### ISSUE TITLE
Create collection

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioHub/synbiohub#1008]
For the uninitiated it is not clear how to create a collection - going via Submit a Design is not intuitive.
The only direct 'Create a Collection' link is on the search page and it is not clear that this creates a collection from the search.
Can a more direct and intuitve way of creating a collection be shown - this is after all pretty much the first thing you need to do, at least that was my perspective.

**Comment by cjmyers** [comment]
Agree this is very confusing.  I've made several UI changes that I hope will help.  

1) The submit page now says explicitly that you can "Create a New Collection" and the file upload is now optional.
2) I've removed the "create collection" option from search.
3) I've added the ability to create collections from search results at the bottom of the advanced search page.  @geoffbaldwin: what do you think?

<img width="967" alt="Screen Shot 2020-05-25 at 11 47 18 AM" src="https://user-images.githubusercontent.com/3507191/82834259-c9aed400-9e7d-11ea-9537-cc36aefc3841.png">
<img width="543" alt="Screen Shot 2020-05-25 at 11 46 45 AM" src="https://user-images.githubusercontent.com/3507191/82834262-cb789780-9e7d-11ea-9345-87933520c929.png">
<img width="753" alt="Screen Shot 2020-05-25 at 11 46 30 AM" src="https://user-images.githubusercontent.com/3507191/82834263-cc112e00-9e7d-11ea-99e2-b6b9b433830c.png">

**Comment by geoffbaldwin** [comment]
Thanks @cjmyers , this looks good, it definitely clarifies things.
