### ISSUE TITLE
Alternative names with dc:alternative

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#1070]
As `dc:title` is being used for names, we are going to use the recommended related term `dc:alternative` for alternative names.  Can this please render on synbiohub in the same way that alternative names with  `rdfs:label` are rendered?

**Comment by cjmyers** [comment]
Should be simple.  Will include in the release for 1.5.3 that we will try to do early next week.

**Comment by cjmyers** [comment]
Fixed in PR #1071
