### ISSUE TITLE
Refactor submit.js to fix Heisenbug.

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1077]
There is a timing issue at line 105 on submit.js.  This appears occasionally when running the SBH SBOLTestSuite.  It appears to occur consistently when adding a collection with the new auth module.  

Refactor the code to see if we can eliminate this timing issue on processing of forms, and test both in master and the auth PR.

**Comment by 3ach** [comment]
I'm pretty sure this can be closed. We've been running on the new submit for ~3 months.
