### ISSUE TITLE
Arrows on pulls downs don't always work correctly

### ISSUE THREAD

**Issue by jcromano** [SynBioHub/synbiohub#1078]
On this page: https://synbiohub.org/public/igem/BBa_F2620/1
When the page is first rendered, all of the arrows point downward.  If you click on a downward arrow to open up more information, the remains downward.  If you click on the arrow to collapse the information, the arrow is now pointing to the right.  Subsequent clicks on the arrow are consistent with the arrow pointing to the right when the information if collapsed and down when the information is expanded.  You should decide what the arrows are supposed to indicate.  For example, the ability to collapse/expand the information, or the state of the collapse/expand of the information.  Right now the initial state is inconsistent with the state after you expand and collapse the information

**Comment by cjmyers** [comment]
Not sure how to fix this one.  It seems to be a problem with the style we are using for this:

https://codepen.io/trabontea/pen/kkJKdg
