### ISSUE TITLE
Need tests for edit endpoints

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1087]
Should test the /updateMutableDescription, /updateSource, /updateNotes, /updateCitations endpoints with the following tests:
1) uri/value for a page that a user has rights to, without accept header
2) uri/value for a page that a user does not have rights to, without accept header
3) uri/value for a page that a user has rights to, with accept header text/plain
4) uri/value for a page that a user does not have rights to, with accept header text/plain

**Comment by cjmyers** [comment]
Should also test add/edit/remove field

**Comment by jvscholz** [comment]
updated issue #1305
