### ISSUE TITLE
Test the download endpoints

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1093]
Add tests for the download endpoints, /gff, /gb, /fasta, /summary, /omex, /sbol, and /sbolnr.  Tests should include the following:

1) Successful download
2) Not found due to wrong URI, both with and without accept header text/html
3) Not found due to URI not allowed to access, both with and without accept header text/html
4) For gff, gb, fasta there should be a test to download an object that cannot to convert to these formats both with and without accept header text/html

**Comment by jvscholz** [comment]
updated issue #1302
