### ISSUE TITLE
Document user endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1111]
app.all('/logout', views.logout)
  app.all('/resetPassword/token/:token', actions.resetPassword)
  app.all('/resetPassword', views.resetPassword)
  app.post('/setNewPassword', actions.setNewPassword)
  app.all('/profile', requireUser, views.profile)

**Comment by jvscholz** [comment]
Done, please take a look @cjmyers @3ach 

https://synbiohub.github.io/api-docs/

**Comment by cjmyers** [comment]
For logout, flip the first two lines and remove the third line.

**Comment by jvscholz** [comment]
Updated
