### ISSUE TITLE
Document Edit Endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1114]
app.post('/updateMutableDescription', requireUser, actions.updateMutableDescription)
  app.post('/updateMutableNotes', requireUser, actions.updateMutableNotes)
  app.post('/updateMutableSource', requireUser, actions.updateMutableSource)
  app.post('/updateCitations', requireUser, actions.updateCitations)

  app.post('/user/:userId/:collectionId/:displayId/:version/edit/:field', requireUser, api.editObject)
  app.post('/user/:userId/:collectionId/:displayId/:version/add/:field', requireUser, api.addObject)
  app.post('/user/:userId/:collectionId/:displayId/:version/remove/:field', requireUser, api.removeObject)

**Comment by cjmyers** [comment]
Make sure to include:

Add Field
Edit Field 
Remove Field

**Comment by cjmyers** [comment]
Done
