### ISSUE TITLE
Doucment search endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1117]
app.get('/search/:query?', views.search)
  app.get('/searchCount/:query?', views.search)

  app.get('/advancedSearch', views.advancedSearch)
  app.post('/advancedSearch', views.advancedSearch)

  app.get('/createCollection', views.advancedSearch)
  app.post('/createCollection', views.advancedSearch)

  app.get('/:type/count', api.count)
  app.get('/rootCollections', api.rootCollections)

  app.get('/public/:collectionId/:displayId/:version/subCollections', api.subCollections)
  app.get('/public/:collectionId/:displayId/:version/twins', views.search)
  app.get('/public/:collectionId/:displayId/:version/uses', views.search)
  app.get('/public/:collectionId/:displayId/:version/similar', views.search)

  app.get('/user/:userId/:collectionId/:displayId/:version/subCollections', api.subCollections)
  app.get('/user/:userId/:collectionId/:displayId/:version/twins', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/uses', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/similar', views.search)

  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/subCollections', api.subCollections)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/twins', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/uses', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/similar', views.search)

  app.get('/sparql', sparql)
  app.post('/sparql', bodyParser.urlencoded({ extended: true }), sparql)

**Comment by jvscholz** [comment]
Finished, can you take a look @cjmyers @3ach 

https://synbiohub.github.io/api-docs/

**Comment by jvscholz** [comment]
Finished, can you take a look @cjmyers @3ach

https://synbiohub.github.io/api-docs/

**Comment by cjmyers** [comment]
Count objects -> Count Objects
" ... within a specified .. " => " ... with a specified..."

**Comment by jvscholz** [comment]
Updated
