### ISSUE TITLE
Document Manage Submissions Endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1119]
app.post('/public/:collectionId/:displayId/:version/icon', requireUser, uploadToMemory.single('collectionIcon'), actions.updateCollectionIcon)

  app.get('/public/:collectionId/:displayId/:version/removeCollection', requireAdmin, actions.removeCollection)
  app.get('/user/:userId/:collectionId/:displayId/:version/removeCollection', requireUser, actions.removeCollection)

  app.get('/user/:userId/:collectionId/:displayId/:version/remove', requireUser, actions.remove)
  app.get('/user/:userId/:collectionId/:displayId/:version/replace', requireUser, actions.replace)
  app.get('/user/:userId/:collectionId/:displayId/:version/makePublic', requireUser, actions.makePublic)
  app.post('/user/:userId/:collectionId/:displayId/:version/makePublic', requireUser, uploadToMemory.single('file'), actions.makePublic)

  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/remove', actions.remove)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/replace', actions.replace)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/makePublic', actions.makePublic)
  app.post('/user/:userId/:collectionId/:displayId/:version/:hash/share/makePublic', uploadToMemory.single('file'), actions.makePublic)

**Comment by cjmyers** [comment]
Make sure to also have submit code too.

**Comment by cjmyers** [comment]
This one is needed too:

app.post('/public/:collectionId/:displayId/:version/icon', requireUser, uploadToMemory.single('collectionIcon'), actions.updateCollectionIcon)

**Comment by jvscholz** [comment]
@cjmyers 

Do you have any examples of collections with icons? Thanks

**Comment by cjmyers** [comment]
iGEM does:

https://synbiohub.org/public/igem/igem_collection/1 <https://synbiohub.org/public/igem/igem_collection/1>

BTW: this endpoint though is used to add an icon to a collection.

**Comment by cjmyers** [comment]
Done
