### ISSUE TITLE
Document Update Permissions Endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1120]
app.get('/public/:collectionId/:displayId/:version/addOwner', requireUser, views.addOwner)
  app.post('/public/:collectionId/:displayId/:version/addOwner', requireUser, views.addOwner)
  app.post('/public/:collectionId/:displayId/:version/removeOwner/:username', requireUser, actions.removeOwner)

  app.get('/user/:userId/:collectionId/:displayId/:version/addOwner', requireUser, views.addOwner)
  app.post('/user/:userId/:collectionId/:displayId/:version/addOwner', requireUser, views.addOwner)
  app.post('/user/:userId/:collectionId/:displayId/:version/removeOwner/:username', requireUser, actions.removeOwner)

  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/addOwner', views.addOwner)
  app.post('/user/:userId/:collectionId/:displayId/:version/:hash/share/addOwner', views.addOwner)
  app.post('/user/:userId/:collectionId/:displayId/:version/:hash/share/removeOwner/:username', actions.removeOwner)

**Comment by cjmyers** [comment]
Done
