### ISSUE TITLE
Document Attachment Endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1121]
app.post('/public/:collectionId/:displayId/:version/attach', requireUser, actions.upload)
  app.post('/public/:collectionId/:displayId/:version/attachUrl', requireUser, api.attachUrl)
  app.get('/public/:collectionId/:displayId/:version/download', api.download)

  app.post('/user/:userId/:collectionId/:displayId/:version/attach', requireUser, actions.upload)
  app.post('/user/:userId/:collectionId/:displayId/:version/attachUrl', requireUser, api.attachUrl)
  app.get('/user/:userId/:collectionId/:displayId/:version/download', requireUser, api.download)

  app.post('/user/:userId/:collectionId/:displayId/:version/:hash/share/attach', actions.upload)
  app.post('/user/:userId/:collectionId/:displayId/:version/:hash/share/attachUrl', api.attachUrl)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/download', api.download)

**Comment by jvscholz** [comment]
I believe that the download endpoint shouldn't be documented.
Done, please take a look @cjmyers @3ach

**Comment by cjmyers** [comment]
No curl example for attachURL, also no python/javascript examples for either.

**Comment by cjmyers** [comment]
Download attachments goes in download endpoints

**Comment by cjmyers** [comment]
Done
