### ISSUE TITLE
Document Download Endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1122]
app.get('/public/:collectionId/:displayId/sbol', api.persistentIdentity)
  app.get('/public/:collectionId/:displayId/sbolnr', api.persistentIdentity)
  app.get('/user/:userId/:collectionId/:displayId/sbol', api.persistentIdentity)
  app.get('/user/:userId/:collectionId/:displayId/sbolnr', api.persistentIdentity)

  app.get('/public/:collectionId/:displayId/:version/sbol', api.sbol)
  app.get('/public/:collectionId/:displayId/:version/sbolnr', api.sbolnr)
  app.get('/public/:collectionId/:displayId/:version/omex', api.omex)
  app.get('/public/:collectionId/:displayId/:version/summary', api.summary)
  app.get('/public/:collectionId/:displayId/:version/fasta', api.fasta)
  app.get('/public/:collectionId/:displayId/:version/gb', api.genBank)
  app.get('/public/:collectionId/:displayId/:version/gff', api.gff3)
  app.get('/public/:collectionId/:displayId/:version/metadata', api.metadata)

  app.get('/user/:userId/:collectionId/:displayId/:version/sbol', api.sbol)
  app.get('/user/:userId/:collectionId/:displayId/:version/sbolnr', api.sbolnr)
  app.get('/user/:userId/:collectionId/:displayId/:version/omex', api.omex)
  app.get('/user/:userId/:collectionId/:displayId/:version/summary', api.summary)
  app.get('/user/:userId/:collectionId/:displayId/:version/fasta', api.fasta)
  app.get('/user/:userId/:collectionId/:displayId/:version/gb', api.genBank)
  app.get('/user/:userId/:collectionId/:displayId/:version/gff', api.gff3)
  app.get('/user/:userId/:collectionId/:displayId/:version/metadata', api.metadata)

  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/sbol', api.sbol)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/sbolnr', api.sbolnr)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/omex', api.omex)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/summary', api.summary)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/fasta', api.fasta)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/gb', api.genBank)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/gff', api.gff3)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/metadata', api.metadata)

  app.get('/public/:collectionId/:displayId/:version/visualization', views.visualization)
  app.get('/user/:userId/:collectionId/:displayId/:version/visualization', views.visualization)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/visualization', views.visualization)

**Comment by jvscholz** [comment]
Done

**Comment by jvscholz** [comment]
Can you have a look @cjmyers @3ach 

https://synbiohub.github.io/api-docs/

**Comment by cjmyers** [comment]
Looks good.
