### ISSUE TITLE
Test '/public/:collectionId/:displayId/:version/ endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1133]
[synbiohub test] Warning- get endpoint public/:collectionId/:displayId/:version/subCollections was not tested.
[synbiohub test] Warning- get endpoint public/:collectionId/:displayId/:version/twins was not tested.

**Comment by jvscholz** [comment]
[synbiohub test] Warning- get endpoint public/:collectionId/:displayId/:version/similar was not tested. as well

**Comment by cjmyers** [comment]
Replacing this issue
