### ISSUE TITLE
Test  '/user/:userId/:collectionId/:displayId/:version/

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1134]
app.get('/user/:userId/:collectionId/:displayId/:version/subCollections', api.subCollections)
  app.get('/user/:userId/:collectionId/:displayId/:version/twins', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/uses', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/similar', views.search)

**Comment by cjmyers** [comment]
Replacing this issue
