### ISSUE TITLE
Test /user/:userId/:collectionId/:displayId/:version/:hash/share/

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1135]
app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/subCollections', api.subCollections)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/twins', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/uses', views.search)
  app.get('/user/:userId/:collectionId/:displayId/:version/:hash/share/similar', views.search)

**Comment by cjmyers** [comment]
Replacing this issue
