### ISSUE TITLE
Add glyphs when displaying list of parts in SynBioHub

### ISSUE THREAD

**Issue by goksel** [SynBioHub/synbiohub#114]
This is on the results returned from search.

**Comment by 16zzundel5** [comment]
Are you looking for something like this?
<img width="1166" alt="screen shot 2017-05-18 at 3 09 10 pm copy" src="https://cloud.githubusercontent.com/assets/3093325/26206249/330d43bc-3bdc-11e7-88cf-a6be21afd465.png">

**Comment by cjmyers** [comment]
Yeah, I think so.  I think it is okay a bit more to the right.  It should be the top-level Role glyph, so Engineered Regions (composites) will be the good old “box”.

FYI: the experimentalists I met last week asked why Box is used for both Composite and Basic with no assigned glpyh.

Chris

**Comment by zachzundel** [comment]
I'm going to move this to SBH 1.1.0, because this is going to require some modifications to visbol.
