### ISSUE TITLE
How can I make private a collection public?

### ISSUE THREAD

**Issue by Gonza10V** [SynBioHub/synbiohub#1153]
Hi, I have a private collection of new constructions and want to make it public. I remember that this was easy in the past now I can not do it. Can someone help me please?

**Comment by cjmyers** [comment]
Only curators can make objects public.  Which instance are you using?  A public one or your own?

**Comment by Gonza10V** [comment]
Im using the public instance,  can I be curator in the public one? I want to share the DNA that we fabricate and use in my lab. I i can not be curator on the public instance the only way to share it is creating a private instance and make myself curator?

**Comment by cjmyers** [comment]
The idea of restricting making records public to a curator is to ensure quality control on the public records.  I would be happy to examine your collection and make it public.  To do so, please send me by email (myers@ece.utah.edu) a share link to your collection that you would like to make public.

**Comment by Gonza10V** [comment]
When parts become public the URI change? Can I edit my construction later?

**Comment by cjmyers** [comment]
Yes, the URI will change.  No, you cannot edit public records.  Or more precisely, you can only do edits to mutable description fields, add a pubmed id, etc. 

The reason for this is that once you publish, others may use your record and they need a stable version to refer to.  If you modify it, you should publish a new version linked via the wasDerivedFrom field to the old version.

**Comment by cjmyers** [comment]
@Gonza10V Any further questions on this one?
