### ISSUE TITLE
Add filtering capability to collection browser

### ISSUE THREAD

**Issue by kevinwkeating** [SynBioHub/synbiohub#1171]
I'm going through the Bacillus collection and it would be nice to be able to filter by a particular part type so you could easily pull out all the promoters, CDS or terminators.

**Comment by cjmyers** [comment]
This is a great idea.  I think what I will do is change the Type entry to be a more specific type, such as Promoter, CDS, Terminator, Protein, etc.  This is a little bit involved to execute, but I will prioritize it for 1.5.5.
