### ISSUE TITLE
Reset password function not working

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1174]
On synbiohub.org, using the reset password link sent to email returns an error like this 

Cannot GET //resetPassword/token/d0170b87574a35a19c54ce761a49d3820eb53e20

**Comment by cjmyers** [comment]
This likely no longer works, since sendgrid changed their pricing.  We need to find a new solution for forwarding email.

**Comment by cjmyers** [comment]
So, my sendgrid account will allow 100 emails per day for testing purposes, which is probably fine for now.  Might want a real account at some point or setup some similar service somehow.

The actual bug is there is an extra "/" in the URL that is sent for some reason.
