### ISSUE TITLE
Get SBOL request without /sbol at the end doesn't work 

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1181]
Works: 
curl -X GET -H "Accept: text/plain" -H "X-authorization: <token>" https://synbiohub.org/public/igem/BBa_F2620/1/sbol

Doesn't work
curl -X GET -H "Accept: text/plain" -H "X-authorization: <token>" https://synbiohub.org/public/igem/BBa_F2620/1

**Comment by cjmyers** [comment]
@jvscholz Actually, this is not a bug.  You cannot test your endpoints against https://synbiohub.org, since it is not updated yet.  This works:

curl -X GET -H "Accept: text/plain" http://localhost:7777/public/igem/BBa_F2620/1
