### ISSUE TITLE
problems cloning the project

### ISSUE THREAD

**Issue by MadraghRua** [SynBioHub/synbiohub#1183]
Hi Folks
I'm using Git on Windows 10. I ran the command git clone  https://github.com/SynBioHub/synbiohub.git

I ran into problems as the clone took place. You can see the dialog below. Basically I can see the code in my local folder but I wasn't sure how significant the error messages were.
---------------------------------------------------------------------------------------------------------
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 17605 (delta 37), reused 68 (delta 26), pack-reused 17505
Receiving objects: 100% (17605/17605), 70.27 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (12597/12597), done.
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId(*)-:version-full_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId(*)-:version_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId-:version-addOwner_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId-:version-copyFromRemote_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId-:version-createSnapshot_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId-:version-metadata_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId-:version-uses_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId-:version-visualization_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId-sbolnr_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId_bbapublic.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_public-:collectionId-:displayId_docker_public.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_user-:userId-:collectionId-:displayId-:version-addOwner_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_user-:userId-:collectionId-:displayId-:version-makePublic_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_user-:userId-:collectionId-:displayId-:version-removeCollection_.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_user-:userId-:collectionId-:displayId-:version-removeCollection_remove_second.html: Invalid argument
error: unable to create file tests/previousresults/getrequest_user-:userId-:collectionId-:displayId_docker.html: Invalid argument
error: unable to create file tests/previousresults/postrequest_user-:userId-:collectionId-:displayId-:version-makePublic_.html: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by cjmyers** [comment]
Very strange.  I just did the same command in a clean directory and it worked fine.  Were you checking out in a clean directory or over top of an existing checkout?
