### ISSUE TITLE
Add Sequence Search to the API Documentation

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1220]
Sequence search adds some new parameters, this and explanation to of how to do sequence search from the API would be good.

**Comment by jvscholz** [comment]
@yu-eric 

Could you provide the key-value pairs and their descriptions to append to this table? Thanks

![Screenshot from 2020-04-24 14-10-58](https://user-images.githubusercontent.com/45739456/80252893-7e629500-8635-11ea-8b6a-5a6c92756f5d.png)

**Comment by yu-eric** [comment]
@jvscholz All the sequence search key-value pairs route through the /search/ endpoint. Currently, the list of flags (and their default values) are:

globalFlags = {'maxaccepts': '50', 'id': '0.8', 'iddef': '2', 'maxrejects': '0', 'maxseqlength': '5000', 'minseqlength': '20'}

where globalFlags is the flags compatible with global search. No flags are used in exact search.

To use these flags, the key value pair would be "flag_{key}={value}&", key being one of the flags in the list above.

For searching, the KVP for global search is "globalsequence={sequence}&", and for exact search, "sequence={sequence}&"

As for the descriptions, I think it would be best if we directly took what is written in the VSearch manual (found here: https://github.com/torognes/vsearch/releases/download/v2.14.2/vsearch_manual.pdf).

**Comment by cjmyers** [comment]
Done
