### ISSUE TITLE
Cannot pull synbiohub docker image

### ISSUE THREAD

**Issue by tcmitchell** [SynBioHub/synbiohub#1229]
When I try to pull the synbiohub docker image as indicated at https://hub.docker.com/r/synbiohub/synbiohub it fails:

```
$ docker pull synbiohub/synbiohub
Using default tag: latest
Error response from daemon: manifest for synbiohub/synbiohub:latest not found
```

Additionally, with the myriad `travis-*` tags it is hard to find the latest version to use without the availability of the `latest` tag. An alphabetical sort helps, but it is still left to the user to deduce what version they should be running.

**Comment by cjmyers** [comment]
The latest version is -snapshot.  However, you cannot run SBH alone.  You need to use docker-compose.  Please see instructions here:

https://synbiohub.github.io/api-docs/#from-prebuilt-image
