### ISSUE TITLE
Auto update on commit

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#123]
When there is a commit on the master branch, automatically have synbiohub.org do a pull and restart.  Perhaps, also with sbolstack-api.

**Comment by cjmyers** [comment]
Let's wait until we have continuous integration.

**Comment by 16zzundel5** [comment]
This is currently added at /admin/update

**Comment by cjmyers** [comment]
There is a problem if you do an update that crashes the server due to a problem with the commit.  This happens if, for example, you fail to commit all the files.  It would be useful if the server goes into a simplified mode where it only supports the Admin page and allows you to try to update again after you have fixed the commit.

**Comment by 16zzundel5** [comment]
I'm closing this issue and moving it to the [roadmap](http://wiki.synbiohub.org/wiki/Roadmap).
