### ISSUE TITLE
Cannot upload project to SynBioHub

### ISSUE THREAD

**Issue by Fontanapink** [SynBioHub/synbiohub#1230]
When trying to upload a project to https://synbiohub.org/ I get an error: 

> org.synbiohub.frontend.SynBioHubException: {}

The following are the steps I followed:
1) open eclipse
2) open project
3) click upload 
3) sign in to synbiohub
4) Add the following to the window pop-up:
Collection ID: TestingTheUpload
Collection Version: 1
Collection Name: TestingTheUploadFeature
Collection Description: This is a test for upload
Citations (optional): 

5) I get the following error: **org.synbiohub.frontend.SynBioHubException: {}** and no error messages in Eclipse's log.

Here is the project itself:
[Circuit0x8E.zip](https://github.com/SynBioHub/synbiohub/files/4546324/Circuit0x8E.zip)

**Comment by cjmyers** [comment]
Problem is with the file, but the error message could be better.

**Comment by cjmyers** [comment]
@Fontanapink better error message is given.  The actual bug here though is with iBioSim somehow creating problems in the SBOL that it submits.  Please re-log this bug in the iBioSim tracker.
