### ISSUE TITLE
synbiohub messed up by incorrect baseColor in /admin/theme

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1275]
feeding the post /admin/theme variable baseColor with a bad input makes the entire site look broken. it should throw an error or warning if the value isn't correct
![Screenshot from 2020-05-29 13-08-57](https://user-images.githubusercontent.com/45739456/83296243-ace00c80-a1ad-11ea-8f79-3ec235de1c52.png)

**Comment by cjmyers** [comment]
Yikes!  Good catch!

**Comment by jvscholz** [comment]
it would also be cool if you made the variable only take in 6 hex values instead of #+6 hex values, it's annoying to deal with the hash in the console.
