### ISSUE TITLE
Add SBOLExplorer to the test suite

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1286]
Should start SBOLExplorer in our testing script, and run tests against it.

**Comment by jvscholz** [comment]
hey Eric,

I got the test suite to include explorer by changing line 6 of start_containers_persist.sh to. 
`
docker-compose -f ./synbiohub-docker/docker-compose.yml -f ./synbiohub-docker/docker-compose.explorer.yml  -p testsuiteproject up -d
`
 it does fetch the latest explorer, however, I can't get it to connect to synbiohub. it says that sbolexplorer is not responding. any ideas?

**Comment by jvscholz** [comment]
I put my changes in a branch add_explorer_to_testsuite

**Comment by cjmyers** [comment]
@yu-eric @jvscholz You probably need to set the SBOLExplorer endpoint to:

http://explorer:13162/

Once it is up, you need to set the Elasticsearch endpoint to:

http://elasticsearch:9200/

And virtuoso endpoint to:

http://virtuoso:8890/sparql?

**Comment by jvscholz** [comment]
I tried that but get this error 
![Screenshot from 2020-06-05 08-52-56](https://user-images.githubusercontent.com/45739456/83891153-fd092280-a709-11ea-97a6-c3c6d1fc7a45.png)

**Comment by cjmyers** [comment]
The SBOLExplorer endpoint should be in docker: http://explorer:13162/ and not localhost

**Comment by jvscholz** [comment]
Alright, that fixed it. it says localhost:13162 on the [sbolexplorer github page](https://github.com/SynBioDex/SBOLExplorer) on step 9. is this specific to this application or is it incorrect on the readme?

**Comment by cjmyers** [comment]
It is correct when run as standalone from source.  However, when run in docker, it is incorrect.  Likely we should update default configs in the docker-compose to have this one in place.
