### ISSUE TITLE
Add glyph for mature transcript region

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#129]

**Comment by 16zzundel5** [comment]
Moved to visbol issue 13

**Comment by cjmyers** [comment]
Has this been published to npm?

**Comment by 16zzundel5** [comment]
Not yet. I had to remove a problematic section of the VisBOL code that I don't *think* will cause an error, but I've tagged @udp in the commit so that I can verify it before publishing in case it is broken.
