### ISSUE TITLE
Missing "filename" parameter in Content-Disposition causes submission to fail without error

### ISSUE THREAD

**Issue by tim-tx** [SynBioHub/synbiohub#1294]
I was previously able to send a request to the SynBioHub `submit` endpoint with a payload containing:
```
Content-Disposition: form-data; name="file"
Content-Type: application/octet-stream
Content-Length: 79024

<?xml version="1.0" ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sbol="http://sbols.org/v2#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:om="http://www.ontology-of-units-of-measure.org/resource/om-2/">
  <sbol:ModuleDefinition rdf:about="http://cellocad.org/v2/Design0_Module">
  ...
```

Recently I noticed that while the same request still returned `HTTP/1.1 200 OK` and the response `Successfully uploaded`, and still created a collection on SynBioHub, the GUI showed the collection as being empty.

Only by including the `filename` parameter in the `Content-Disposition` header for the file could I get the SBOL content to appear in the collection:
```
Content-Disposition: form-data; name="file"; filename="myfile.xml"
Content-Type: application/octet-stream
Content-Length: 79024

<?xml version="1.0" ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sbol="http://sbols.org/v2#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:om="http://www.ontology-of-units-of-measure.org/resource/om-2/">
  <sbol:ModuleDefinition rdf:about="http://cellocad.org/v2/Design0_Module">
  ...
```

I would think the request should fail if `filename` is not included. There is also no mention of this requirement in the API documentation here: https://synbiohub.github.io/api-docs/#submit.

**Comment by cjmyers** [comment]
What language are you using?  I don't see this being explicitly done in the examples, but I'm wondering if it is done implicitly by curl, python, and javascript.

**Comment by tim-tx** [comment]
This is in Java, using Spring Boot. I'm not using libSBOLj's SynBioHubFrontend -- building the request manually was a lot simpler and easier than figuring out how to persist SynBioHubFrontend instance for each user session. Adding `filename` is done implicitly by curl when you load a file like `-F "file=@myfile.xml"`, but no language would need to set a `filename` if handed just a byte array, e.g. if that SBOL document were never associated with a file.

**Comment by cjmyers** [comment]
Good point.  We will get this added to the documentation.

**Comment by jvscholz** [comment]
@tim-tx Hey, I'm the guy working on the SynBioHub API documentation.

I'm sort of confused as to what I should do. Is 'filename' required for submit post requests to SynBioHub? It appears to work for curl, python, and javascript, so specifying the filename is required for requests outside those languages? If you could clarify for me, I'd appreciate it.

**Comment by tim-tx** [comment]
I would just add a note saying something like:
The `filename` parameter must be present in the `Content-Disposition` header of the `file` part of the submit request. Many request-handling libraries (curl, Python’s `requests`) add this automatically if passed a file object, but if `filename` is omitted, the SBOL content will not be accepted.

Example acceptable header:
`Content-Disposition: form-data; name="file"; filename="foo"`

**Comment by jvscholz** [comment]
updated
