### ISSUE TITLE
Test download endpoints

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1302]
The following endpoints still require testing:

- [x] GET <URI>/sbol OR GET <URI>
- [x] GET <URI>/sbolnr
- [ ] GET <URI>/metadata
- [ ] GET <URI>/gb
- [ ] GET <URI>/fasta
- [ ] GET <URI>/gff
- [ ] GET <URI>/download

    Successful download
    Not found due to wrong URI, both with and without accept header text/html
    Not found due to URI not allowed to access, both with and without accept header text/html
    For gff, gb, fasta there should be a test to download an object that cannot to convert to these formats both with and without accept header text/html

**Comment by jvscholz** [comment]
updates issue #1093

**Comment by cjmyers** [comment]
Also include /summary and add to api docs too (returns JSON)

**Comment by cjmyers** [comment]
/metadata and /summary return JSON, must compare with diff

/download returns an attachment, so if you attach a text, can compare with diff

All other use SBOL Validator
