### ISSUE TITLE
Symbiohub Sbol exporter has a broken link to wiki.synbiohub.org  resource

### ISSUE THREAD

**Issue by linediconsine** [SynBioHub/synbiohub#1322]
Hello

I hope this is the right place to add this feedback.

If I export as SBOL a file from symbiohub.org (in my test I used BBa_K1080006 (Plastocyanin) )
then I see this XML SBOL a node:

`<sbol:role rdf:resource="http://wiki.synbiohub.org/wiki/Terms/igem#partType/Coding"/>`

When I will visit this link http://wiki.synbiohub.org/wiki/Terms/igem#partType/Coding I will be redirected to 
http://wiki.synbiohub.org/wiki/Terms/igem#partType/Coding ( that I believe is the wrong page)

Thanks

**Comment by cjmyers** [comment]
These are URIs for the iGEM part type fields that were generated to preserve this information when we converted from the iGEM database to SBOL.  URIs are not URLs meaning they do not need to take you to a website, though often they are such as in the case of the Sequence Ontology role fields that are also present.  In the case of the iGEM role, we have never found an adequate definition for these terms, so we have left them as simply URIs with no dereference.

**Comment by linediconsine** [comment]
HI CJ Myers and thanks for your reply. 

Just for my understanding 

In this node:
`<sbol:role rdf:resource="http://wiki.synbiohub.org/wiki/Terms/igem#partType/Coding"/>`
 should consider only '#partType/Coding' and mark the component as coding sequence.

Please bear with me, I am a  CS, not a biologist so I could be losing something important here

**Comment by linediconsine** [comment]
Thanks for this feedback!
