### ISSUE TITLE
Multifile uploads lead to collection unlinking

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub#1351]
It seems that both if you upload a zip file containing multiple genbank files and if you run an api call to submit multiple files it leads to the unlinking of the collection somehow. Leading to the collection still displaying under submissions but the error: `TypeError: Cannot read property 'name' of undefined` if you click on the collection to view it. Additionally, further api submissions are still possible and if you search you can find the parts in the collection and linked to the collection but the collection link is broken.

**Comment by cjmyers** [comment]
I cannot reproduce this one.  What I did was:

1) Create a collection called "test"
2) Submitted the zip to this collection.
