### ISSUE TITLE
I can't access any part details

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioHub/synbiohub#1379]
I can search for parts e.g. 'LacI' and I can see a whole list of entries. When I click on any of these it is broken and I can't get to the parts. 
I would like to use this resource in a teaching module in 2 weeks, but it is going to be difficult if it is broken!

**Comment by geoffbaldwin** [comment]
This relates to the Living computing project:
https://synbiohub.programmingbiology.org/
sorry if this wasn't clear in the first post

**Comment by cjmyers** [comment]
Should be fixed now.

**Comment by geoffbaldwin** [comment]
Thanks - now working at my end.
