### ISSUE TITLE
change of colour scheme

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioHub/synbiohub#1383]
This is a trivial one, but I just setup our SynBioHub instance with the default brown colour. I'd like to change it to blue.

Admin>Theme> Base color = #d25627

Anyone know the code for a nice dark blue colour?

**Comment by cjmyers** [comment]
Can use this color chooser:

https://www.hexcolortool.com/#0558ff

**Comment by geoffbaldwin** [comment]
Thanks
