### ISSUE TITLE
Download Image is Not working

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub#1393]
I think this is a visbol issue. When download image is selected nothing happens e.g. for https://synbiohub.org/public/bsu/module_BO_30843_encodes_BO_11239/1
and https://synbiohub.org/public/bsu/BO_30843/1

**Comment by cjmyers** [comment]
This is indeed a bug or at least something that has not been implemented yet in the new VisBol.  I will move this issue to the VisBol issue tracker.
