### ISSUE TITLE
Link to the definition of instance on a component page is wrong.

### ISSUE THREAD

**Issue by PRUBHTEJ** [SynBioHub/synbiohub#1394]
The **i** button for instance on the component page which is for further information, redirects to the wrong page.

The page it directs to is [here](https://dissys.github.io/sbol-owl/sbol-owl.html#Component) and where it should possibly direct is [here](http://sbols.org/v2#ComponentInstance).

**Comment by cjmyers** [comment]
Think this one is okay, in SBH Component = ComponentDefinition
