### ISSUE TITLE
Clicking Sequence(310 bp) directs to a broken link

### ISSUE THREAD

**Issue by PRUBHTEJ** [SynBioHub/synbiohub#1395]
On [this](https://synbiohub.org/public/igem/BBa_K1444010_sequence/1) page, if we click on the **Sequence (310 bp)** option, it directs to [this](https://www.qmul.ac.uk/undergraduate/coursefinder/courses/2020/chemistry//) page, which is probably not right and hence needs to be replaced.

**Comment by cjmyers** [comment]
Seems fixed
