### ISSUE TITLE
SynBioHub portal keeps reloading design pages

### ISSUE THREAD

**Issue by tzielins** [SynBioHub/synbiohub#1399]
The page for designes keeps reloading.
It looks like it is never loads completely (though renders all the details) and then reloads.
Dev tools, show series of  api requests with different UUID like:

https://synbiohub.org/api/stream/25973902-5764-420e-96f6-ca5011ba2ec1

some of which fail.

I experience it on all my designs, for example
https://synbiohub.org/user/tzielins/cyano_test/backbone/1.0.0

or public ones
https://synbiohub.org/public/bsu/BO_27977/1

I belive the problem first appear after the viaualization update couple of months back.

**Comment by cjmyers** [comment]
Sorry for the delay in responding to this.  There was a problem when plugins (namely our iGEM plugin) fails to respond properly.  This has been fixed on the dev server, as you can see here:

https://dev.synbiohub.org/public/bsu/BO_27977/1

You can try your private ones as well by adding "dev." to the domain.  

We have turned off the problematic plugins on the main server, which should cause the refreshing to stop.  We will restore them when we update the production server.  Please let us know if you have any further issues.
