### ISSUE TITLE
Search Metadata API Endpoint with SBOL Tags

### ISSUE THREAD

**Issue by jhay-epcc** [SynBioHub/synbiohub#1414]
Hello,

I would like to use the search metadata endpoint (https://wiki.synbiohub.org/api-docs/?python#search-metadata) to retrieve designs, and I would like to use SBOL namespace tags in the search parameters. I am not having any success however when I do this, for example:

https://synbiohub.org/search/%3Chttp%3A%2F%2Fsbols.org%2Fv2%23displayId%3E%3DBBa_K318030.

As far as I understand it, that should retrieve the design located at https://synbiohub.org/public/igem/BBa_K318030/1, because I am specifying 'BBa_K318030' for the http://sbols.org/v2#displayId namespace/tag.

Please could you help me get the right URL and request parameters to do this? Thanks!

Johnny

**Comment by cjmyers** [comment]
This query was missing the quotes around the string and the ampersand at the end.  This query works for me:

curl -X GET -H "Accept: text/plain" https://synbiohub.org/search/displayId%3D\'BBa_K318030\'%26

[{"type":"http://sbols.org/v2#ComponentDefinition","uri":"https://synbiohub.org/public/igem/BBa_K318030/1","name":"\"Lock\"","description":"lox66 + rpCons + hixC + lox71 + SapI + T + T + Hin enhancer + HindIII + hixC","displayId":"BBa_K318030","version":"1","percentMatch":"","strandAlignment":"","CIGAR":""}]

**Comment by jhay-epcc** [comment]
Wonderful, thank you very much. Adding the single quotes and trailing ampersand fixed the request and I have got it working in my application now!

Cheers,

Johnny
