### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub#1415]
When uploading an xml file that passed the validator test there was an error when viewing the collection. The error was just given as: TypeError: Cannot read property 'name' of undefined
Further digging through logs revealed: 
TypeError: Cannot read property ‘name’ of undefined
    at Object.shortName (/Users/myers/git/synbiohub/lib/summarize/namespace.js:38:45)
    at /Users/myers/git/synbiohub/lib/views/topLevelView.js:165:33

which was an issue with a new SO term (SO:0002251). This is an issue both in an unhelpful error message to the users and the lack of SO term acceptance

**Comment by cjmyers** [comment]
Fixed by PR #1417
