### ISSUE TITLE
Unexpected Search Behaviour

### ISSUE THREAD

**Issue by jhay-epcc** [SynBioHub/synbiohub#1428]
Hello,

I cannot find designs that I submitted to my private repositories when I use the search function at https://synbiohub.org/search. Is the search function disabled for private repositories?

Also, if I try to search for my designs in private collections using the API endpoint, it fails to find anything either, e.g. https://synbiohub.org/search/objectType=ComponentDefinition&collection=<https%3A%2F%2Fsynbiohub.org%2Fuser%2Fjhay%2FTestCollection%2FTestCollection_collection%2F1>&<http%3A%2F%2Fsbols.org%2Fv2%23displayId>='left_flank'&/?offset=0&limit=10

The equivalent API request works correctly for public repositories, e.g. https://synbiohub.org/search/objectType=ComponentDefinition&collection=<https%3A%2F%2Fsynbiohub.org%2Fpublic%2Figem%2Figem_collection%2F1>&<http%3A%2F%2Fsbols.org%2Fv2%23displayId>='BBa_K1311000'&/?offset=0&limit=10

Any advice appreciated! Thanks,

Johnny

**Comment by cjmyers** [comment]
We have been having issues with one of our search engines.  I've turned it off for now.  Can you please try again?

**Comment by jhay-epcc** [comment]
Oh great, that's fixed it, thanks! I am now seeing the results I expected when searching for my designs in private collections.

**Comment by jhay-epcc** [comment]
Sorry to be a pain, but I am also trying to search for designs in private collections belonging to my colleague that have been shared with me. These searches are not finding any results, though I would expect them to, e.g. 

https://synbiohub.org/search/objectType=ComponentDefinition&collection=<https%3A%2F%2Fsynbiohub.org%2Fuser%2Ftzielins%2Fa_sbol_testing%2Fa_sbol_testing_collection%2F1>&<http%3A%2F%2Fsbols.org%2Fv2%23displayId>='left_flank'&/?offset=0&limit=10

and the following equivalent search query for https://synbiohub.org/search/ fails to find any results too:

objectType=ComponentDefinition&collection=<https://synbiohub.org/user/tzielins/a_sbol_testing/a_sbol_testing_collection/1>&<http://sbols.org/v2#displayId>='left_flank'&

Both the API request and querying on the /search UI work for my own private repositories, but not for someone else's private repositories that they have shared with me. Thanks in advance!

**Comment by cjmyers** [comment]
This one actually does not surprise me.  Searches are over the public graph and the logged in user's private graph.  Currently, you cannot search over objects shared with you in other user's graphs.  This would be quite challenging to implement in the current scheme in a secure manner.  I'm not sure if there is a straightforward way to do this in the current architecture.  I will leave this issue open as we consider it.  Thanks for pointing this out.

**Comment by jhay-epcc** [comment]
Thanks for the response and information!

**Comment by cjmyers** [comment]
@jhay-epcc We think we fixed the issue with searching in your own private repository with our SBOLExplorer tool (which is now turned back on).  Could you please verify if this is working for you?   If not, please reopen this issue. 

Also, could you log a separate issue about searching through shared objects.  This is going to be a bigger lift.  Thanks.
