### ISSUE TITLE
How to share designs which are still under development on SynBioHub

### ISSUE THREAD

**Issue by tzielins** [SynBioHub/synbiohub#1429]
It is not an issue but a question on how to use SynBioHub to share designs.

I posted a question on bioinformactics stack exchange in the spirit of building a Q&A knowledge base (I don't have enough reputation to create a synbiohub tag).

https://bioinformatics.stackexchange.com/questions/15646/how-to-share-a-collection-of-sbol-designs-in-synbiohub

Here, a shorter version without the reational:

Our initial plan to share designes was:
-	Create a collection with initial designs (component definitions) Stage 1
-	As production progresses add new versions of component if their designs had to change (Stage 2)
-	Stage 3, 4 update designs descriptions (synbio desc or notes) and attach additional files (e.g. from sequencing).

However, our current understanding is the publicly collections are frozen so stage 2,3,4 cannot be accommodated. 

We are seeking advice how to plan for sharing this resource and some clarifications.

1.	Is there a way of making collection readable by others without freezing its content?
2.	What operations are possible on public component definitions, can the free text descriptions/notes be updated or file attached?
3.	Can new component definitions or their versions be added to a published collection
4.	For 2) 3) who can perform these operations, the collection’s creator or SynBio curators?

**Comment by cjmyers** [comment]
Posted an answer on stack exchange.  Thanks.
