### ISSUE TITLE
VisBol Navigator: rendering issues for shared designs

### ISSUE THREAD

**Issue by jhay-epcc** [SynBioHub/synbiohub#1440]
Hello,

I would like to report an issue I am having with the rendering of components in VisBol Navigator for designs I have shared. Here are the steps to reproduce:

1. Upload the attached SBOL file into a collection, e.g. collection name = 'Johnny 19-04-21'
2. Open the uploaded 'cyano_codA_Km' design in SynBioHub, e.g. 'https://synbiohub.org/user/jhay/Johnny190421/cyano_codA_Km/1.0.0'
3. Click on the green 'share' button in the options menu
4. Copy the share link URL
5. Login to SynBioHub as a different user
6. Visit the share link URL

The design is rendered correctly in VisBol Navigator for the owner, e.g. in 
![rendering_issue_owned](https://user-images.githubusercontent.com/48282285/115225539-19d1fd00-a106-11eb-887f-ae3e979caab5.png)

The rendering issues appear for the user with whom the design has been shared, e.g. in 
![rendering_issue_shared](https://user-images.githubusercontent.com/48282285/115225592-2b1b0980-a106-11eb-892d-6395c1e02931.png)

Please could you take a look and advise whether this is being caused by the SBOL document [cyano_sl1099.zip](https://github.com/SynBioHub/synbiohub/files/6335435/cyano_sl1099.zip) or something else?

Thanks!

Johnny

**Comment by cjmyers** [comment]
Thanks for your detailed description. We have been able to reproduce this issue with our VisBol2 tool, and we will try to find a solution soon.  In the future, you can log issues with VisBol2 here:

https://github.com/VisBOL/visbol2
