### ISSUE TITLE
Deleting original after renaming a collection deletes both versions

### ISSUE THREAD

**Issue by joco0061** [SynBioHub/synbiohub#1469]
After renaming a collection, when I viewed my submissions I showed two collections; one was the original collection with the original name, the other had the updated name. I deleted the old/original collection, and both collections disappeared altogether from my submissions.

**Comment by cjmyers** [comment]
This one is very strange.  I can reproduce it.  Namely, it is caused by a second name ('title') being introduced without deleting the first one.  However, when I run the update query manually, it does remove the old titles.

**Comment by cjmyers** [comment]
Strange.  Now I cannot reproduce this one.
