### ISSUE TITLE
pSB1C3 has a feature going off the end of the sequence

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#1484]
The BioBrick suffix in pSB1C3 (https://synbiohub.org/public/igem/pSB1C3/1) has location 2051 - 2072. The sequence of pSB1C3, however, is only 2070 bp long.

**Comment by cjmyers** [comment]
Good catch.  This is clearly an error in the iGEM dataset.  Indeed, when we converted the iGEM data set to SBOL, we found 834 parts with errors like this one.  We decided at the time not to attempt to fix the iGEM data set but rather make it an accurate reflection of what is stored in the iGEM registry.

**Comment by cjmyers** [comment]
iGEM data error.  closing
