### ISSUE TITLE
Uploading fasta should (optionally?) make a ComponentDefinition

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#149]
e.g. if I upload a fasta file for a protein, I would like a protein CD to be created.

**Comment by udp** [comment]
Actually it might be useful to be able to create a CD from a Sequence in the web interface?

**Comment by cjmyers** [comment]
This should probably be a request on libSBOLj for a change in the FASTA conversion code.

**Comment by cjmyers** [comment]
In this case too, it might be easier to do through libSBOLj, but perhaps sboljs could work too.  Depends though on if we think this is generally useful or a SynBioHub only use case.

**Comment by cjmyers** [comment]
Also relates to #641 to use snapgene to autoannotate
