### ISSUE TITLE
Submission How to make the repository public?

### ISSUE THREAD

**Issue by anacarolb** [SynBioHub/synbiohub#1490]
Hello!
I am Ana, my group and I are currently trying to make our repository public in SynBioHub, but there is no "**make it public**" button, like it is described in 4.2 Managing at this page: https://wiki.synbiohub.org/userdocumentation/managingsubmitting/#43-updating or a way to contact a curator. 
So we would appreciate information or a guide of how to make it public, Thanks.

**Comment by cjmyers** [comment]
Making public is restricted to curators.  Would you mind providing a sharing link to your repo?  You can send it by email to chris.myers@colorado.edu.  Could you also tell me your username on SynBioHub?  Thanks.

**Comment by anacarolb** [comment]
Thanks Chris, I sent the informations by email.
