### ISSUE TITLE
partial sequence matches 

### ISSUE THREAD

**Issue by MattyCrowther** [SynBioHub/synbiohub#1507]
When using the sequence match feature, results only appear when there is a 100% sequence match.
So my input looks like this:
`https://synbiohub.org/search/sequence=<seq>&`
The results only return on 100% match.
For example
`https://synbiohub.org/search/globalsequence=atgcagtttaaggtttacacctataaaagagagagccgttatcgtctgtttgtggatgtacagagtgatattattgacacgcccgggcgacggatggtgatccccctggccagtgcacgtctgctgtcagataaagtctcccgtgaactttacccggtggtgcatatcggggatgaaagctggcgcatgatgaccaccgatatggccagtgtgccggtctccgttatcggggaagaagtggctgatctcagccaccgcgaaaatgacatcaaaaacgccattaacctgatgttctggggaatataa&id=1.0&`
Returns Matches but:
`https://synbiohub.org/search/globalsequence=ttgcagtttaaggtttacacctataaaagagagagccgttatcgtctgtttgtggatgtacagagtgatattattgacacgcccgggcgacggatggtgatccccctggccagtgcacgtctgctgtcagataaagtctcccgtgaactttacccggtggtgcatatcggggatgaaagctggcgcatgatgaccaccgatatggccagtgtgccggtctccgttatcggggaagaagtggctgatctcagccaccgcgaaaatgacatcaaaaacgccattaacctgatgttctggggaatataa&id=1.0&`
Will not.
It seems changing the ID value doesn't make a difference.
Is this an incorrect way of using the API, or is it a bug?

**Comment by cjmyers** [comment]
We are doing sequence search using Vsearch (https://vcru.wisc.edu/simonlab/bioinformatics/programs/vsearch/vsearch_manual.pdf).  We have also struggled to figure out how to configure it to give "close" but not "exact" results.  If you have any suggestions, please let us know.
