### ISSUE TITLE
Bad Gateway 502

### ISSUE THREAD

**Issue by mti1313** [SynBioHub/synbiohub#1534]
Every time I click on a component from the search results it times out with 502 error.

**Comment by cjmyers** [comment]
I've restarted the server.  Please try again.

**Comment by willfoerster** [comment]
I'm having the same issue, but it extends to more than just the components. I get the same error when I try to open my collections, create a new collection, and try to access other things like the iGEM Parts registry.

**Comment by cjmyers** [comment]
I've restarted the server.  Please try again.

**Comment by beastypants** [comment]
This issue seems to be occurring again. I cannot open my collections

**Comment by cjmyers** [comment]
I'm sorry for your trouble.  I've restarted the server.

**Comment by gareththomasnz** [comment]
Please restart the server - I have the 502 all day yesterday & again today when trying to view my private submissions - thanks

**Comment by cjmyers** [comment]
Please try now

**Comment by cjmyers** [comment]
They appear to be up now.  Can you retry?  Also, you might experiment with https://dev2.synbiohub.org.

**Comment by gareththomasnz** [comment]
It worked for me a day or two back

**Comment by ykho001** [comment]
The sites (SBH and devSBH) loaded yesterday, but still hit the bad gateway error when we looked into collections (tried SEGA and iGEM). Today, straight to 502 bad gateway for both. 
Managed to have a look at dev2SBH yesterday too - it looks very close to what you previewed to us previously! - but today, it also doesn't load (just blank screen).

**Comment by cjmyers** [comment]
Sorry about that.  There was a rogue process that I had to kill.  I think it is working now.

**Comment by SharonVarughese** [comment]
Hi. Can you restart the server please? Its appears I'm getting a 502 error.

**Comment by cjmyers** [comment]
It should be back up

**Comment by ykho001** [comment]
Hi, can you restart the server again please? 502 for the first two, timeout for dev2. 
Thank you!

**Comment by cjmyers** [comment]
Restarted

**Comment by ykho001** [comment]
Hi again, can you restart the server again please? Thanks again. 
(Do you know what's causing the 502 error, or a product of just ongoing development?)

**Comment by cjmyers** [comment]
Rebooted

Not sure why, looking into it

**Comment by ykho001** [comment]
Hi, can you reboot the server again, thanks!

**Comment by cjmyers** [comment]
It does not seem down to me.  I can access it.

**Comment by rake-83** [comment]
It's still showing 502 bad gateway these days. Cannot access to do the homework.
Help...

**Comment by rake-83** [comment]
Is there alternative way to access Synhiohub to finish my homework?  Tried https://dev2.synbiohub.org/ but also encountered same error when click on a search result.

**Comment by cjmyers** [comment]
Sorry about that.  I rebooted the server, and it is back up

**Comment by rake-83** [comment]
Tried again but still not working...may it was OK right after reboot but not is not. Even dev2.synbiohub.org cannot be opened.

**Comment by cjmyers** [comment]
Sorry.  Should be back up now
