### ISSUE TITLE
No ability to register

### ISSUE THREAD

**Issue by Duncan-Britt** [SynBioHub/synbiohub#1535]
There is a button that says Login or Register, but when clicked, it takes me to a log in page, and there's no option to register a new account. Btw I'm coming from clicking the report and issue link on [http://sevahub.es/](http://sevahub.es/)

**Comment by cjmyers** [comment]
sevahub does not allow public account creation.  If you try synbiohub.org, it will allow you to register.  Agree that there should be a message though that public account creation is not allowed.
