### ISSUE TITLE
SynBioHub is down

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#1537]
synbiohub.org is down and has been for the last day or so, according to the failed regressions tests I'm seeing.

**Comment by cjmyers** [comment]
Should be back up now.  It went down when I was traveling and did not have time till now to restart.

**Comment by cjmyers** [comment]
Shouldn't have changed.  I can check on this when I get a moment.

**Comment by cjmyers** [comment]
I'm really confused by this one.  When I click on the part that it says it cannot find.  It comes right up.  Can you provide any more context about the error?

**Comment by jakebeal** [comment]
It's happening because the SynBioHub search API is not returning an object with the expected identity. I haven't dug farther in to see if it's not getting the object or if it's coming back with a different identity.

**Comment by cjmyers** [comment]
Can you point me to the test code where the error is happening?  Nothing has changed with SBH1 in ages.

**Comment by jakebeal** [comment]
Here are the two places where failures are occurring:

- https://github.com/SynBioDex/pySBOL2/blob/master/test/test_searchquery.py#L51
- https://github.com/SynBioDex/pySBOL2/blob/master/test/test_searchquery.py#L106

**Comment by cjmyers** [comment]
I think I figured it out.  I turned off SBOLExplorer, since it was using a lot of resources and seems to be one of the reasons for SBH going down.  This would indeed change search results.

**Comment by jakebeal** [comment]
Is it OK for SBOLExplorer to be turned back on, or do you need to leave it off? 
My impression is that it does make a big difference for search results.

**Comment by cjmyers** [comment]
I would prefer to wait until we can figure out why it was using so much memory before turning it back on.  It seems it was what was causing SBH to go down a lot, since it used up resources.  The recent instances going down are unrelated to SBH.  They were due to some issue with Caddy.  I've updated the Caddyfile just now and hoping this will make things more stable.  It would be good if your tests did not depend on SBOLExplorer, since we cannot guarantee that it will always be on.  Make a search that is only going to return less than 50 results, and you should be good.

**Comment by jakebeal** [comment]
Well, things seem to have resolved on their own, which suggests something odd happened down in the external dependencies...

**Comment by cjmyers** [comment]
Hmm, that does not make sense.  We still have SBOLExplorer off.

**Comment by jakebeal** [comment]
My guess is that it had nothing to do with SynBioHub, but something in the dependencies of pySBOL2. Something like this happened with the GitHub mac build environment for SBOL-utilities a little while back also

**Comment by cjmyers** [comment]
Interesting.  Glad you don't have an SBOLExplorer dependency.  Hope to get it running again at some point.
