### ISSUE TITLE
synbio hub 502 error when collections or parts are opened

### ISSUE THREAD

**Issue by pvskpraveen** [SynBioHub/synbiohub#1540]
I am noticing that when I try to open any of my submissions or if I open any parts like https://synbiohub.org/public/igem/BBa_K1428000/1, I get a 502 Gateway error. Please check

**Comment by cjmyers** [comment]
Should be working now.  Please check

**Comment by pvskpraveen** [comment]
Thank you. It worked for one day and now the entire website is not available

**Comment by cjmyers** [comment]
Yeah, there seems to be some problem with our port forwarding software.  SBH is up but not accessible.  I've rebooted the port forwarding software (caddy), and it is accessible again.  I will try to debug why that software if failing.  Sorry for the inconvenience.

**Comment by CoolEJ** [comment]
Hello, this has been happening frequently.

**Comment by cjmyers** [comment]
Sorry about that.  When it happens, let us know, so I can check the system.  I've restarted the system, and it seems to be working for me now.

**Comment by Uselessandusefull** [comment]
From the past 3 days I am unable open any of my submissions, because I am getting a blank page saying "502 Bad Gateway" . Please do the needful🙏

**Comment by cjmyers** [comment]
Could you try now
