### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by CoolEJ** [SynBioHub/synbiohub#1550]
I cannot login to my account.

I tried two of my email addresses and keep getting this when trying to reset.

"The provided authorization grant is invalid, expired, or revoked"

"Cannot set property 'resetPasswordLink' of null"

How to go about this?

Thanks

**Comment by CoolEJ** [comment]
I recreated my account and found that my past collections are gone.

**Comment by cjmyers** [comment]
Could you tell me your username on SynBioHub?  So, I can double check your account.  To be clear, you have forgotten your password, is that correct?
