### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by CoolEJ** [SynBioHub/synbiohub#1551]
When I click a link, the  site tries to load eternally.

**Comment by CoolEJ** [comment]
Bad gateway

**Comment by cjmyers** [comment]
Restarted the server

**Comment by EllenHA16** [comment]
I am having the same issue, it won't load no matter what browser I use

**Comment by cjmyers** [comment]
Please try now

**Comment by EllenHA16** [comment]
Now it works, thank you!

**Comment by Kla-Ops** [comment]
I am currently having this same issue. I have tried waiting a day, using a different device, a different browser, and trying a different wifi network, but nothing seems to be working.

**Comment by cjmyers** [comment]
I've rebooted the system, and I believe it is working now.  Please try again.
