### ISSUE TITLE
Source repo cannot be cloned

### ISSUE THREAD

**Issue by MukherjeeSayak** [SynBioHub/synbiohub#1552]
The source code cannot be cloned from the master branch. Please see the err msg below. Please let me know how this can be fixed

'error: invalid path 'tests/previousresults/get_file_public-:collectionId-:displayId-:version-fasta_.xml'
fatal: unable to checkout working tree'

Thanks
Sayak

**Comment by cjmyers** [comment]
Strange, works me:  did you do this?

git clone https://github.com/SynBioHub/synbiohub.git

**Comment by MukherjeeSayak** [comment]
On Linux, the clone operation seems to work.
One of my colleagues Found this StackOverflow: -  https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows
The problem we were seeing is a Window problem because the filename contains illegal characters: 
Basically, after checking out the repo he did **git config --global core.protectNTFS false** before the clone operation.

**Comment by cjmyers** [comment]
Duplicate closing
