### ISSUE TITLE
BBa_R0040 Link to part does not load

### ISSUE THREAD

**Issue by MarshallLucky** [SynBioHub/synbiohub#1555]
https://synbiohub.org/public/igem/BBa_R0040/1

The above link to TetR repressible promoter, BBa_R0040 does not load.  I dont' think the issue is specific to this part, rather to all/many parts.  I am logged in fine, i created a collection and i see it in profile.  i'm trying to find parts and add them, but the part pages don't load.

**Comment by MarshallLucky** [comment]
By the way, after death spin, it says "502 Bad Gateway"

**Comment by cjmyers** [comment]
Please try now.  The server needed rebooting.

**Comment by MarshallLucky** [comment]
Thank you, It's better and it allows me to add parts now, I think it worked.  However, when i tried to go back and look at the list, which i had just done 2 minutes before, it hangs at "Processing" popup and then gives this error:

DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Nevertheless, i think the parts are there, but that it sometimes chokes, not always, when loading.  I'd bet in a couple hours it might load fine (I saw this behavior last night, but this morning it had populated).  Still flaky though, hence this fyi.

**Comment by cjmyers** [comment]
If this happens again, select Show All Objects and press Filter

**Comment by MarshallLucky** [comment]
Will do, all appears to be working now, thank you.
