### ISSUE TITLE
Entries not loading

### ISSUE THREAD

**Issue by ebsi99** [SynBioHub/synbiohub#1589]
Hi
I'm trying to add parts to my collection but neither parts nor collections are opening. It stays stuck in the loading step.

![image](https://github.com/user-attachments/assets/345bf558-fc1d-4a88-a413-305b4812e76c)

![image](https://github.com/user-attachments/assets/adbd276d-eabe-4244-bbd8-dffb5ce39389)

**Comment by cjmyers** [comment]
Rebooted.  Please try now
