### ISSUE TITLE
Create and use mutableProvenance predicate

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#174]
Would replace dc source as an editable field.  I suggest calling it mutableProvenance rather than mutableSource to make the field more generally useful.  "source" (i.e. where you got it) isn't something people should be changing after creating a part, but adding attribution or information about how a part was constructed would be useful, and I think this fits better under the umbrella of "provenance" than "source".

**Comment by cjmyers** [comment]
Done
