### ISSUE TITLE
HTTPS for synbiohub.org

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#178]

**Comment by cjmyers** [comment]
Would this mean we need to change URIs to https?

**Comment by cjmyers** [comment]
Yes, I believe we should change the URIs.  So, we should decide this one soon.  It is working for LCP SynBioHub, so it should work here too, if we decide to go forward.

**Comment by 16zzundel5** [comment]
https://dev.synbiohub.org is live and ready to poke around on.

**Comment by NeilWipat** [comment]
Just looking at it but its gone down

Sent from my iPhone

On 6 Jun 2017, at 12:52, Zach Zundel <notifications@github.com<mailto:notifications@github.com>> wrote:


https://dev.synbiohub.org is live and ready to poke around on.

**Comment by cjmyers** [comment]
We are in the midst of getting dev updated.

Chris

**Comment by 16zzundel5** [comment]
Should be back up

**Comment by NeilWipat** [comment]
Why did it go down?

Sent from my iPhone

On 6 Jun 2017, at 16:52, Zach Zundel <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be back up

**Comment by 16zzundel5** [comment]
I killed the process because I was moving it to a deploy user so it's not running under one of our specific accounts.

**Comment by cjmyers** [comment]
We moved the instances to a new user “deploy” instead of having it run as “james”.  

Chris

**Comment by NeilWipat** [comment]
The datasets have changed? Bacillus and E coli not there anymore?

Sent from my iPhone

On 6 Jun 2017, at 16:55, Zach Zundel <notifications@github.com<mailto:notifications@github.com>> wrote:


I killed the process because I was moving it to a deploy user so it's not running under one of our specific accounts.

**Comment by cjmyers** [comment]
Dev does not have these yet.  They need to be re-uploaded.

**Comment by cjmyers** [comment]
Goksel has said he will re-upload the Bacillus dataset once we are ready.

I’m not so sure we want to upload the E. Coli one as it has not been very well curated yet.  

Are release is releasing both the repository and the data sets, so we want to be sure they are final.

Do you want me to wait until Goksel has reload the Bacillus (or try to upload ourself) before I make the demo video?

**Comment by NeilWipat** [comment]
Hi Chris,

Yes please i would like the bacillus parts there.

Thanks

Sent from my iPhone

On 6 Jun 2017, at 17:09, cjmyers <notifications@github.com<mailto:notifications@github.com>> wrote:

Goksel has said he will re-upload the Bacillus dataset once we are ready.

I’m not so sure we want to upload the E. Coli one as it has not been very well curated yet.

Are release is releasing both the repository and the data sets, so we want to be sure they are final.

Do you want me to wait until Goksel has reload the Bacillus (or try to upload ourself) before I make the demo video?

**Comment by cjmyers** [comment]
Ok, I will try to copy them over to dev then.

**Comment by cjmyers** [comment]
Ok, that did not work. Downloading bacilus collection timed out.

The only way I can do this without Goksel’s help is to update synbiohub.org <http://synbiohub.org/>, so it gets the “no timeout” fix.	

Is it alright to pull in the latest code into synbiohub.org <http://synbiohub.org/>?  I will not be touching the data there, so it will still be the same as before.

Chris

**Comment by 16zzundel5** [comment]
Since we know that HTTPS data works, we could point dev back to the org graphs until org is on HTTPS (which needs to happen by tomorrow afternoon so I have time to build and document the releases.)

**Comment by cjmyers** [comment]
I will do this temporarily, if need be.  But I prefer not to do this.  The reason is making the video will be a test.  

The last time I ran a demo with one set of data then switch, I ran into issues.  It is best if the demo is created on the live instance to provide at least a minimal test of the live instance.

**Comment by cjmyers** [comment]
This has been moved to https.
