### ISSUE TITLE
Delete tmp files

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#222]
The tmp files generated should be deleted periodically.

**Comment by udp** [comment]
They should be deleted after they've been used, not even periodically.

**Comment by cjmyers** [comment]
synbiohub@kilchoman:/tmp$ ls -lt |wc
2172059 19548524 170195847

**Comment by cjmyers** [comment]
synbiohub@kilchoman:/tmp$ ls -lS | grep "synbiohub       674 " |wc
2165710 19491390 169696521

**Comment by cjmyers** [comment]
My guess is it is in sbol.js, here, where a tempFile is returned but is it removed?

    fetchSBOLSource(uri, graphUri).then((tempFilename) => {

        res.status(200).type('application/rdf+xml')
           //.set({ 'Content-Disposition': 'attachment; filename=' + collection.name + '.xml' })

        const readStream = fs.createReadStream(tempFilename)
            
        readStream.pipe(res)


    }).catch((err) => {
	if (req.url.endsWith('/sbol')) {
	    return res.status(404).send(uri + ' not found')
	} else { 
        var locals = {
            config: config.get(),
            section: 'errors',
            user: req.user,
            errors: [ err.stack ]
        }
        res.send(pug.renderFile('templates/views/errors/errors.jade', locals))
	}
    })

**Comment by cjmyers** [comment]
Several leaks of temp files have been fixed.  Hopefully, we got them all though more testing may be needed.

**Comment by 16zzundel5** [comment]
Looking around, it looks like all of these have been cleared out, so I'm going to close this. We can open another issue if we spot a specific one.
