### ISSUE TITLE
Hide forgotten password link if email isn't set up

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#236]

**Comment by 16zzundel5** [comment]
Is this if the user hasn't set their email? Is that an option?

**Comment by cjmyers** [comment]
No, the issue is that for forgotten password to work, the instance must have setup an SMTP server to use.  We don’t have this setup on our instances here, for example, so the link will not work.

**Comment by 16zzundel5** [comment]
Will the SMTP server be set up in config.json? How does this work?
