### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN public-registry.jbei.org:443

### ISSUE THREAD

**Issue by rgiessmann** [SynBioHub/synbiohub#238]
Dear team,

I set up SynBioHub on a computer of ours by running the provided docker image. I followed the installation guide http://wiki.synbiohub.org/wiki/Installation .

The system starts up all well. However, when I try to browse a public repository (start page -> "Browse Public Designs") and want to access either JBEI or ACS, the following error message is returned:

`Error: getaddrinfo EAI_AGAIN public-registry.jbei.org:443 at Object.exports._errnoException (util.js:1018:11) at errnoException (dns.js:33:15) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)`

Do you have any idea what's going on?

Thanks in advance,
   Robert

**Comment by cjmyers** [comment]
Hi Robert,

These repositories require an access token, and unfortunately, the one in the docker image appears to have expired.  We are trying to figure out another means to access these repositories that will not expire.  Hopefully, we will have a solution soon.

BTW: we would be happy with any feedback you have on the installation process.

Cheers,

Chris

**Comment by rgiessmann** [comment]
Hi Chris,

alright, thanks for the answer! 


Regarding the installation process: I was deeply impressed. That was the fasted installation I have ever seen (I haven't used docker before), and --at least on a Linux machine-- this was just so incredibly easy... Thumbs up!

(One note, though: As I wasn't familiar with docker, I searched your website for a couple of minutes to find the "download" link, before just trying to execute the line (`docker run ...`) given in the wiki -- maybe you could add a short sentence in beginning of the section "Starting a SynBioHub container" for those unfamiliar with docker.)

Best,
   Robert

**Comment by cjmyers** [comment]
Thanks for the feedback.  We will look forward to more as you get started working with it.

Chris
