### ISSUE TITLE
Configuration editable in admin dashboard

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#245]

**Comment by cjmyers** [comment]
Disallow setup page continue if not first time.
Remove clear SQL lite database on setup and add new admin user.
Do not require an image.
If no image, use the synbiohub title instead
Hide any admin features that do not work.
Make config editable from admin as well as user database.
Use synbiohub instance name to form graph names.

**Comment by cjmyers** [comment]
After setup, should be logged in.

**Comment by 16zzundel5** [comment]
Hi, what of this still needs to get done?

**Comment by cjmyers** [comment]
I think this is basically done, though we may add to it as we go forward.

The key thing is getting the entire config editable in admin page.

Chris

**Comment by 16zzundel5** [comment]
Specified in #324, #325, #326
