### ISSUE TITLE
Operator vs. User defined glyph

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#246]
Nitpicky question:
The araR_araR shown in this image represents an operator. Based on the [SBOL visual specification 1.0.0](http://sbolstandard.org/wp-content/uploads/2015/02/BBFRFC93.pdf) , the operator symbol is represented as a **square shape** and not a **rectangle shape**. A rectangle shape represents a user defined symbol and the square shape represents an operator. 

This issue is redundant across the Bacillus subtilis collection. 

<img width="416" alt="glyph" src="https://cloud.githubusercontent.com/assets/7537729/24920136/60a23932-1ea3-11e7-8687-1fa92967f2cd.png">

**Comment by 16zzundel5** [comment]
This is actually a VisBOL issue, I'm going to move it there.

**Comment by 16zzundel5** [comment]
Moved to VisBOL issue [24](https://github.com/VisBOL/visbol-js/issues/24).
