### ISSUE TITLE
Rename graph if user id changed OR do not allow user id to be changed

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#252]
If you change the user id but do not update the graphUri, then there are a lot of problems.  So, either need to not allow user id changes OR change the graphUri when the user id changes.  If you change the graphUri, then likely need to actually rename the graph so no data is lost.

**Comment by udp** [comment]
I think we should not allow the user ID to be changed.

**Comment by cjmyers** [comment]
Agreed.  If there is a means to add a user, then this would not be needed.  I did this as a poor man’s way to change the user from a test one to myself.  Should still display it but leave it as read-only.

**Comment by 16zzundel5** [comment]
@cjmyers @udp it looks like user id is read-only in /admin/users, so can this get closed?

**Comment by cjmyers** [comment]
Agreed.  Is there an issue to add a new user already?  If not, please create one.

**Comment by cjmyers** [comment]
Hmm, I can edit the user id.

**Comment by 16zzundel5** [comment]
Where can you edit it? Can you include a screenshot?

**Comment by 16zzundel5** [comment]
I can't edit the user. Are you running the latest version of SynBioHub?
<img width="439" alt="screen shot 2017-05-17 at 1 29 47 pm" src="https://cloud.githubusercontent.com/assets/3093325/26153800/f25ec8e0-3b04-11e7-9242-717dfca7becc.png">

**Comment by cjmyers** [comment]
Yes, it is the latest version.  When I type in the username box, the Save button turns green, so I assume it is letting me edit.

On a related note, the Save button does not turn green if you click “Admin” button

**Comment by 16zzundel5** [comment]
ah! I thought you meant then numerical ID.

**Comment by 16zzundel5** [comment]
Fixed!
