### ISSUE TITLE
Backup not working on RedHat

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#256]
Error: ENOENT: no such file or directory, scandir '/var/lib/virtuoso-opensource-7/db' at Error (native)

**Comment by udp** [comment]
Any idea where the virtuoso DB is on redhat?

**Comment by cjmyers** [comment]
It is here on fedora:

/var/lib/virtuoso/db

**Comment by udp** [comment]
You can just add:

    "triplestore": {
        "virtuosoDB": "/var/lib/virtuoso/db"
    } 

to config.local.json

**Comment by cjmyers** [comment]
Also virtuosoINI change?  It is also in a different place.

**Comment by udp** [comment]
Literally just edited my comment with that!

**Comment by 16zzundel5** [comment]
I implemented the fix you guys described. I'm going to add the option to set this in the initial config!

**Comment by 16zzundel5** [comment]
PR #333
