### ISSUE TITLE
Wishlist from BU Wet-lab

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#260]
- Features: 
-- identifier, creator, created, modified, description, type, 
-- antibiotic resistant gene, 
-- plasmid map, 
-- sequencing results attached, 
-- status, localization, 
-- good search mechanism, 
-- space for experimental data, 
-- can be exported as genbank and sbol files, 
-- space to insert files/attachments/ links/texts, 
-- annotation and verification, 
-- real time DNA editing.

- It should generate barcodes

- It should communicate with our design tool (Benchling)

- Easy to exchange data with "customers"

**Comment by 16zzundel5** [comment]
I've moved this to the [wiki](http://wiki.synbiohub.org/wiki/Boston_University_desired_features)
