### ISSUE TITLE
Allow parts to be added without name/description

### ISSUE THREAD

**Issue by lemccarthy** [SynBioHub/synbiohub#263]
In my cases when uploading parts I end up having to type nonsense into the name/description field as I just want to upload the part. Make it so that the fields are optional so that I don't have to keep doing that.

**Comment by cjmyers** [comment]
Understand why this is a pain during debugging, but allowing records without names and descriptions in production seems like a mistake.

BTW: ICE also has several required fields on submit which must be filled in and get filled with junk during testing.  

One option in the future to consider perhaps is to have a special developer user that is like admin but has a few things done for them like have defaults filled in to avoid the extra typing during debug.

**Comment by cjmyers** [comment]
Closing.
