### ISSUE TITLE
Add New User Types

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#264]
Guest (no login) - view public
    General user - submit, mange own submissions
    Member - view remotes and possible private repos(?)
    Curator - view all, manage all, make public
    Admin - Manage users, configuration, etc.

**Comment by 16zzundel5** [comment]
It's common in other systems to have user types, and then the ability for admin users to granularly control specific users' permissions. For example, perhaps there is a specific user with the **curator** type who should also be able to manage the theming of the site, but not users. Do you think we need this level of control, or should it be strictly these profiles?

**Comment by cjmyers** [comment]
Perhaps at some point but this sounds pretty detailed for our needs.  I think the key cross point will be groups.  Namely, we will have general users, members of groups, curators of groups, and admin users.

The members can do things like see private data within their group, and curators will be able to transfer private data into public data within their group.  We should put this as a near term action item to discuss.

**Comment by cjmyers** [comment]
This is now committed to branch feature/user-types.  Will pull to master once there is a migration path for the SQL database to add the new isCurator and isMember fields.

**Comment by 16zzundel5** [comment]
And it's merged into master!
