### ISSUE TITLE
Change submission/make public pages

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#265]
Ask if create new collection or add to existing
Change options based on this choice

Create new collection should basically be same choices as now, except you should not be able to merge to new one.

Add to existing should allow you to choose a root collection from a list and not ask for id/version/name/description, etc.

**Comment by cjmyers** [comment]
This is implemented but it needs more testing.

Also, the radio button could be formatted better, and it should disable/enable the relevant options.

**Comment by 16zzundel5** [comment]
Finished, tested, and updated the layout!
