### ISSUE TITLE
Docker image should restart virtuoso if it crashes

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#279]
https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-1-practical-examples

**Comment by udp** [comment]
Would you like to take a look at this Zach?  The repository for the Docker image is at http://github.com/synbiohub/synbiohub-docker

**Comment by 16zzundel5** [comment]
Yeah, I can take a look -- I haven't worked a ton with Docker so it may not be a quick fix.

**Comment by 16zzundel5** [comment]
Moving to synbiohub/synbiohub-docker issue 2.
