### ISSUE TITLE
Problems with VisBol glyph mappings

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#295]
There are problems with the glyph mappings in VisBol.

For example, sequence feature now rendered with Scar

http://synbiohub.org/public/igem/BBa_M1994/1

Tag glyph disappeared:

http://synbiohub.org/public/igem/BBa_K823038/1

OriT glyph disappeared:

http://synbiohub.org/public/igem/BBa_K125320/1

etc.

Note, you can use advanced search to find examples of each role to check rendering.

**Comment by 16zzundel5** [comment]
Moving this to VisBOL.
