### ISSUE TITLE
Support for COMBINE Archives

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#297]
Should unpack and submit the SBOL file
Any models or other attachments should be logged in as attachments
Links in the SBOL file to the models/attachments should be updated to the URIs within SynBioHub

**Comment by 16zzundel5** [comment]
Note -- the specification for COMBINE archives is found [here](http://co.mbine.org/specifications/omex.version-1.pdf)

**Comment by zachzundel** [comment]
Marking as priority as since it was discussed at IWBDA

**Comment by zachzundel** [comment]
Done!
