### ISSUE TITLE
Save not enabled with Admin checkbox changes

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#298]
The Save button does not become enabled when the admin save button changes state.

**Comment by 16zzundel5** [comment]
Does it not let you click? Or does it not turn green?

**Comment by 16zzundel5** [comment]
Which page is this on? The theming page?

**Comment by cjmyers** [comment]
User page.  Does not turn green.  Please hold off on this one as I’m trying to add user types, so we will likely have conflicts if you make changes here.

**Comment by 16zzundel5** [comment]
PR #315
