### ISSUE TITLE
Sort/search does not work for remote collections

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#329]
Either we should hide these when viewing a remote OR we should figure out how to enable them.   My guess is hide though, since to enable them we likely need to have functionality in ICE/Benchling that may not be present.

**Comment by 16zzundel5** [comment]
You're right -- this would be difficult to implement for remotes. We should look at it again after the 1.0 release

**Comment by 16zzundel5** [comment]
PR #330
