### ISSUE TITLE
Temp files are not being deleted

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#334]
Temp files are building up, so there must be some places where we are not deleting them.  Should track these down as this can become a problem.

**Comment by cjmyers** [comment]
I think I found one temp file leak when generating GenBank files, but there are likely others.

**Comment by cjmyers** [comment]
Searching for files with this require line should find them:

var fs = require('mz/fs');

**Comment by cjmyers** [comment]
[myers@jiaqi synbiohub]$ grep mz/fs */*/*.js
lib/actions/cloneSubmission.js:var fs = require('mz/fs');
lib/actions/copyFromRemote.js:var fs = require('mz/fs');
lib/actions/createSnapshot.js:const fs = require('mz/fs')
lib/actions/makePublic.js:var fs = require('mz/fs');
lib/api/genBank.js:var fs = require('mz/fs');
lib/api/persistentIdentity.js:const fs = require('mz/fs')
lib/api/sbol.js:const fs = require('mz/fs')
lib/conversion/n3-to-sbol.js:const fs = require('mz/fs')
lib/conversion/prepare-snapshot.js:const fs = require('mz/fs')
lib/sparql/sparql.js:const fs = require('mz/fs')
lib/views/submit.js:var fs = require('mz/fs');
[myers@jiaqi synbiohub]$ grep mz/fs */*/*/*.js
lib/fetch/local/fetch-sbol-object-recursive.js:const fs = require('mz/fs')
lib/fetch/local/fetch-sbol-source.js:const fs = require('mz/fs')
lib/views/admin/backup.js:const fs = require('mz/fs')
[myers@jiaqi synbiohub]$ grep mz/fs */*/*/*/*.js
lib/fetch/remote/benchling/fetch-sbol-source.js:const fs = require('mz/fs')
lib/fetch/remote/ice/fetch-sbol-source.js:const fs = require('mz/fs')
lib/fetch/remote/synbiohub/fetch-sbol-source.js:const fs = require('mz/fs')

**Comment by cjmyers** [comment]
sparql.uploadFile seems to do some unlinking, so methods above that upload likely do remove the file.

Am concerned though if on any error if temp files get removed.

**Comment by 16zzundel5** [comment]
Major culprit appears to have been addressed, so removing from 1.0

**Comment by cjmyers** [comment]
Still a problem moving back to 1.0.

**Comment by cjmyers** [comment]
Was not removing temp file when GenBank conversion failed.  This is fixed now but should keep an eye on this.

**Comment by zachzundel** [comment]
I don't see any temp files on the current SBH deployment, so I think this is either fixed or near-fixed. I'm going to close.

**Comment by cjmyers** [comment]
They are still created, see synbiohub.utah.edu instance to see some.  I think the ones created on reads of synbiohub are fixed, but there are still ones created on actions like submit, makePublic, etc.  I'm reopening this but moving to 1.1.0.

**Comment by zachzundel** [comment]
I found a significant leak where temporary directories were being created and fixed that. The remaining files appear to have come from @cjmyers tool information upload. Could you describe the steps you followed during that so I can figure out where the issue is?

**Comment by cjmyers** [comment]
These are pretty tricky.  It is a mixture of Java, Javascript, and scripts.  Best to discuss in person.
