### ISSUE TITLE
Setup should ask for instanceUrl and databasePrefix as these do not need to match

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#335]
The instanceUrl is the actual URL of the synbiohub instance.  The databasePrefix is the URI prefix that this database uses.  The later one is also the graph prefix.

**Comment by cjmyers** [comment]
I think I remember now that James and I decided to force config to be edited manually for this one, since this should only be done on test servers.  Would be good to be able to change on admin but not needed right away.

**Comment by zachzundel** [comment]
PR #387
