### ISSUE TITLE
URIs of iGEM parts should not contain 'BBa_'

### ISSUE THREAD

**Issue by bbartley** [SynBioHub/synbiohub#344]
If I want to look up a biobrick on SynBioHub, it's difficult for me to remember how to construct the URL.  I always forget the 'BBa_' prefix.  As far as I know, every biobrick has this prefix, so practically speaking it doesn't serve much purpose. I always think of a biobrick in terms of it's unique ID, eg. T9002.  The URIs would be much prettier if they were of the form: https://synbiohub.org/public/igem/T9002/1

**Comment by cjmyers** [comment]
HI Bryan,

Thanks for the suggestion, but I’m afraid that the ship has sailed on that one.  We don’t have the cycles to change everything before the release we are scrambling towards with SB7.0.  In any case, you should not be searching using URI.  You should be using our search mechanisms :-)

Chris

**Comment by bbartley** [comment]
I'm not suggesting this change needs to be done anytime soon, but it is a nice touch that would optimize usability for those approaching SynBioHub from the browser side (which inevitably many users will).  The webpage URLs should be easy to construct from memory.  I'm guessing there's probably a way to implement simple URLs without touching the SBOL already in SynBioHub.

**Comment by cjmyers** [comment]
Perhaps some sort of redirection.  However, remember this does not scale.  SynBioHub is not the iGEM registry.  We don’t know the meaning of the displayIds that are given to us.  We are just serving them back up as given, and this is the form they take in iGEM.  We could perhaps do something special for iGEM, but many people are following this convention, so the displayId alone tells you where it came from.  I’ve now seen BO_#### for Bacillus, LCP_#### for Living Computing Project, CIDAR_#### for Cidar lab.  

So, while I sort of see your point, the BBa I would argue is an important part of the id.

**Comment by bbartley** [comment]
Point conceded.
