### ISSUE TITLE
Change wiki.synbiohub.org to https

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#345]

**Comment by cjmyers** [comment]
On second thought this is too big a change.  Instead let's make https://wiki.synbiohub.org and http://wiki.synbiohub.org dereference to the same place.

**Comment by zachzundel** [comment]
If the http:// address redirects to https://, will that work?

**Comment by cjmyers** [comment]
I think so.  I’m actually though having second thoughts.  Do we care if https://wiki works?  Or should we make sure annotations all point to http://wiki.  Might be confusing to have both. I’m moving to 1.1.0, so we can reconsider.

**Comment by cjmyers** [comment]
Closing.
