### ISSUE TITLE
Web page load is way too slow

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#347]
I checked the pages using this tool:

https://tools.pingdom.com/#!/cW4Pjk/https://synbiohub.org

It indicates we have a problem with “bundle.js” being very slow to load.  It suggests enabling browser caching.  

https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

I’m out of my element here.  And I’m not sure why this all of a sudden became such a problem. 

James, Zach: can you try to sort this ASAP?

**Comment by 16zzundel5** [comment]
Added precompiling, caching, and minifying to bundle.js middleware
