### ISSUE TITLE
Bugged error message when submitting with invalid ID

### ISSUE THREAD

**Issue by mholowko** [SynBioHub/synbiohub#354]
When I try to submit a new plasmid with invalid ID (for example containing bracket) instead of error message telling me to adhere to ID naming rules I get something like this:
https://pastebin.com/8svGjd1q

**Comment by zachzundel** [comment]
I think this is likely due to the fact that the id is incorporated into the URI, and libSBOLj encounters the URI first. @cjmyers , thoughts?

**Comment by cjmyers** [comment]
That is correct.  The URI must always be created first, and the id is part of the URI, and it is illegal to have brackets in a URI.

**Comment by zachzundel** [comment]
What if we built the ID from the Display ID? The user will be able to edit it, of course, but if we auto-filled with some valid value generated from the display ID, that would increase usability for those who are not familiar with the data model.

**Comment by cjmyers** [comment]
If the id is the submission id from the submit form, then we cannot use the displayID, since when you upload, you may be uploading a large number of objects each with their own displayId.  I think a better solution is a help message telling what is expected plus do error checking on the validating of the id before trying to create the collection.  A simple parse check on the field with a simpler error message would suffice.

**Comment by zachzundel** [comment]
Definitely we should run form validation before passing something to the SBOL validator, but talking with Neil I think we may be coupling the SynBioHub interface here a little bit too closely to the data model. I think that this is one of the places where we could at least pre-fill some value to make it more user-friendly.

**Comment by cjmyers** [comment]
The problem is there is no obvious thing to prefill it with.  You need an id for a group of records. Unless we do something like submission1, 2, 3, etc.

Chris

**Comment by NeilWipat** [comment]
Most database systems don’t require a user to add the ID for a record. It’s also still confusing for a biologist user. There must be a way of auto-generating a suitable ID.

Neil

**Comment by NeilWipat** [comment]
It makes sense to let the user make and name collections. Can always use assigned IDs as in Genbank etc. for individual designs?

**Comment by cjmyers** [comment]
How about as a compromise, we make it an optional field, and if not provided then we generate one?  I would still like to give the more expert user the ability to give meaningful ids to their submissions.

**Comment by zachzundel** [comment]
I agree that we should retain the ability for someone to modify the ID. I just think that if we can make a reasonably good guess as to what it should be, then we should try to do so. 

Thanks,
Zach

**Comment by cjmyers** [comment]
There is no way to guess, but we can make one up (i.e., SBH000001, or similar).

**Comment by cjmyers** [comment]
There is a new issue #357 to deal with the automatically generated id for new private submissions.  The remaining part of this issue is to add checking of the id validity before accepting the submission for the case where an id is provided.

**Comment by cjmyers** [comment]
Added error checking on ids and versions and give a better error message.
