### ISSUE TITLE
Error message when submitting ICE generated SBOL file

### ISSUE THREAD

**Issue by mholowko** [SynBioHub/synbiohub#355]
When I try to submit a new entry using an SBOL file (ver. 2.0) generated by ICE (ver 5.2.2) I receive the following error: https://pastebin.com/pmuN15DJ
The original file is attached. [ICE SBOL file.zip](https://github.com/SynBioHub/synbiohub/files/1096882/ICE.SBOL.file.zip)
I am not sure if it is a problem with the hub or the ICE.

**Comment by cjmyers** [comment]
It is a bit of a combination of both.  The URIs produced by ICE are not correct.  They do not have a “scheme”.  Namely, they should start with http:// or https:// etc.  However, the error message is not a good one, so we should fix that.

You should be able to solve this issue by changing the URI prefix configuration in ICE.

To do this, login into ICE as an administrator, and go to the administrator settings.  There you should find URI prefix, and change this from:

ice.bic.nus.edu.sg:8443 

to

https://ice.bic.nus.edu.sg

Another solution is that we can attach your ICE instance to a SynBioHub instance which will enable push-button transfer between the two.  Let me know if you would like me to help you do this.

**Comment by cjmyers** [comment]
The bad error message is actually a libSBOLj bug.  Moving this issue to the tracker for libSBOLj.
