### ISSUE TITLE
advanced search uses field names, not plain english

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#360]
The advanced search uses names like CreatedAfter and igem#partType.
The fields should instead be translated into plain English and organized more nicely.

**Comment by cjmyers** [comment]
Fixed.  See here:
https://dev.synbiohub.org/advancedSearch

However, this is part of a largely issue logged here #303, in which there is a plan to make the search less iGEM specific.  It has iGEM search fields for demo purposes, but long-term it should allow any annotations to be searched over.  This is a bit of a tricky UI issue as there can literally be anything in the annotations.

Jake: let me know if you are okay with me closing this one.

**Comment by jakebeal** [comment]
This addresses the immediate issue, thank you.
