### ISSUE TITLE
Sequences should be merged with the page for their referencing CD

### ISSUE THREAD

**Issue by jamesamcl** [SynBioHub/synbiohub#361]

**Comment by cjmyers** [comment]
I disagree with this one.  The page for parts is already so full.  Adding the sequence will overload this page even further.  I think the sequence should only be visible on demand as it is now.  We could perhaps make it more obvious how to see the sequence OR add a feature to VisBol that enables the sequence be viewed in place of the VisBol diagram, much like in the iGEM registry.

**Comment by zachzundel** [comment]
Biologists asked for this in the focus group, but I agree that the CD page is already fairly cluttered. Maybe we can make it an expandable section on the CD page.

**Comment by zachzundel** [comment]
Moving to 1.0.2, but just so that we have some kind of settle-by date for this question

**Comment by cjmyers** [comment]
The ideal in my mind would be to make this part of the Visbol diagram, namely, you could swap tabs between visual and sequence view like on the iGEM website.
