### ISSUE TITLE
A collection page should indicate that the user is looking at a collection

### ISSUE THREAD

**Issue by NeilWipat** [SynBioHub/synbiohub#362]
e.g. Collection - collection name

**Comment by cjmyers** [comment]
The name of the Collection is provided by the creator of the Collection.  See for example:

https://dev.synbiohub.org/public/bsu/bsu_collection/1

This one is named: "Bacillus subtilis Collection", so it would not make sense to add the word Collection at the end.  The question then becomes whether or not we want to change the name of other Collections on SynBioHub.org.  For example, should "IGEM Parts Registry" be renamed to "IGEM Parts Registry Collection".  I think the word Collection in redundant, but I don't feel to strongly about it, if others think we should add this word to the end of the names of this and perhaps other collections.

**Comment by cjmyers** [comment]
Added the type to the header on all pages.  This is especially important for genericTopLevel pages, which otherwise it is not obvious.  There is also an information icon link to find more information about the type.  For the SBOL types, this goes to the wiki.
