### ISSUE TITLE
Virtuoso crashes bring SynBioHub down

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#364]
Trying to search, I get:

> Error: connect ECONNREFUSED 127.0.0.1:8890

**Comment by cjmyers** [comment]
Restarted virtuoso

**Comment by zachzundel** [comment]
As a stopgap, I've added a crontab that restarts Virtuoso every morning at 1am

**Comment by zachzundel** [comment]
I've also set up an uptime monitor. Ideally, Virtuoso will be managed entirely by the SynBioHub process, but this will probably take a bit longer, so I'm going to move that to 1.0.0.

**Comment by cjmyers** [comment]
A simpler solution would be to have a cron job that runs every few minutes and pings a simple endpoint like:

<URL>/rootCollections

and only restarts virtuoso when this returns 500.

**Comment by zachzundel** [comment]
duplicate of #259, closing
