### ISSUE TITLE
Download COMBINE Archive button

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#372]
This would download the SBOL file along with all attachments, models, data, etc. into a single COMBINE archive file.

**Comment by zachzundel** [comment]
Marking as priority since we said it was supported at IWBDA

**Comment by cjmyers** [comment]
With maven, you should be able to fine tune the dependencies tree.

See https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

In the previous case with libsbml, you could have declare libsbml as an optional dependency so that is it not included in the other project if they don't need it.

In the case of CombineExt, if it does work with the newer version of the libraries, you can use dependency exclusion to remove the dependencies you have already with newer version.

**Comment by zachzundel** [comment]
Ready for review #582

**Comment by cjmyers** [comment]
It works but the manifest has unknownAttachment for all files.  I guess this is probably a problem with the upload actually as this not getting proper format settings yet.  Hopefully, this sorts out after migration of attachments.
