### ISSUE TITLE
'Shared with me' page

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#379]
The 'shared with me' page should show all of the objects from other users' private graphs which contain the current session user in an `ownedBy` predicate.

**Comment by cjmyers** [comment]
When you make someone an owner, we will add triples of the form:

<databasePrefix>/user/<username> sbh:sharedWithMe <URI of object>

where <URI of object> is just the URI of the object that the owner is added to and not the recursive dive of all objects made to be owned by this person.
