### ISSUE TITLE
Text not centered in search button on homepage

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#389]
<img width="895" alt="screenshot 2017-07-17 14 10 11" src="https://user-images.githubusercontent.com/454895/28269366-b5d37298-6af9-11e7-9f9b-583ef2ca0576.png">

**Comment by zachzundel** [comment]
Tweaked padding, this is the result:
![search centering](https://user-images.githubusercontent.com/3093325/28848422-1c4e4476-76d0-11e7-85ce-a5c0423c0063.png)
