### ISSUE TITLE
Should be a description of what you're looking at in "Benchling Transfers"

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#397]
Like "These are parts that have been transferred to Benchling from SynBioHub"

Also not clear how to get to Benchling from the SBH transfers page

**Comment by udp** [comment]
"Send to Benchling" should take you directly to Benchling

**Comment by cjmyers** [comment]
The description actually is what is entered into Benchling for the description of the folder.  I've changed the wording for Neil's group Benchling account to match text above.
