### ISSUE TITLE
Links starting with "http://api.benchling..." should not actually be links

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#400]
e.g. in the "Source" field

otherwise people click them and they end up with json in their browser

**Comment by udp** [comment]
If you wrap them in `<code>` tags they'll still look nice but won't be clickable

**Comment by cjmyers** [comment]
What would be even better likely is to open the Folder in Benchling.  Will check if that is possible.

**Comment by cjmyers** [comment]
Changed to "benchling.com" when no better wasDerivedFrom is available.
