### ISSUE TITLE
Some users can see the Benchling collection and some can't

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#401]

**Comment by cjmyers** [comment]
Users must be marked as members to see it.  This is a security issue.

Chris

**Comment by udp** [comment]
They were able to send to benchling but they can't see it afterwards, though?

**Comment by udp** [comment]
And putting the URL into the browser still worked.  So it's not exactly security.

**Comment by cjmyers** [comment]
Agreed, it was attempted security.  Need to tighten it up.

**Comment by cjmyers** [comment]
Now only members can view or submit to private remotes.
