### ISSUE TITLE
Hand ("click me") cursor should not be shown for sequence features that aren't clickable

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#402]

**Comment by cjmyers** [comment]
This one should be moved to VisBol tracker.

**Comment by udp** [comment]
no, the cursor is set by sbh's javascript, not visbol

**Comment by cjmyers** [comment]
Hmm, I cannot reproduce this.  I only see the hand for clickable parts.  Do you have an example which is getting hand but not clickable?

**Comment by zachzundel** [comment]
@udp could you give us steps to reproduce this? I'm not sure what it is either.

**Comment by zachzundel** [comment]
Moving to 1.1.0 until we get more information.

**Comment by cjmyers** [comment]
Can't reproduce closing.
