### ISSUE TITLE
Submission / wiki needs more biologist-friendly "help" pages

### ISSUE THREAD

**Issue by djskelton** [SynBioHub/synbiohub#407]
Clicking the **i** next to 'Collection ID' links to a list of terms. Some of the terms, e.g. "Collection" direct to the SBOL specification for more information, which includes terms such as "class" and "object" (not friendly for biologists) -- perhaps the wiki needs 'SynBioHub for Computing Scientists" and "SynBioHub for Biologists" sections?

**Comment by cjmyers** [comment]
Let's make the icon clickable at the top.  The text is already pretty clear how to reach synbiohub.org.

**Comment by cjmyers** [comment]
Agreed.  What we need is a user documentation, which is covered in this issue #892.
