### ISSUE TITLE
Drop downs in advanced search should be obviously dropdowns

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#409]

**Comment by cjmyers** [comment]
We are using a library for this not sure how to change that.  What was the problem exactly?

**Comment by zachzundel** [comment]
Couple users weren't clear that they could be searched and selected as a drop down.

**Comment by zachzundel** [comment]
@cjmyers here is a .gif of the expected behavior.
![select2](https://user-images.githubusercontent.com/3093325/28277379-b6f36fee-6b11-11e7-962d-c8561a1c03ac.gif)

**Comment by zachzundel** [comment]
Dropdowns were missing the image resource for the down arrow.
