### ISSUE TITLE
Id/name/description should be clearer in advanced search

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#410]

**Comment by cjmyers** [comment]
Explain?

**Comment by zachzundel** [comment]
Not sure yet, but a couple of people ran into the issue of assuming that they were more general fields than they were. Maybe we should change the labels to SBOL ID, SBOL Name, or SBOL Description, so it's clear that they map directly to the data model

**Comment by zachzundel** [comment]
Changed field label
