### ISSUE TITLE
Should be able to download protein sequences as GenBank

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#413]

**Comment by cjmyers** [comment]
DNA, RNA only, correct?

**Comment by udp** [comment]
:+1:

**Comment by udp** [comment]
Looks like we're wrong about GenBank not doing protein sequences - we found one

**Comment by udp** [comment]
https://www.ncbi.nlm.nih.gov/protein/663085257

**Comment by cjmyers** [comment]
This is probably a libSBOLj issue then.

**Comment by cjmyers** [comment]
Moved this issue to libSBOLj tracker.
