### ISSUE TITLE
Remove "Annotations" heading above the table at the bottom

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#414]
For a non SBOL person, "annotations" means "sequence annotations".  so it's confusing

Also we don't really need a heading there at all

**Comment by cjmyers** [comment]
No term would leave it as being under Member of Collections, which is not good.  

In Benchling, they are called "Custom Fields", how about that?

**Comment by udp** [comment]
How about "Other Properties"?

**Comment by udp** [comment]
"Fields" is really databasey

**Comment by cjmyers** [comment]
Changed to Other Properties.
