### ISSUE TITLE
Need to explicitly state whether a submitted part / device is made public or not

### ISSUE THREAD

**Issue by djskelton** [SynBioHub/synbiohub#416]
On the submission page, there's nothing to indicate whether the part submitted is public / private (although terms such as "Select some _public_ collections" would make me worry it's going to be made public). This would put me off using SynBioHub (prior to the point of publication) for fear of accidentally making something public.

**Comment by cjmyers** [comment]
Removed the word Public from the collections and added work Private to the top tabs.
