### ISSUE TITLE
Submitting the attached GenBank file does not give an error, but attempting to view the resulting component gives 'Error'

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#423]
[promoter-17n-40n-.gb.zip](https://github.com/SynBioHub/synbiohub/files/1153823/promoter-17n-40n-.gb.zip)

**Comment by cjmyers** [comment]
I did not get any errors for this.  I uploaded and viewed just fine.  Can you double check?

**Comment by cjmyers** [comment]
Also just uploaded no problem to dev.synbiohub.org, no issues.

**Comment by zachzundel** [comment]
Bizarre, I checked this live and it did produce an error. Can you try uploading it to an existing collection?

Thanks,
Zach

**Comment by cjmyers** [comment]
Ok, that generated an error.  Will look into it.

**Comment by cjmyers** [comment]
Ok, it is a combination of issues.

1) The GenBank file is missing a version.
2) libSBOLj converts this into an SBOL object with no version, but it should use the default SBOLReader version, logged libSBOLj issue.
3) Objects with no version in SynBioHub are assumed to actually have a version and are being referenced by persistentIdentity, so this code tries to find the latest version and redirect to that.

So, libSBOLj should be fixed to keep all objects on SynBioHub with versions.  However, I should be able to also fix the issue that if an object has no version that it is able to be looked up too.

**Comment by cjmyers** [comment]
This should be fixed now.  When missing a version and no element with a version can be found, it attempts to fetch without the version.  

When libSBOLj is updated, hopefully missing versions will not happen anymore.
