### ISSUE TITLE
Should not include trailing slashes when registering with web of registries

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#427]
These should be removed before sending request to web of registries or perhaps trimmed on receipt.  This is duplicated on the WoR tracker in case it should be done here.

**Comment by zachzundel** [comment]
Where should trailing slashes be trimmed? From the instance URL? Do they break things?

**Comment by cjmyers** [comment]
Web of registries entries cannot have trailing slashes as this breaks things.  Unfortunately, instanceURL and databasePrefix must have them or this breaks things.  Bad choices I know, but given this when you derive the web of registries entry from these config options, you must trim the trailing slash.  Perhaps we should rework things so these are consistent but that is likely a large change.

**Comment by zachzundel** [comment]
Resolving in the Web of Registries
