### ISSUE TITLE
Add ability to delete graphs to the User admin panel

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#450]
It would be nice to be able to delete user graphs from the admin panel.  Perhaps also public graphs, but there should likely be a "are you sure" and "are you really sure" warning on that one.

**Comment by zachzundel** [comment]
I think that it should be just an option to delete user graphs for users which have been deleted. Deleting public graphs and deleting user graphs for existing users would be really dangerous -- what's the use case?

**Comment by cjmyers** [comment]
Yes, this could be an option that you have when deleting a user, which would be fine.  Except it should be an option since right now the only way to change password for a user with a bogus email address is to delete them and re-add them.  In this case, you don’t want to delete the graph.

BTW: there is a significant bug on synbiohub.org (fixed now) which was blocking remove private from working correctly.  It appears to leave stray triples around.  This is why I want to remove the whole graph, since these graphs are full of bogus triples that I have no way to delete.

Again, a are you really really sure button is needed, especially if deleting public.  This is primarily going to be used when first setting up.  This could be done via virtuoso, but I believe we are trying to make it hard to access that in most cases.
