### ISSUE TITLE
Error when collection ID contains invalid characters

### ISSUE THREAD

**Issue by dwootton** [SynBioHub/synbiohub#451]
The following error occurs when you use invalid characters in the collection ID: 
Error
Error: Virtuoso 37000 Error SP030: SPARQL compiler, line 23: syntax error at '<' before 'https:' SPARQL query: define sql:big-data-const 0 define input:default-graph-uri <https://synbiohub.org/user/woottondylan> PREFIX sbol2: <http://sbols.org/v2#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX synbiohub: <http://synbiohub.org#> PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX prov: <http://www.w3.org/ns/prov#> PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#> SELECT ?persistentIdentity ?displayId ?version ?name ?description ?ownedBy ?mutableDescription ?mutableNotes ?mutableProvenance ?creator ?created ?modified ?wasDerivedFrom WHERE { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> a sbol2:Collection . OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> sbol2:persistentIdentity ?persistentIdentity . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> sbol2:displayId ?displayId . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> sbol2:version ?version . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> dcterms:title ?name . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> dcterms:description ?description . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> dc:creator ?creator . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> dcterms:created ?created . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> dcterms:modified ?modified . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> synbiohub:uploadedBy ?uploadedBy . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> sbh:ownedBy ?ownedBy . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> sbh:mutableDescription ?mutableDescription . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> sbh:mutableNotes ?mutableNotes . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> sbh:mutableProvenance ?mutableProvenance . } OPTIONAL { <https://synbiohub.org/user/woottondylan/Test mess/Test mess_collection/1> prov:wasDerivedFrom ?wasDerivedFrom . } } at Request.request [as _callback] (/home/deploy/synbiohub/lib/sparql/sparql.js:126:24) at Request.self.callback (/home/deploy/synbiohub/node_modules/request/request.js:188:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (/home/deploy/synbiohub/node_modules/request/request.js:1171:10) at emitOne (events.js:96:13) at Request.emit (events.js:188:7) at IncomingMessage.<anonymous> (/home/deploy/synbiohub/node_modules/request/request.js:1091:12) at IncomingMessage.g (events.js:292:16) at emitNone (events.js:91:20) at IncomingMessage.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by zachzundel** [comment]
Solution is likely the ID hint previously discussed between myself and @cjmyers in the style of the username suggestion.

**Comment by zachzundel** [comment]
Putting on 1.1 because it's small but 1.0.3 is frozen for new noncritical bugs

**Comment by cjmyers** [comment]
Actually, I thought I fixed this one.  I have this code which validates the id and version with regular expressions:

		if(submissionData.id === '') {
                    errors.push('Please enter an id for your submission')
		}

		const idRegEx = /[a-zA-Z_]+[a-zA-Z0-9_]*$/
		if (!idRegEx.test(submissionData.id)) {
                    errors.push('Collection id is invalid. An id is a string of characters that MUST be composed of only alphanumeric or underscore characters and MUST NOT begin with a digit.')
		}

		if(submissionData.version === '') {
                    errors.push('Please enter a version for your submission')
		}

		const versionRegEx = /[0-9]+[a-zA-Z0-9_\\.-]*$/
		if (!versionRegEx.test(submissionData.version)) {
                    errors.push('Version is invalid. A version is a string of characters that MUST be composed of only alphanumeric characters, underscores, hyphens, or periods and MUST begin with a digit.')
		}

For some reason, it does not seem to be working though.

**Comment by cjmyers** [comment]
This should give a much better error message now.  Please try it out.  

If satisfied, please close the issue.
