### ISSUE TITLE
Problem with citations that are not comma separated numbers

### ISSUE THREAD

**Issue by dwootton** [SynBioHub/synbiohub#452]
When I try to access my private submission, I get a 502 Bad gateway message:
https://synbiohub.org/user/woottondylan/LACQ_SWITCH/LACQ_SWITCH_collection/1

**Comment by zachzundel** [comment]
Could you send a screenshot of the error?

**Comment by dwootton** [comment]
![image](https://user-images.githubusercontent.com/30129761/29990064-aebfde6a-8f34-11e7-98af-1a1706fb4acc.png)

**Comment by dwootton** [comment]
I have verified that I'm logged in to the correct user and I'm using the correct domain (synbiohub.utah.edu).

**Comment by dwootton** [comment]
note: This could be related to entering a citation when creating a collection. I've been able to generate collections and access them if I don't add a citation.

**Comment by cjmyers** [comment]
Can you tell me what you are putting in the citation field to cause this?

**Comment by dwootton** [comment]
I'm pasting the citation URL- It gives me this error with both the toggle paper and the ACS Syn Bio paper.

**Comment by cjmyers** [comment]
Ah, I see.  You should paste only the PubMed Id number.  It is usually an 8 digit number.  If you want to cite more than one, then you put a comma between the numbers.  SynBioHub then looks up the reference for you.

Will fix the bug though to not allow this to crash the page.

**Comment by cjmyers** [comment]
Reopening because it should really give a better error message.

**Comment by cjmyers** [comment]
This is no longer throwing an exception, but the references returned will be odd since it will return a reference for every number it finds in the text.  Should add a regular expression check to both the submit page and this reference edit to ensure that the entry is a valid comma separated list of pubmed ids.

**Comment by cjmyers** [comment]
Need to add a regEx check on submission for citation list AND all mutable references update.

**Comment by cjmyers** [comment]
The wiki editor itself should likely be changed as it allows for full wiki content when only comma separated pubmedIds are allowed.  It should also say clearly when it is opened that only comma separated pubmedId's should be entered.

**Comment by zachzundel** [comment]
Moving this to 1.2.0 because rewriting the editor is more complicated than previously expected

**Comment by cjmyers** [comment]
Add regEx check to submit.js and updateCitations.js to ensure comma separated pubmedIds for 1.1.1.

Update the editor to a specialized one for pubmedIds in 1.2.0.

**Comment by cjmyers** [comment]
Checked now, but gives promise rejection.  Pop-up error would be better.  Also, still need to update the citation editor in 1.3.0.
