### ISSUE TITLE
Should not show mutable edit buttons if viewing user cannot edit

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#463]
Currently, the buttons are shown but the edits are not saved.

**Comment by cjmyers** [comment]
Hmm, I thought we fixed this one.  Are you checking this on the most up-to-date source?

**Comment by zachzundel** [comment]
No, sorry, this was just off that paper of issues to log, I will look now.

**Comment by zachzundel** [comment]
You're right, this is already fixed.
