### ISSUE TITLE
Indicate MapsTos for Components/FunctionalComponents/Modules

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#47]
For Components/FunctionalComponents/Modules, should indicate their MapsTos.

**Comment by cjmyers** [comment]
Done perhaps with visualization.

**Comment by 16zzundel5** [comment]
@cjmyers can this be moved to visbol?

**Comment by cjmyers** [comment]
Yes.

**Comment by cjmyers** [comment]
Moved to visbol tracker.
