### ISSUE TITLE
Problem sorting collection for labhost_All.xml

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#481]
This file hangs while sorting the collection.

**Comment by zachzundel** [comment]
I'm trying to replicate this, and I can't. 
https://synbiohub.utah.edu/user/zachzundel/LabhostAll/LabhostAll_collection/1/eb6bf27cf70396aecaa83f4d9bf23fbb8246d779/share

**Comment by cjmyers** [comment]
Seems to only happen when submitting it programmatically.  Did you submit with UI or with libSBOLj?

**Comment by zachzundel** [comment]
I submitted with the UI. Let's talk about this tomorrow.

**Comment by cjmyers** [comment]
No problem now. Closing.
