### ISSUE TITLE
Need a better way to associate SBML files with SBOL Models

### ISSUE THREAD

**Issue by PrashantVaidyanathan** [SynBioHub/synbiohub#489]
There doesn't seem to be a trivial way to associate SBML files to SBOL Models. 
The current workflow: 

1. Create an empty SBOL document and upload it to Synbiohub (by creating a new collection 'foo'). 
2. Upload all SBML files as attachments
3. Create an SBOL file where the URL or the SBML file is associated with the SBOL model. 
4. Upload the SBOL file to the same collection 'foo'. 

However when 'foo' is made public, the links to the SBML models still remain private. 

This issue could ideally be lumped with the issue of uploading attachments to SBOL Documents.

**Comment by cjmyers** [comment]
Agreed.  This needs to be resolved.  Zach is actually planning to look at this one soon.

**Comment by zachzundel** [comment]
COMBINE archive support now associates SBML with SBOL models.
