### ISSUE TITLE
Unable to attach images to collection

### ISSUE THREAD

**Issue by schnauzer** [SynBioHub/synbiohub#500]
When I click the image button in the editors for the description, notes, source and references field there is no file upload menu, only this:
![screenshot from 2017-10-06 20-34-14](https://user-images.githubusercontent.com/1291308/31304028-bfc6100a-aad5-11e7-8f56-1a27f2a9cb0d.png)

This prevents me from uploading files, of course.

**Comment by cjmyers** [comment]
Scroll to the bottom of the page.  There you should find the ability to add attachments.  Once you add the attachment, and if it is of png format, than you can add the image to the description.

**Comment by cjmyers** [comment]
Not an issue
