### ISSUE TITLE
Think about recursive delete of items

### ISSUE THREAD

**Issue by 3ach** [SynBioHub/synbiohub#502]
Could add in an extra button or prompt to check if child objects are recursively deleted.

**Comment by zachzundel** [comment]
Have to be careful that it is not allowed to remove from non-personal graphs

**Comment by zachzundel** [comment]
May also apply to collections, which do not currently have a delete button because it's not clear if you want to remove a collection or a collection and its members

**Comment by zachzundel** [comment]
Cannot delete empty collections, even though this should be a safe operation
