### ISSUE TITLE
Introduction/availability of user profile page or similar?

### ISSUE THREAD

**Issue by a4ff7810** [SynBioHub/synbiohub#505]
I currently can't seem to find a profile section or anything similar like that (I might just not have found it, though, in which case it should maybe be displayed more prominently, e.g. next to "Submit", "About" etc.). Combined with #504 I currently don't seem to have a way to see what my username is, should I forget it. Again, I might be missing something obvious.

**Comment by zachzundel** [comment]
From @tramyn: SynBioHub should have a account settings for each user that creates an account on synbiohub. The account should have features such as personal information (i.e. Full Name, e-mail, password reset) and any other settings that could be useful for the user.

This feature should be reflected on all SynBioHub instances.

**Comment by jakebeal** [comment]
Please! This is especially important given the security flaws in the current login API.

**Comment by cjmyers** [comment]
Ok, marked as a priority.  Though not sure there is a security flaw, since James says with https that these are encrypted before being sent to the website.

**Comment by zachzundel** [comment]
This is ready for review on PR #583

**Comment by zachzundel** [comment]
Merged!
