### ISSUE TITLE
Allow logon with username?

### ISSUE THREAD

**Issue by a4ff7810** [SynBioHub/synbiohub#506]
Maybe allowing users to log in using their user names might be an improvement, if usernames are unique, anyway (which I reckon they would be).

Cf. #504 and #505: If I didn't receive and e-mail and can't login with but remember my username, I can't even find out which e-mail I used to register with any more and thus can't log in any more.

**Comment by zachzundel** [comment]
PR #584 ready for review

**Comment by zachzundel** [comment]
Merged!
