### ISSUE TITLE
Better way of highlighting elements for top right corner navigation?

### ISSUE THREAD

**Issue by a4ff7810** [SynBioHub/synbiohub#507]
I find the "bold on hover" for the "Submit", "About" etc. links in the top right somewhat less than ideal. The changing width and shifting elements make it feel unruly in my opinion. Maybe something like https://stackoverflow.com/questions/556153/inline-elements-shifting-when-made-bold-on-hover, or https://stackoverflow.com/questions/5687035/css-bolding-some-text-without-changing-its-containers-size (using shadow) might work. Or possibly bolding could be done away with entirely and something along the lines of coloured background "tabs", highlighting the currently selected one that way etc. could be implemented instead. Surely there are other ways as well :)! Also see #505, maybe.

**Comment by cjmyers** [comment]
@udp  can you comment on this suggestion?
