### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#510]
SynBioHub should have a account settings for each user that creates an account on synbiohub. The account should have features such as personal information (i.e. Full Name, e-mail, password reset) and any other settings that could be useful for the user. 

This feature should be reflected on all SynBioHub instances.

**Comment by a4ff7810** [comment]
Very similar/identical idea has been assigned to Milestone 1.2.0 (see #505), but this contains some pertinent additional information. Merge issues/close duplicate?

**Comment by tramyn** [comment]
Hi @a4ff7810, 

Yes I agree, this issue should be merged with #505. Once it's merged, feel free to close this issue.

**Comment by zachzundel** [comment]
Merged, closing.
