### ISSUE TITLE
Collections display different contents in Explorer than they do Chrome

### ISSUE THREAD

**Issue by NeilWipat** [SynBioHub/synbiohub#515]
When logged in using Explorer to view SynbioHub collections, the page isn't not drawn properly and the wrong data is displayed for a collection. It's OK when not logged in. Works fine in Chrome. See the screenshot.
[SBOL iGEM distribution issue.pptx](https://github.com/SynBioHub/synbiohub/files/1463064/SBOL.iGEM.distribution.issue.pptx)

**Comment by cjmyers** [comment]
Can you confirm if you still have this problem and provide details on how to reproduce.

**Comment by cjmyers** [comment]
Cannot reproduce
