### ISSUE TITLE
Java components do not compile with Java 9

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#516]
Found this after I updated my computer Java to Java 9. 

![screen shot 2017-11-14 at 12 29 44 am](https://user-images.githubusercontent.com/3093325/32767959-f3ff1fc2-c8d2-11e7-8d4a-94edd378cb7c.png)

Compilation works if I switch back to Java 8. Probably something to do with the new typechecking in Java 9.

**Comment by cjmyers** [comment]
Hmm, would be good to log on the tracker so we can get it sorted.  Hopefully, it is something simple to fix.

Chris

**Comment by zachzundel** [comment]
Do you mean the libSBOLj tracker?

Thanks,
Zach

**Comment by cjmyers** [comment]
No, because the error message you showed was from synbiohub java code, unless I’m mistaken.

**Comment by zachzundel** [comment]
...you’re responding to this on the tracker? Is there another one I should log it on?

Thanks,
Zach

**Comment by cjmyers** [comment]
Oops.  Sorry too tired.  I thought it was on the mailing list. :-(

**Comment by zachzundel** [comment]
PR #643
