### ISSUE TITLE
Can't install; manifest not found

### ISSUE THREAD

**Issue by eyesmo** [SynBioHub/synbiohub#517]
New to using Docker, this may be a simple mistake on my part. I tried following the SynBioHub install instructions, and ran
>docker run -v synbiohub:/mnt -p 7777:7777 --name synbiohub -d synbiohub/synbiohub:v1.0.0

and got
>Unable to find image 'synbiohub/synbiohub:v1.0.0' locally
>docker: Error response from daemon: manifest for synbiohub/synbiohub:v1.0.0 not found.
>See 'docker run --help'.

I'm pretty sure Docker isn't broken, because I tried 
>docker install hello-world

and it worked (contacted Daemon, pulled image, created container, streamed output to terminal).

**Comment by zachzundel** [comment]
The command is a just little bit wrong. Our tags no longer begin with a lowercase **v**, so you should adjust it to be:

`docker run -v synbiohub:/mnt -p 7777:7777 --name synbiohub -d synbiohub/synbiohub:1.0.0`

And that works!

1.0.0 isn't the latest version, either, 1.1.0 is the latest. You can update the version in your command if you want the latest release.

Was this command on our documentation somewhere?

**Comment by eyesmo** [comment]
Thanks! Seems to be working now with
>docker run -v synbiohub:/mnt -p 7777:7777 --name synbiohub -d synbiohub/synbiohub:1.1.0

 The command I was using is on the SynBioHub wiki (http://wiki.synbiohub.org/wiki/Installation).

**Comment by cjmyers** [comment]
Great.  Zach: please update the docs.

Thanks.

**Comment by zachzundel** [comment]
Updated.
