### ISSUE TITLE
Migration of Attachments

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#519]
If the new Attachment class is approved, then we will need to migrate the Attachments in SynBioHub and the support of attachments to this new class.

**Comment by cjmyers** [comment]
0) libSBOLj and sboljs support for Attachments first
1) Render SBOL attachments correctly
2) Create SBOL attachments on upload
3) Download SBOL attachments
4) Convert SBH attachments to SBOL attachments

**Comment by cjmyers** [comment]
1. Render
views/toplevel.js should direct sbol:Attachment types to views/attachment.js
attachment.js needs to be updated to deal with either type of attachment
getAttachmentsFromTopLevel in lib/attachments.js needs to fetch both types of attachments
EdamOntology.js should include JSON array generated from EDAM obo file
Using this should be able to display format of file in human readable form.
Download attachment button should be connected to sbol:source field if sbol:Attachment
size should be displayed in top of page 
hash should be displayed in other properties

2. Create SBOL Attachments
actions/upload.js
lib/attachments.js
Modify to create sbol:attachment on toplevel, and sbol:Attachment

3. Download
api/downloads.js

4. Convert
SPARQL queries on startup
sbh:attachment -> sbol:attachment
sbh:Attachment -> sbol:Attachment
sbh:attachmentHash -> sbol:hash
sbh:attachmentSize -> sbol:size
sbh:attachmentType -> sbol:format
identity/download -> sbol:source

**Comment by zachzundel** [comment]
This is part of PR #591, and is ready for review
