### ISSUE TITLE
When I create an empty collection from scratch it appears to have things in

### ISSUE THREAD

**Issue by NeilWipat** [SynBioHub/synbiohub#521]
![synbiohub_collection_issue](https://user-images.githubusercontent.com/1294713/33031272-b0d8e44c-ce15-11e7-8f5c-9311d97c474d.png)

**Comment by cjmyers** [comment]
Could you try opening this Collection on https://dev.synbiohub.org?

I want to see if this is a bug that is in the current development branch of the code.

**Comment by cjmyers** [comment]
Please confirm if you still see this problem and provide details to reproduce.

**Comment by cjmyers** [comment]
Cannot reproduce
