### ISSUE TITLE
When I try to load a new part into the new collection it says it exists already

### ISSUE THREAD

**Issue by NeilWipat** [SynBioHub/synbiohub#522]
![synbiohub_collection_issue](https://user-images.githubusercontent.com/1294713/33031272-b0d8e44c-ce15-11e7-8f5c-9311d97c474d.png)
![synbiohuberror2](https://user-images.githubusercontent.com/1294713/33031922-8c77a1b8-ce17-11e7-9e00-61aa536f8406.png)

**Comment by cjmyers** [comment]
Please confirm if you still have this problem and provide details to reproduce.

**Comment by cjmyers** [comment]
Cannot reproduce
