### ISSUE TITLE
Submission does not work in the docker

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#529]
I think it must be something to do with the JDK version vs. whatever was used to build the zip library jar.  Either way, perhaps the zip library should be a maven dependency.

<img width="1324" alt="screenshot 2017-11-23 14 28 41" src="https://user-images.githubusercontent.com/454895/33180507-d9f077cc-d064-11e7-8e99-3b4a7e25cfb4.png">

**Comment by cjmyers** [comment]
I was getting this error too.  I just checked in a workaround which is to have the exception caught and assume the file is not a CombineArchive when this exception occurs.  This likely means CombineArchives don't work when this Zip library problem is present.  Still need a proper solution.

**Comment by cjmyers** [comment]
@zachzundel is this one still an issue?

**Comment by zachzundel** [comment]
I can't repliate this issue in the 1.2.0 docker release.
