### ISSUE TITLE
Change 'remove' to a POST request to avoid browser prefetching

### ISSUE THREAD

**Issue by 3ach** [SynBioHub/synbiohub#541]

**Comment by udp** [comment]
Removed security label and added bug.  This isn't a security issue but worse: it could result in parts being removed unintentionally without any user action.

**Comment by 3ach** [comment]
Don't think that links (`<a>` tags) will be prefetched based on [this article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ). Closing.
