### ISSUE TITLE
Large collections hanging on dev

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#543]
The AJAX request is failing on dev -- but is working on @cjmyers localhost with iGem data and on the reference instance.

**Comment by zachzundel** [comment]
The sort ordering query was taking too long. @cjmyers reverted the change, need to figure out a way to do proper secondary sort.

**Comment by cjmyers** [comment]
Seems to be an issue with str before lcase.  However, swapping them makes concat not work.  However, this is only needed due to the name being "empty" issue.  I'm going to close this though, as that is not essential, and it is working now.
