### ISSUE TITLE
Updating instructions on starting up synbiohub

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#546]
The instructions in the readme/wiki are not really complete.  On the readme, they are missing instructions about using tmux, setting up virtuoso, etc.  On wiki, they are focused on docker which is not completely up-to-date.  For reference, here are the instructions for starting up from source:

1) Open a new terminal and login as tomcat
2) tmux new-session -s virtuoso
3) cd /usr/local/var/lib/virtuoso/db
4) sudo /usr/local/bin/virtuoso-t -f
5) You may now close this terminal
6) Open a new terminal and login as tomcat
7) tmux new-session -s synbiohub
8) cd synbiohub
9) npm start

BTW: if this is the first time, you also need to do "mvn compile" in the java directory and currently you need to clone and mvn install libSBOLj.

**Comment by cjmyers** [comment]
Would also be good to document virtuouso configuration and how to start up in debug mode.

**Comment by zachzundel** [comment]
Updated.
