### ISSUE TITLE
Zip upload should alway remove 'unzipped/' from the filename.

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#547]
Filename includes 'unzipped' 😞

**Comment by zachzundel** [comment]
I'm working on this, and I think I figured out how to *fix* the issue, but I can't find where the `unzipped/` is present in a filename. Could you point me towards the right place?

**Comment by cjmyers** [comment]
if you call getAttachment in SynBioHubFrontend, this method will extract the filename returned in the header (see fetchContentSaveToFile).  This is returning “unzipped/<filename>”
