### ISSUE TITLE
Changing the Virtuoso login results in errors

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#555]
@nroehner reports that an instance of SynBioHub where the Virtuoso credentials have been modified in config.local.json is having issues. I can't spot (`grep`) anywhere where the credentials are hard-coded, so I don't think that's the issue.

# From email:

They changed the Virtuoso DBA user password and that is what seems to be causing this behavior. When SynBioHub starts up, even with valid credentials in the config.local.json file, they see the following:
```
synbiohub_1  | *** Error 28000: [Virtuoso Driver]CL034: Bad login
synbiohub_1  | at line 1 of Top-Level:
synbiohub_1  | USER_GRANT_ROLE('SPARQL', 'SPARQL_UPDATE')
synbiohub_1  | 
```
and then the service dies.

**Comment by cjmyers** [comment]
I think the problem is that we are assuming that both the dba and SPARQL users have the same password.  Can you ask them to set both of these users to the same password and see if that works?

Chris

**Comment by cjmyers** [comment]
Reported that it is fixed.  Perhaps a problem with SPARQL_UPDATE missing from dba user.
