### ISSUE TITLE
Curators are unable to delete records they make public

### ISSUE THREAD

**Issue by ckmadsen** [SynBioHub/synbiohub#560]
If I create a submission as a curator user, make it public, and try to remove it, I get a browser error saying that the page isn't redirecting properly.  However, admin users are able to remove public submissions just fine.

**Comment by cjmyers** [comment]
We strongly discourage removing public submissions.  Once a submission is made public others may use the information and it would be highly problematic for it to disappear.  Indeed, the ability of removing public collections should likely be off by default in production repositories.  

However, for debug purposes, we have the option in conflg.local.json:

"removePublicEnabled": true,

This adds the remove button to submission pages.  However, this feature is only available to admin users for the reasons above.  The assumption is that the people debugging would be admins.  However, I see an issue which is that a admin user cannot easily delete a non-admin user’s submission.  You would likely need to be first added as an owner then go to Shared With Me and select remove.  If this does not work, please let me know.

Please also leave this issue open as we should remove the Remove button on the submission page for non-admin users.

**Comment by ckmadsen** [comment]
Ah.  This makes sense and is in line with how I thought the SynBioHub should be used.  I agree that the button should be removed for non-admin users though.
