### ISSUE TITLE
Search results should prioritize small parts

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#562]
When I search for a commonly used part, such as J23117 or J23101, it's hard to find the part itself in the mess of other parts that use it and include its name in their description.

This problem could be remedied by having the search sort in a way that puts the core part at the top, e.g., by putting smaller and more "basic" parts first.

**Comment by cjmyers** [comment]
Great suggestion.  Michael is actually going to be transition to a new project once SBOLDesigner 3.0 is released, and the project is related to improving search on synbiohub using ideas of page/rank etc.  The small parts that are frequently used should get higher page rank and thus be higher on the list, I think.

**Comment by cjmyers** [comment]
Being addressed by SBOLExplorer

**Comment by cjmyers** [comment]
Should have been addressed with SBOLExplorer which is currently running on dev.synbiohub.org.  Now, when you search by J23117, it is on the first page.  Strange though it is not on the top of the list.  My suspicion is that it has to do with sequence clustering.  Namely, the parts listed higher have a high sequence similarity and higher page rank.  @michael13162 can you confirm this?

For J23101, it is the 2nd entry in the list.  Hmm, for this one, I checked "Find Similar" and it does not include J23100 which comes out on top of the J23101 search.  In this case, maybe it is the fact that the string text is similar and the page rank is higher.  @michael13162 thoughts?

**Comment by cjmyers** [comment]
Closing since addressed by SBOLExplorer.
