### ISSUE TITLE
Remove trailing delimiters in registry entries

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#564]
Registry entries should not have trailing slashes.  I think the issue is URL and database prefix in the config file do have these and when copied into registries, it is copied with the delimiter but web-of-registries always trims these.  It is good to be consistent though as it causes some problems with assumptions in the code about their not being a delimiter.

**Comment by zachzundel** [comment]
I'm a bit confused, does this mean we should just change the defaults? They should be consistently NOT present in the Web of Registries, if that's not happening then this issue should be logged there.

**Comment by cjmyers** [comment]
I think web-of-registries handles this fine.  However, when the URL/databasePrefix are copied into the registries on SynBioHub, it does not delete the trailing delimiter.

**Comment by zachzundel** [comment]
Ready for review PR #585

**Comment by zachzundel** [comment]
Merged!
