### ISSUE TITLE
Error when trying to open an entry on SynBioHubDev

### ISSUE THREAD

**Issue by chrisAta** [SynBioHub/synbiohub#569]
If you search for a part e.g. 'BBa_I757003', and then click on the first search result that shows up, it gives this error: 
```
TypeError: templates/layouts/topLevel.jade:85
    83|                         a(href=meta.wasDerivedFrom.toString().startsWith(config.databasePrefix)?'/'+meta.wasDerivedFrom.toString().replace(config.databasePrefix,''):meta.wasDerivedFrom.toString()) #{meta.wasDerivedFrom}
    84| 
  > 85|                 if meta.wasGeneratedBy.uri && meta.wasGeneratedBy.uri != ''
    86|                     h5 Generated By: 
    87|                         a(href=meta.wasGeneratedBy.url) #{meta.wasGeneratedBy.uri}
    88| 

Cannot read property 'uri' of undefined
    at eval (eval at wrap (/home/deploy/synbiohub_dev/node_modules/pug-runtime/wrap.js:9:4), <anonymous>:899:24)
    at template (eval at wrap (/home/deploy/synbiohub_dev/node_modules/pug-runtime/wrap.js:9:4), <anonymous>:2077:74)
    at Object.exports.renderFile (/home/deploy/synbiohub_dev/node_modules/pug/lib/index.js:331:38)
    at renderView (/home/deploy/synbiohub_dev/lib/views/componentDefinition.js:392:22)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
This same error seems to also happen when you try to access something you submitted yourself from the submissions page.

Both me and @Brad0440 have reproduced this same bug with different accounts.

**Comment by cjmyers** [comment]
Try npm update twice

Chris

**Comment by nathanwilk7** [comment]
@cjmyers or @zachzundel, Is the `meta` variable any top level object in this script?

**Comment by cjmyers** [comment]
Not exactly.  The meta variable is created in Javascript.  It copies and prepares these for presentation.

**Comment by cjmyers** [comment]
Is this working now?

**Comment by chrisAta** [comment]
The bug is gone, however some files just end up giving an empty table that says 'No data available in the table'. This one for example https://synbiohub.org/public/igem/BBa_S05277/1

**Comment by chrisAta** [comment]
Update: when you try to download a file with said empty table, the SBOL file has lost pretty much all content. This is what remains of https://synbiohub.org/public/igem/BBa_S05277/1 after I download it, resubmit it, and redownload it:

```xml
<?xml version="1.0" ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sbh="http://wiki.synbiohub.org/wiki/Terms/synbiohub#" xmlns:sbol="http://sbols.org/v2#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <sbol:Collection rdf:about="https://synbiohub.org/user/ChrisICOS/Test2/Test2_collection/1">
    <sbol:persistentIdentity rdf:resource="https://synbiohub.org/user/ChrisICOS/Test2/Test2_collection"/>
    <sbol:displayId>Test2_collection</sbol:displayId>
    <sbol:version>1</sbol:version>
    <dcterms:title>Test2</dcterms:title>
    <dcterms:description>Test2</dcterms:description>
    <dc:creator>Christian Atallah</dc:creator>
    <dcterms:created>2018-02-05T14:31:48.634Z</dcterms:created>
    <sbh:ownedBy rdf:resource="https://synbiohub.org/user/ChrisICOS"/>
    <sbh:topLevel rdf:resource="https://synbiohub.org/user/ChrisICOS/Test2/Test2_collection/1"/>
    <rdf:type rdf:resource="http://sbols.org/v2#Collection"/>
  </sbol:Collection>
</rdf:RDF>

```

This happens on both synbiohub.org AND dev.synbiohub

**Comment by cjmyers** [comment]
This is the correct behavior.  When you submit a file, any objects already found in a synbiohub instance are filtered out before the submit.  This is to prevent duplicate entries from getting created.  Whenever you submit new objects, they should not be in the namespace of a SynBioHub instance, since these are assumed to already reside in SynBioHub.

**Comment by cjmyers** [comment]
Can you provide more details on this?  When I open the link you give on the dev server, I see a part entry.

**Comment by chrisAta** [comment]
Ah, well if that's the intended behaviour then it's not a bug! I didn't know about this so I just kept trying with the same files. Changing the name inside the file fixed that, so I think everything's fine.

This can probably be closed then.

**Comment by gyanezfeliu** [comment]
This happens even if the file is not in a public collection?
We made tests uploading files to synbiohub.org and then to our instance at synbiohub.ing.puc.cl:7777. The former works, the latter shows an empty collection with "No data available in table".

Thanks

**Comment by cjmyers** [comment]
To be clear, are you uploading to synbiohub.org, then downloading the SBOL and uploading to your instance?  If so, yes, these parts will be omitted since it is assumed that they will be found in synbiohub.org.  Am I missing something?

If this is not correct, could you provide the SBOL file you are trying to upload to your instance?

**Comment by gyanezfeliu** [comment]
Please find attached 2 SBOL files.
I can upload "test.sbol" to synbiohub.org and to my instance. The other
file I cannot showing this message inside the collection:

[image: image.png]

Thanks

**Comment by cjmyers** [comment]
Sorry but the files did not come through.  I think you cannot simply attach to email.  Can you zip the files and attach them to the issue on github.  Sorry for the trouble.

**Comment by gyanezfeliu** [comment]
Sure!

**Comment by gyanezfeliu** [comment]
[files.zip](https://github.com/SynBioHub/synbiohub/files/2856497/files.zip)

**Comment by cjmyers** [comment]
Sorry for the delay in responding.  The second file has a lot of problems.  This file is an SBOL1 and not an SBOL2 file, so it needs converting.  It also is not a valid XML document, since it is missing namespaces at the top.  Finally, I'm not even sure it is a valid SBOL1 file, since it does not appear to convert properly even when the namespaces are added.  Where did you obtain this file?  It seems to have a number of issues.  Thanks.

**Comment by gyanezfeliu** [comment]
Hi, sorry for the delay.
We used SBOLDesigner v3, but instead of just saving the file, we exported
as an SBOL 1.1. Now it works perfectly.
Thanks

**Comment by cjmyers** [comment]
Ok, I see.  You should actually just save, so you get an SBOL 2 file, unless you wanted SBOL 1.1 for some reason.

**Comment by gyanezfeliu** [comment]
Yep, thanks for the support.
