### ISSUE TITLE
Attachments not linking correctly when uploaded in a ZIP file

### ISSUE THREAD

**Issue by ckmadsen** [SynBioHub/synbiohub#571]
When uploading a ZIP archive file containing both SBOL data and SBML model attachments, the attachments are given their own URIs, but these URIs are not used in the Model objects' "source" properties.  Instead, the "source" property contains "file:///tmp/<filename>" which doesn't link to anything and gives errors if the SBOL is downloaded and used elsewhere.  For example, the models in the following collection have this problem as they were uploaded as part of a ZIP archive:

https://synbiohub.cidarlab.org/public/AlphaTest/AlphaTest_collection/1

**Comment by cjmyers** [comment]
What was the value of the source field when you uploaded the SBOL?  

I think it needs to be “file:<filename>”  

Also, it looks like your file is in a sub-directory in your zip.  Could you perhaps provide your zip, so we can see how it is structured?

**Comment by PrashantVaidyanathan** [comment]
The zip files do not have any subdirectory structure. They are all in the same level. 

We tried file:<filename>:
`<sbol:source rdf:resource="file:pL2f1437.xml"/>`

However, we get the following error: 

`Error: org.sbolstandard.core2.SBOLValidationException: sbol-10202: The identity property of an Identified object MUST be globally unique. Reference: SBOL Version 2.2.0 Section 7.4 on page 17 : https://synbiohub.cidarlab.org/user/prash/AlphaTest/_model/1 at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:2132) at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1961) at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1933) at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:289) at org.synbiohub.Main$1.run(Main.java:30) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) at responseCallbacks.(anonymous function) (/home/tomcat/synbiohub/lib/java.js:89:24) at DestroyableTransform.javaProcess.stdout.pipe.on (/home/tomcat/synbiohub/lib/java.js:51:5) at emitOne (events.js:96:13) at DestroyableTransform.emit (events.js:188:7) at readableAddChunk (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:212:18) at DestroyableTransform.Readable.push (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:171:10) at DestroyableTransform.Transform.push (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:123:32) at DestroyableTransform.write [as _transform] (/home/tomcat/synbiohub/node_modules/binary-split/index.js:24:14) at DestroyableTransform.Transform._read (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:159:10) at DestroyableTransform.Transform._write (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:147:83) at doWrite (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:338:64) at writeOrBuffer (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:327:5) at DestroyableTransform.Writable.write (/home/tomcat/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:264:11) at Socket.ondata (_stream_readable.js:555:20) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7)`

**Comment by cjmyers** [comment]
Sorry, I was wrong.  It should be “pL2f1437.xml” without the “file:” otherwise it tries to convert the SBML to SBOL for you.  I assume you are providing SBOL already and don’t want this behavior.

Could you perhaps send the zip file?

**Comment by ckmadsen** [comment]
The fix you posted solved this problem.  Thanks!
