### ISSUE TITLE
URL for attachments do not get updated when a collection is made public

### ISSUE THREAD

**Issue by PrashantVaidyanathan** [SynBioHub/synbiohub#572]
While uploading a collection with attachments (as a zip file), the collection is first created a private collection. 

However when this collection is made public, the URL for the attachments in the collection are changed to make it public. However, the link to the attachments are not made public. 
Consider this collection: 
https://synbiohub.cidarlab.org/public/AlphaTest/AlphaTest_collection/1

The Model here:
https://synbiohub.cidarlab.org/public/AlphaTest/GFP_Model/0.2

Has an attachment which still points to 
https://synbiohub.cidarlab.org/user/prash/AlphaTest/attachment_00009T8ZeIMnLWGJaM6gG8/1

which was the URL before the collection was made public. However it should point to (which is the updated URL of the attachment after it was made public) 
https://synbiohub.cidarlab.org/public/AlphaTest/attachment_00009T8ZeIMnLWGJaM6gG8/1

Hence the attachment returns an error since the private URL of the attachment doesnt exist anymore.

**Comment by cjmyers** [comment]
This should be fixed now please test.

**Comment by PrashantVaidyanathan** [comment]
Yes. The most recent update solved the issue.
