### ISSUE TITLE
SynBioHub should return an error when trying to upload a duplicate

### ISSUE THREAD

**Issue by chrisAta** [SynBioHub/synbiohub#575]
At the moment, if you try to upload a file that already exists in a SynBioHub instance i.e. a duplicate, the submission goes through showing just an empty table. 

In the case of a full duplicate where everything gets trimmed out, it should probably give you some error statement to let the user know.

**Comment by jakebeal** [comment]
I want to bump the priority of this one.  I just got burned by it as well.

**Comment by cjmyers** [comment]
Duplicate of #916 which is more detailed, so closing this one.
