### ISSUE TITLE
Issues with Docker instructions

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#577]
The Mac link downloaded a non-functional docker application.  I think the link should point to the general docker install page, so they can make sure to get the latest version.  

Also, some of the instructions were not relevant or incorrect on Mac.  The gpasswd command for example.  It should be clear that this is not needed.  Would be also nice to explain how to start docker running using the whale at the top of the screen, since the docker command is not available in the terminal until you do this.

**Comment by zachzundel** [comment]
Updated to point to the Docker docs for Docker installation techniques and instructs user that the daemon must be running.
