### ISSUE TITLE
Add ability to disable self-registration

### ISSUE THREAD

**Issue by jnguyen88** [SynBioHub/synbiohub#587]
Request: Add ability to disable self-registration
Reason: Add extra layer of security [defense in depth]. Even though the server hosting the application is behind a firewall, BBN had instances in the past where people [internal and external] would self-register themselves and have access to the application. Other application such as Gitlab, Bugzilla and Atliassian products have this feature available.

**Comment by zachzundel** [comment]
Duplicate of #586 , closing

**Comment by zachzundel** [comment]
This has been fixed by PR #588 and merged into master.
