### ISSUE TITLE
Attachment source tag not updated after making public

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#593]
When making public, all URIs that dereference to SBOL objects on this SBH get updated to the new public URI prefix.  However, the sbol:source URIs do not point to actual objects, so they will need to be updated manually to the correct new URI.

**Comment by zachzundel** [comment]
Oh, this makes sense now. 

Thanks,
Zach

**Comment by cjmyers** [comment]
Fixed.
