### ISSUE TITLE
HTTP API Documentation Could Use Examples

### ISSUE THREAD

**Issue by nroehner** [SynBioHub/synbiohub#598]
It would be helpful to provide examples of parameters for the various HTTP API methods. We have collaborators that have mistakenly tried to include angle brackets in their curl request, e.g.

curl -X POST -H "Accept: text/plain" -d "email=\<person@gmail.com\>&password=\<opensesame\>"  https://synbiohub.org/login

**Comment by cjmyers** [comment]
Please see:

https://synbiohub.github.io/api-docs/#about-synbiohub

**Comment by cjmyers** [comment]
@nroehner please check the API docs linked above.

**Comment by cjmyers** [comment]
Being sorted in new API docs
