### ISSUE TITLE
Fetching a non-local attachment should dereference the source field

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#611]
When fetching an attachment, that has a source field that is not local, it should dereference the source field to grab the referenced file.

**Comment by zachzundel** [comment]
Is this on download only or on render?

**Comment by cjmyers** [comment]
Download would be fine.  Render would be extra credit.  Since only currently render PNG, probably not a high priority.

**Comment by zachzundel** [comment]
I think this is already done, I verified with the attachment_pointers.xml test file.
