### ISSUE TITLE
SynBioHub Webpage Using too much Memory

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#614]
My SynBioHub instance is starting to slow down when I try to perform search and navigating around private and public collections. I get this message displayed at the top of my browser whenever I try to browse my collections through the search bar:

<img width="640" alt="sbh_memory" src="https://user-images.githubusercontent.com/7537729/38680341-176d6956-3e34-11e8-820d-d2304d701d6d.png">

I understand that as I store more information on SynBioHub, the performance of SynBioHub will be affected. But, it would be great if SynBioHub could see how they can account for this performance issue.

**Comment by cjmyers** [comment]
How many entries do you have in the collection you are trying to view?

**Comment by tramyn** [comment]
Each collection stored in our current SynBioHub instance ranges between 30 - 100K triples. There are no noticeable lag when looking through collections. The manage submissions page is where this occurs. On manage submissions, I have over 80,000 collections I want to filter through and when I try to make use of the search box to filter, each character I type takes a while for the website to respond before I can see the next character that I type.

**Comment by cjmyers** [comment]
The manage submissions page should use limits/offsets to allow scrolling through large lists of Collections.
