### ISSUE TITLE
SQL database not persistent

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#616]

**Comment by cjmyers** [comment]
Docker issue.  Should be fixed.  Need to test and update docker instructions.

**Comment by zachzundel** [comment]
This issue is fixed, but people running an old version of SynBioHub in Docker willl *lose* the data in their SQL database. I don't have a fix for this yet, but could develop one if necessary. I am not sure it's worth the cycles since I'm not sure if anyone's running the old version in production.

**Comment by cjmyers** [comment]
Hmm, this is a pretty big issue though.  Really not sure who is running the docker version.

**Comment by zachzundel** [comment]
Yeah. I think it’s a documentation problem at this point. I need to figure out what the workflow is for moving the SQL information out of the Docker image, upgrading the volume and image to a working version, and then moving the old data into the new Docker volume and write it up. I’m not sure where would be the best place to publish this information so anyone using it sees it — maybe the wiki?

Thanks,
Zach

**Comment by cjmyers** [comment]
I guess adding it to the docker wiki and the release notes for the next release of SynBioHub.  As long as there are instructions as to how to not lose the SQL database, I guess we are fine.

Thanks,
Chris

**Comment by jamesscottbrown** [comment]
[Apparently you can copy a file from a Docker container to the host](https://stackoverflow.com/a/22050116) without needing a mounted data volume. So the easiest fix would be to get the container id with ``docker ps`` then run:

    docker cp <containerId>:/mnt/data/synbiohub.sqlite ./synbiohub_data.sqlite
    docker cp <containerId>:/mnt/config/synbiohub.sqlite ./synbiohub_config.sqlite

(all database connections should be closed first so that there's no data sitting in ``.wal`` or ``.shm`` files). 

This is easier than what I was going to suggests, which was to commit the container to create a new image, then start a container running from this with a data volume mounted, and copy the database files into this volume.

**Comment by tcmitchell** [comment]
The only `.sqlite` file I could find inside my docker container running synbiohub 1.3.0 is `/opt/synbiohub/synbiohub.sqlite`. What are the two sqlite files listed above in `/mnt`? My container does not have any `.sqlite` files under `/mnt`.

It seems easy enough to copy the `/opt/synbiohub/synbiohub.sqlite` out of the container using `docker cp` for backups until an updated docker container is released.

**Comment by zachzundel** [comment]
Hi, I think we just have the one... @jamesscottbrown are you working on some fork of SynbioHub?

**Comment by jamesscottbrown** [comment]
No: I was just hastily misreading the Dockerfile - sorry for the confusion.

**Comment by cjmyers** [comment]
Hi, there was a typo.  There is only one sqlite file.  Here is what we think will work, but we are having some issues checking.

1) Start your 1.3.0 instance.
2) docker cp <containerId>:/opt/synbiohub/synbiohub.sqlite ./synbiohub.sqlite
3) Start the snapshot instance
4) docker cp ./synbiohub.sqlite <containerId>:/mnt/data/synbiohub.sqlite

Note that if you are just running a new 1.3.0 or earlier instance than the last command should be:

docker cp ./synbiohub.sqlite <containerId>:/opt/synbiohub/synbiohub.sqlite

Please let us know how this works for you.

**Comment by cjmyers** [comment]
@zachzundel is this ready to be closed?

**Comment by zachzundel** [comment]
It is not. I need to write documentation on the wiki. I am about to lose reception but I’ll do it when I get back on Monday. 

Thanks,
Zach

**Comment by zachzundel** [comment]
Documented [here](http://wiki.synbiohub.org/wiki/Installation#DATA_CONSISTENCY_WARNING).
