### ISSUE TITLE
Public Account Creation Not Completely Turned Off

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#618]
I have disabled my SynBioHub instance to prevent users from creating public account through the register page by unchecking "Allow Public Account Creation".  Doing so, I do not see the register page show up on my instance's home page. However, I can still access the register page if I append my SynBioHub URL with "/register".

**Comment by cjmyers** [comment]
Must be logged in as an admin user when you hit /register endpoint

**Comment by tramyn** [comment]
What does it mean by "I must log in to hit /register endpoint?" I was able to access the register webpage whether I log in as an admin or not log into my instance.

**Comment by cjmyers** [comment]
Sorry that was a note to remind us that to fix this bug, we must add a check that either public account creation is allowed OR you are logged in as an admin.  We need to add this check, it is not there yet.

**Comment by zachzundel** [comment]
PR #636
