### ISSUE TITLE
Full Tmp Directory Prevents Upload to SynBioHub

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#619]
This is to document an issue that was resolved when SynBioHub v1.3.0 was released. 
The issue was a tmp directory was not clearing up tmp files that are produced when uploading an SBOL file to a new collection. These tmp files had the following extensions .omex, .xml, tmp-, and .zip. If I were to continue pushing data to SynBioHub overtime, the tmp directory will get to a point where the tmp directory has taken up 100% of the available space and prevent a SynBioHub user from continuing to upload to SynBioHub.

**Comment by cjmyers** [comment]
Fixed.
