### ISSUE TITLE
SBOL Validation Affects Upload Time

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#620]
I have been uploading SBOL files with different file size to my SynBioHub instance and the time it takes for certain uploads are not matching up with the result that I am expecting. One specific test case that I have done is uploading 4 SBOL files with the following size: 62 triples (6KB), 450 triples (40KB), 4359 triples (497 KB), and 10,000 triples (953 KB). Of the four files, three of them have the same data but are subsets of each other. For example, the SBOL file with 62 triples is a subset of 450 triples and the file with 450 triples is a subset of 4,359 triples. The fourth SBOL file (10,000 triples) have no relation to the other three files and are composed of 2,000 synthetic ComponentDefinitions. 

When I record the time it takes to push these 4 files, I expect a linear growth rate as the file size gets larger. The result shows that the three SBOL files (62 triples, 450 triples, 4359 triples) are indeed growing linearly but the fourth file (10,000 triples) is taking just as long  to perform a push to SynBioHub as the 4,359 triples SBOL file. I have also tested the 10,000 triples with smaller files with the same information that are subsets of the 10,000 triples. As expected, there is a reasonable linear growth rate. I am aware that SynBioHub does validation of the data that gets uploaded to SynBioHub and I can conclude that SBOL validation is affecting the time it takes to perform an upload. When the data structure has more validation rules that needs to be verified, the time it takes to perform that upload will increase in addition to file size.

This is one limitation that SynBioHub should consider to help decrease the time it takes to perform an upload to SynBioHub, especially if the files to be uploaded are quite large and has a lot of validation rules to go through.

**Comment by cjmyers** [comment]
Need to instrument a bit more to discover where the runtime is going.  May get Meher to help with this one with her testing structure.

**Comment by cjmyers** [comment]
Actually appears to be changeURIPrefixVersion in libSBOLj

**Comment by cjmyers** [comment]
Update to libSBOLj has significantly improved upload time.
