### ISSUE TITLE
Error Viewing ComponentDefinition on Private Collection

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#622]
I have a collection with 3 ComponentDefinitions on SynBioHub v1.3.0. 
When I try to view one of the three ComponentDefinitions, I got this error.

Error: https://synbiohub.bbn.com/user/tramyn/overwrite_coll/compDef1/1.0.0 not found: https://synbiohub.bbn.com/user/tramyn/overwrite_coll/compDef1/1.0.0
    at fetchSBOLObjectRecursive.then (/opt/synbiohub/lib/views/componentDefinition.js:86:35)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by cjmyers** [comment]
Can you give a bit more details on this?  How did you create the collection?  Can you provide the file you used and steps to create?  The error message is exactly what it says which is that the object does not exist.  Are you able to see a object on the Collection view and clicking on it fails?

Please also try refreshing your collection view and trying again.

**Comment by tramyn** [comment]
This collection was created using pySBOL's method and was also tested by using the web interface. 
This file has been validated with no errors and it has been uploaded to SynBioHub.utah.edu's instance without any problems. For some reason, this fails when I try to browse these three ComponentDefinitions on BBN's instance. Same error occurs after refreshing my browser.

File is attached. 
[test.zip](https://github.com/SynBioHub/synbiohub/files/1940405/test.zip)

**Comment by cjmyers** [comment]
Do you have the same problem on synbiohub.utah.edu <http://synbiohub.utah.edu/> or is this unique to your instance?

**Comment by tramyn** [comment]
unique to my instance.

**Comment by cjmyers** [comment]
I also cannot reproduce this on my system.  What happens if you attempt to download the SBOL from the Collection page?  Can you send screenshots from the Admin Status, General, and Graph pages?

**Comment by tramyn** [comment]
We had to restart our SynBioHub instance so resolve this issue. I'm not clear what caused the issue but this issue can no longer be reproduced. I can now view parts within a specified collection without any errors popping up.

**Comment by cjmyers** [comment]
Strange.  Okay, let's us know if it occurs again.
