### ISSUE TITLE
Hovering info box can't follow horizontal scrolling

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#624]
Particularly large constructs often don't fit horizontally onto the screen.  To look at such a construct, one has to scroll to the right, which is fine.  The black "info box" that pops up when one hovers over a glyph, however, gets stuck maxing out at the window width and cannot follow the scroll.

This prevents the user from seeing "pop-up" information about large constructs, because it appears way off to the left of where the mouse cursor is, often entirely off the left side of the window.

**Comment by cjmyers** [comment]
This is actually a VisBol bug, so I've copied this issue over to that tracker.

**Comment by cjmyers** [comment]
https://github.com/VisBOL/visbol-js/issues/71
