### ISSUE TITLE
SO:0000035 rendered as generic engineered region

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#630]
Riboswitches (role=SO:0000035) are being rendered in SynBioHub as a generic Engineered Region even though they are a child of SO:0000834 (Mature Transcript Region) and as such should get the "Non-Coding RNA Gene" glyph.

**Comment by cjmyers** [comment]
This and anything to do with visualization are visbol bugs.  I've moved this one to the visbol tracker:

https://github.com/VisBOL/visbol-js/issues/72
