### ISSUE TITLE
Broken definition links

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#631]
SBH links like this: http://sbols.org/v2#FunctionalComponent
end up resolving to locations on the SBOL website like this: http://sbolstandard.org/downloads/specifications/specification-data-model-2-1-0/#FunctionalComponent
that give 404 errors.

**Comment by cjmyers** [comment]
Ah, good catch.  We used to have links to the specification for these, but we removed these links to avoid confusion.  However, we missed these on the module view.  We should remove these as well.

**Comment by cjmyers** [comment]
Links removed.
