### ISSUE TITLE
Upward navigation when browsing sub-collection

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#632]
When browsing a submitted collection, one often wants to browse its sub-collections.
Once you have gone down into one, however, there is no readily accessible link that takes you back to the parent collection.  You either have to go "back" (which may be quite a ways, if you are exploring a complex collection) or have to know to open go look inside the "member of these collections" tab.

**Comment by cjmyers** [comment]
Upward navigation is tricky since there is no rule that an object is a member of only one collection, so it is not simply find the collection that has this object as a member.  The browser, however, does remember the path you took down, if you just want to back out the same way you came down.

**Comment by udp** [comment]
Which is fine if you ignore the typical case that each TopLevel is part of exactly one collection.

Sent from my iPhone

On 25 May 2018, at 23:14, cjmyers <notifications@github.com<mailto:notifications@github.com>> wrote:


Upward navigation is tricky since there is no rule that an object is a member of only one collection, so it is not simply find the collection that has this object as a member. The browser, however, does remember the path you took down, if you just want to back out the same way you came down.

**Comment by jakebeal** [comment]
I agree with James: so far in our usages, there is typically a clear hierarchy of collections (perhaps not exactly one, but one directed chain).

**Comment by cjmyers** [comment]
Unfortunately, this is not the typical case.  In the iGEM collection, all parts are members of the iGEM collection AND also part of zero, one, or more category collections.  If the part is in the distribution, then they are members of the distribution collection.  

Also, anything that is submitted along with a Collection that it is a member of, will be a member of that Collection as well as the root Collection created by the submission process.  In this case, I agree there is a hierarchy of collections, but the query to determine this may be involved.

Also from the UI standpoint, I'm not sure what you have in mind and how it differs from the back button on your browser.

**Comment by jakebeal** [comment]
So how about a link up to the root collection, at least?

The problem is that when I'm browsing a big collection that spans multiple pages, I might be a dozen "back" clicks away from being able to go up.

**Comment by cjmyers** [comment]
That should be easy

Chris

**Comment by cjmyers** [comment]
Sorry this one got lost for awhile.  I've added a "Back to root collection" button.

<img width="528" alt="Screen Shot 2019-06-28 at 12 17 33 PM" src="https://user-images.githubusercontent.com/3507191/60338799-d8a3b280-999e-11e9-8078-0d7c0a689152.png">

**Comment by cjmyers** [comment]
It is the green back arrow, and it takes you to the root collection that this is contained in.

**Comment by cjmyers** [comment]
It is up on staging.  I'm closing this issue.  @jakebeal please reopen if you have any remaining concerns.

**Comment by jakebeal** [comment]
Thanks --- looks good!
