### ISSUE TITLE
SEVAhub unable to show components

### ISSUE THREAD

**Issue by AGMoreno** [SynBioHub/synbiohub#633]
If you go to sevahub.es and try to see any SBOL design you will always get to this error:

Error: http://sevahub.es/public/pSEVA621/ComponentDefinition_pSEVA621/1 not found: http://sevahub.es/public/pSEVA621/ComponentDefinition_pSEVA621/1
    at fetchSBOLObjectRecursive.then (/opt/synbiohub/lib/views/componentDefinition.js:82:35)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Any idea?

**Comment by cjmyers** [comment]
It is likely an issue with configuration.  Can you give me (myers) admin access?  Then, I can check this out.

**Comment by cjmyers** [comment]
What was the issue?
