### ISSUE TITLE
Silent failure when uploading collection

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#634]
I am trying to upload the iGEM 2016 interlab designs, to be used as a supplemental with the paper. When I upload this, however, SynBioHub silently fails, producing only an empty collection.

[SBOL file](https://gist.github.com/jakebeal/0ef97941357675d8b2bd6eb9b6fe7aee)

**Comment by cjmyers** [comment]
It is not actually failing.  Instance so SynBioHub assume that if you upload objects with namespaces in any SynBioHub in the WebOfRegistries that it already exists in that SBH.  This is necessary to avoid accidentally adding objects used from one SBH into another SBH and getting duplicate entries in different SBHs.

This also means you cannot download an SBOL file from one SBH then try to upload it to another.  

Note that we do not give any warning message because this is a VERY common case.  Image you use SBOLDesigner to create a new design using parts from the iGEM registry then upload your design.  You don’t want to re-upload the iGEM parts, they are already there.  You only want to upload the new composite that you created.

**Comment by jakebeal** [comment]
I just want to make a collection of those composites that I can share publicly and link from the article supplementary information. I am not getting this: I am getting an empty collection.

How do I make this happen?

**Comment by cjmyers** [comment]
First, I suggest you make a collection for all your supplementary files, let’s call that “JakeSupplementary”.  You can do this by making a submission but not providing a file, which will create an empty collection.  You then make this public.

Next, create a Collection in your OWN namespace (http://jake.beal.org <http://jake.beal.org/>) or similar.  Add members to that collection that are links to your other objects that you have already uploaded to another SynBioHub presumably (synbiohub.utah.edu <http://synbiohub.utah.edu/>, it appears).  Unfortunately, we don’t have any simple software to do this for you, so you need to do this with your own little code using pySBOL or libSBOLj.

Next, upload just that collection.  You will end up making a submission collection with this collection as a member.  

Finally, you will make this Collection public into another collection, namely, “JakeSupplementary”.

Which instance are you using?  Will need to make you a curator for the make public steps.

Hmm, okay, I think I see something we can do to make this simpler.  Before removing duplicate top-levels, we should add these as members of the new submission Collection.  Need to think about that for a bit though as this has a serious side-effect which is your Collections will get a lot larger as all referenced elements will end up as members.  However, the filter referenced elements bit will help here to keep the list manageable.

**Comment by jakebeal** [comment]
OK, I've re-created my collection from scratch, and I _think_ it has uploaded correctly (when I download the file and open in SBOL Designer, it comes up blank, but all the contents look right online?).

Now, how to I make it public?

Private URI is: https://synbiohub.org/user/jakebeal/iGEM_2016_interlab/iGEM_2016_interlab_collection/1
I can't find any sharing URI for the collection, either.

**Comment by jakebeal** [comment]
Apparently this button does not appear in Chrome.  If I go to Safari, it appears that I can get a sharing link, but there is no option for making the collection public, only for sharing via a link.

How do I make a public collection?

**Comment by jakebeal** [comment]
It's a supplemental for a PLOS ONE article, which I don't think has an current collection.

Can you please take a look and tell me if there is anything that you see that needs correction before it is exposed as a public collection?

**Comment by cjmyers** [comment]
Sure, but I need a share link, and likely a few hours sleep.  Just got back from London this afternoon.

**Comment by jakebeal** [comment]
Here is a share link: https://synbiohub.org/user/jakebeal/iGEM_2016_interlab/iGEM_2016_interlab_collection/1/ed56bd9817af4a395819a050e290135d3a9a566b/share
The second part I can't help you with. :-)

**Comment by cjmyers** [comment]
Actually looks pretty straightforward.  Do you think we should have a Collection for each individual journal?  Or, perhaps a PLoS collection?  Creating such a Collection is fairly straightforward.  You just do a submit with no file.  If you would like to create this collection and send me a share link for that, I can make both public for you after giving it a sanity check.
