### ISSUE TITLE
Sharing button missing on Chrome on Mac

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#635]
The "Button with bent arrow" for private sharing of a collection does not appear in my copy of Chrome on Mac (up-to-date at version 66.0.3359.181 (Official Build), running on OS 10.12.6).

Instead of the sharing button, there is a truncated green box about 1/3 height that does nothing when clicked.

**Comment by jakebeal** [comment]
Figured it out... I use an ad-blocker, and apparently it thinks that that icon, and only that icon is an ad. I have disabled it on synbiohub.org, and that apparently does the trick.

**Comment by udp** [comment]
Which ad blocker?

**Comment by jakebeal** [comment]
Adblock Plus

**Comment by udp** [comment]
Thanks

I'll leave this open, as it's likely we just need to change the class of the button from "share" to something else.
