### ISSUE TITLE
Add "Are you sure you want to remove?" safeguard

### ISSUE THREAD

**Issue by bbartley** [SynBioHub/synbiohub#645]
When pressing the remove button, synbiohub should prompt the user to confirm before actually deleting stuff.

This hasn't been a problem so far, but it's just a matter of time until some user in a hurry accidentally clicks the wrong thing.

**Comment by cjmyers** [comment]
@zachzundel can you add a popup confirmation for this?  Thanks.

**Comment by zachzundel** [comment]
Ready for review #673

**Comment by cjmyers** [comment]
@zachzundel The popup is now on remove of an object.  However, the remove collection on the manage submission page still deletes without confirmation.

**Comment by zachzundel** [comment]
Fixed on manage page.

**Comment by cjmyers** [comment]
Cancel remove still removes.

**Comment by cjmyers** [comment]
Fixed
