### ISSUE TITLE
Add a ability during setup to set the URI prefix

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#646]
Add to the Setup screen the ability to set the URI prefix.  There can be a big warning that says this is usually the same as the URL unless you are using this instance for debug purposes to pretend to be a different instance.  

The URI prefix should be used to set the following configurations in config.local.json:

  "databasePrefix": "\<URI prefix\>",
  "triplestore": {
 ...
    "defaultGraph": "\<URI prefix\>public",
    "graphPrefix": "\<URI prefix\>",
 ...
  },

Note that the URI prefix should end with a "/", or one should be added.  Finally, the URI prefix should be used to create the graph URI for the admin user that is created during setup, i.e.,

\<URI prefix\>user/\<adminId\>/

**Comment by zachzundel** [comment]
Ready for review #672

**Comment by cjmyers** [comment]
Works.
