### ISSUE TITLE
Annotation endpoint

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#651]
"Add/update an annotation" and "Delete an annotation" should be endpoints too, so that we can easily push and modify triples.

**Comment by cjmyers** [comment]
This will be restricted a single (or perhaps multiple) mutable namespaces.  Possibly the namespace for the instance, or the synbiohub namespace, or potentially any namespace outside a restricted group (sbol, prov, dc, dcterms, etc.).  My preferences it to keep it to a very small set (or even one) namespace to keep tight control on what is mutable in a record.

Question: should this endpoint be accessible from the GUI, and if so, what should the interface look like?

**Comment by cjmyers** [comment]
Addressed in PR #1270.  The support in API is using the add/edit/remove fields methods extended to annotations.  Not much error checking at this point though.  Essentially people can add any annotations they want.
