### ISSUE TITLE
Characters displayed as their Entity Number rather than as character.

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioHub/synbiohub#656]
Some characters such as **Δ** (delta) appear as their HTML Entity number (e.g. **``&#916;``** for delta) rather than as the actual character.

This problem occurs in the name field of component pages ([example](https://dev.synbiohub.org/public/igem/BBa_K925000/1)), and in the ``id (name)`` string in the results of a search ([example](https://synbiohub.org/search/BBa_K925000)). 

The problem does **not** occur in the name column of the table listing the members of a collection ([example](https://dev.synbiohub.org/public/iGEM_2017/Plasmid_pSB1C3/1)).

This problem was initially mentioned  in #652.

**Comment by cjmyers** [comment]
Fixed in 1.5.6
