### ISSUE TITLE
Submitting to Existing Collection Removes Overwritten Objects from Sub-Collections

### ISSUE THREAD

**Issue by nroehner** [SynBioHub/synbiohub#666]
The following example demonstrates this issue when uploading to the main SD2 instance of SynBioHub. Test files are attached in a zip. 

First, via the web GUI, submit the file sub_collection_upload_test_1.xml  to a new collection with the name and display_id "sub_upload_test" and description "This is a test." Second, again via the web GUI, submit the file sub_collection_upload_test2.xml to the existing collection sub_upload_test with Overwrite Existing Objects checked. 

If these steps are followed, then the description of the pBad promoter will be changed from "This is the pBad promoter." to "This is the best pBad promoter." as expected, but it will also be removed from the promoters sub-Collection.

Note that only the main SD2 instance of SynBioHub exhibits this behavior. If these steps are followed for the staging instance, the pBad promoter won't be removed from the promoters sub-Collection, but its description also won't be changed. Instead, a second pBad promoter entry will be added with the new description, thus causing an error when attempting to download the collection since now there are two copies of a promoter with the same identity but different descriptions.

It looks like the staging instance is an older version of SynBIoHub while the main instance is a newer version that fixes the older version's overwrite bug but introduces the new issue of removing overwritten objects from their sub-Collections.
[sub_collection_upload_example.zip](https://github.com/SynBioHub/synbiohub/files/2295216/sub_collection_upload_example.zip)

**Comment by cjmyers** [comment]
The staging and main SBH have the same version, but there was a difference in configuration. Can you double check whether or not they now perform the same?  Namely, they should both have the same bug you saw.

**Comment by cjmyers** [comment]
I think this one is sorted now.  I've added a replace end point which removes an object without removing its references.  This is the endpoint now used by submission.  This is updated on SBH Utah.  Please test.

**Comment by nroehner** [comment]
Looks like it's passing my test on SBH Utah.
