### ISSUE TITLE
Attachment download results in 502 Error

### ISSUE THREAD

**Issue by danbryce** [SynBioHub/synbiohub#670]
Retrieving https://hub.sd2e.org/user/sd2e/experiment/attachment_00009YTT3rZPD3qEj4wh4C/1/download results in a 502 error.

**Comment by cjmyers** [comment]
@danbryce This should be fixed now.  Please close this issue if you agree.

**Comment by cjmyers** [comment]
@zachzundel please make sure the docker image is updated to keep uploads in the  persistent store.

**Comment by danbryce** [comment]
It works now.  I tried with all the sibling attachments too. Thanks!
