### ISSUE TITLE
Updating registries on setup

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#674]
The setup procedure should update the registries from web-of-registries.  It should also include the instance being created in the list with the correct URI prefix and URL as provided during setup.  Finally, if this is spoofing an instance in WoR, then this record should replace the one from WoR.

**Comment by zachzundel** [comment]
Done. Tested by creating a new SynBioHub and setting the URI prefix to https://synbiohub.org.
Here is the Web of Registries right after creation:
![2018-08-30-14-38-49_1295x410](https://user-images.githubusercontent.com/3093325/44877856-8270c080-ac62-11e8-84b4-0f3c33e2aba2.png)

Also tested on an instance where I kept the default URI prefix, here is the WoR right after creation:
![2018-08-30-14-41-17_1282x361](https://user-images.githubusercontent.com/3093325/44877901-a7653380-ac62-11e8-8021-22a552b1cdd8.png)

So it looks like it's all working. Ready for review.
