### ISSUE TITLE
Update docker build to use docker compose

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#682]
- [x] Update docker build to use docker compose (building a microservice-esque image instead of monolith)
- [x] Update installation documentation
- [x] move SBH Utah to docker
- [x] move SBH to Docker

**Comment by zachzundel** [comment]
Converted Chris' comment to tasks

**Comment by zachzundel** [comment]
SynBioHub Utah is running on docker, after it has been running a while with no issues we should be good to move the reference instance to the composed config.

**Comment by zachzundel** [comment]
Why is this still open @cjmyers ?

**Comment by cjmyers** [comment]
Just testing 

Chris
