### ISSUE TITLE
When downloading a Collection non-recursively, the members property is empty

### ISSUE THREAD

**Issue by bbartley** [SynBioHub/synbiohub#683]
Is this as designed?  I was expecting it to download the Collection with all the member references left intact, while not actually fetching the referenced objects.

**Comment by cjmyers** [comment]
That is the expected behavior, and it is what I'm seeing.  Which collection are you not getting this behavior from?  Also, if you use libSBOLj, remember that getMembers() only returns linked members, but getMemberURIs() returns the references.

**Comment by bbartley** [comment]
> Also, if you use libSBOLj, remember that getMembers() only returns linked members, but getMemberURIs() returns the references.

That was probably the issue.  Thanks!
