### ISSUE TITLE
Components deleted when adding a new part to collection

### ISSUE THREAD

**Issue by Fontanapink** [SynBioHub/synbiohub#695]
I had a private collection with all the component parts for the genetic toggle switch. 
Created in SBOL a new document with the composition of parts. 
Uploaded the part to my private collection, being careful of not checking the "overwrite parts" checkbox so as to not delete the parts that were already there. 
But now only the composite Component is visible, with no other parts.

**Comment by cjmyers** [comment]
Please try again now.

**Comment by Fontanapink** [comment]
It's all there! Thanks

**Comment by cjmyers** [comment]
Sorry.  I had change the query for the list.  They are always there, but I had it set to filter the referenced parts since you can get at them by clicking on the composite.
