### ISSUE TITLE
Issue Uploading Xml to SBOL

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub#696]
Used SBOL Designer to create a xml file
upload xml file to new collection
The collection appears to display all correct parts but if I click on a part I get the error:

Error: getType: https://synbiohub.utah.edu/user/JMante/Asyntheticmulticellularsystemforprogrammedpatternformation/AY962288/1/GeneticToggleSwitch/1 not found
    at sparql.queryJson.then (/root/synbiohub/lib/query/local/type.js:17:35)
    at process._tickCallback (internal/process/next_tick.js:103:7)Error

**Comment by cjmyers** [comment]
Looks like you put “slashes” in your collection id.  This is unfortunately a bug, as this should not be allowed.

Can you try uploading with a simpler collection id?

**Comment by JMante1** [comment]
It is automatically generating the collection id. I just named the collection ToggleSwitchSBOL and retried but I get the same error

**Comment by cjmyers** [comment]
Can you send me a share link to the collection it generates?

**Comment by cjmyers** [comment]
Moved to SBOLDesigner issue #308
