### ISSUE TITLE
Delay in update of registries

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#708]
When a docker instance is first started and setup run, the registries list does not appear to get updated right away.  When you restart the docker container, it does get updated.  The symptoms are that any uploaded parts cannot be viewed.  You can open the collection but clicking on a part will not take you to the part of interest.

**Comment by zachzundel** [comment]
Why keep open both this and #647?

**Comment by cjmyers** [comment]
Forgot about the other one, which I noticed in closed.  The issue appears to not be a docker only issue, which should make it easier to track down.  Seems to be any updates are not immediate.  Not sure if this all config elements, but it could be.

**Comment by zachzundel** [comment]
Okay, I'm going to close the other one so that we only have one open for this issue.

**Comment by cjmyers** [comment]
That's fine.

**Comment by cjmyers** [comment]
Is this one still happening?

**Comment by zachzundel** [comment]
Yes
