### ISSUE TITLE
Virtuoso cannot be installed via APT

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#717]
`http://packages.comsode.eu/key/odn.gpg.key` is a 404, as is `http://packages.comsode.eu/debian`.

@udp: should we just build these ourselves for Docker? What should we do for the non-Docker install?

**Comment by zachzundel** [comment]
Decided to just pull the compiled binaries out of the tenforce image we used in the composed docker for the monolithic docker. Still an open issue for non-docker installs.

**Comment by cjmyers** [comment]
We should document how to build it from source.

**Comment by oflatt** [comment]
Right now the README points to the virtuoso repo, which has documentation for building it.
This seems reasonable to me. Should we close this issue, or is there something more to talk about?

**Comment by cjmyers** [comment]
Seems reasonable.  Closing.
