### ISSUE TITLE
Cannot view collections

### ISSUE THREAD

**Issue by palchicz** [SynBioHub/synbiohub#727]
**Steps to reproduce:**
1. Go to https://synbiohub.org/
2. Click "Browse Design Collections" button

**Expected Behavior** 
To be navigated to the design collections browse page

**Actual Behavior**
The following stack trach 
```
Error
TypeError: Cannot read property 'map' of undefined
    at sparql.queryJson.then (/opt/synbiohub/lib/query/local/collection.js:61:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

This seems to affect version `v1.4.0 (5fedd722)`

**Comment by cjmyers** [comment]
Database was down. Should be back up now. Please check

Thanks

Chris

**Comment by palchicz** [comment]
Looks resolved. Thanks!
