### ISSUE TITLE
Docker Image  v1.4.0 (47826858) cannot view members of collection

### ISSUE THREAD

**Issue by palchicz** [SynBioHub/synbiohub#728]
**Steps to Reproduce**
1. Create a new collection by uploading a genbank file with a single sequence
2. Navigate to the new collections page
3. Verify that the member of my collection appears in the `Members` table
4. Click on the "Name" field in the members table (link

**Expected Behavior**
Be navigated to the 'http://localhost:7777/<FILE_PATH>/<COLLECTION_NAME>/<MEMBER_ID>/1' (angle brackets added by me).

**Actual Behavior**
The following error message:

```
Error:http://localhost:7777/<FILE_PATH>/<COLLECTION_NAME>/<MEMBER_ID>/1 not found: http://localhost:7777/<FILE_PATH>/<COLLECTION_NAME>/<MEMBER_ID>/1
    at fetchSBOLObjectRecursive.then (/opt/synbiohub/lib/views/componentDefinition.js:86:35)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

This is what `docker log -f <CONTAIN_ID>` reports
```
0 URI(s) left to resolve
```

**Comment by cjmyers** [comment]
I believe there is a bit of setup that is not updated properly on first start.  Please try

sudo docker stop synbiohub
sudo docker start synbiohub

If that does not do it then please take screenshot of the admin registries page

Chris

**Comment by palchicz** [comment]
That seemed to do the trick. Thanks!
