### ISSUE TITLE
Synbiohub standalone producing the error when uploading a collection

### ISSUE THREAD

**Issue by jurquiza** [SynBioHub/synbiohub#742]
Error: split_to_n3 returned exit code 127
    at ChildProcess.splitProcess.on (/synbiohub/lib/sparql/sparql.js:369:28)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)

**Comment by jurquiza** [comment]
Forgot to mention this happens both in the public and in the standalone version installed with Docker

**Comment by cjmyers** [comment]
Can you please send the file you are uploading?  Also by public, do you mean https://synbiohub.org?

**Comment by jurquiza** [comment]
This happens in public and standalone. I git cloned the repo and followed the instructions for using docker with it. The services seems to be running fine though they SBOL I generated with SBOL Designer produces the error. I know this file should work as I have uploaded it in previous synbiohub repos

**Comment by cjmyers** [comment]
If you can share the file, that would really help so we can try to reproduce the problem.  Also, I want to make sure I'm understanding specifically the steps you are taking to get this error:

1) By public, do you mean you try to upload this file to https://synbiohub.org?  Or do you mean something else?

2) By "git cloned the repo and followed the instructions for using docker with it", do you mean these instructions:

http://wiki.synbiohub.org/wiki/Installation

Namely, the "From Prebuilt Image" steps?  Or something else?

**Comment by jurquiza** [comment]
1) by public I mean https://synbiohub.org/

2) The instructions in the wiki does not work anymore. However if I clone the synbiohub-docker and then I do docker-compose up then all works as expected. In both synbiohub.org and standalone current versions I get the error reported.

I attached the file to this comment just changed xml for txt. This files has worked before 

[AbstractLUC.txt](https://github.com/SynBioHub/synbiohub/files/2649606/AbstractLUC.txt)

**Comment by cjmyers** [comment]
Ok, I can reproduce this.  This does appear to be a problem with the new docker-compose deployment.  You can do submit on https://dev.synbiohub.org which is built from source rather than using docker-compose.  Thanks for reporting it.  We will have a look.

**Comment by cjmyers** [comment]
Should be fixed now.  There was an issue in the docker configuration.

**Comment by cjmyers** [comment]
We think this is all sorted now.  Could you please confirm when you get a chance?  

Thanks for catching this.
