### ISSUE TITLE
Dropping attachment fields from GenericTopLevels

### ISSUE THREAD

**Issue by bbartley** [SynBioHub/synbiohub#756]
The following serialization contains a GenericTopLevel object with properties in the SBOL namespace (e.g., displayId, wasGeneratedBy, attachments, etc).  It currently evaluates as valid by the SBOLValidator tool.

1. Should properties in the SBOL namespace be allowed in non-SBOL objects?
2. Is this explicitly legal according to specification?
3. For the most part SynBioHub appears to treat this as legal. It parses the SBOL properties correctly, except for the `attachments` field.  Is this a bug?
```
<?xml version="1.0" ?>
<rdf:RDF xmlns:prov="http://www.w3.org/ns/prov#" xmlns:sd2="http://sd2e.org#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:sys-bio="http://sys-bio.org#" xmlns:sbol="http://sbols.org/v2#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <sd2:ExperimentalData rdf:about="http://bbn.com/measurement0x2eginkgo0x2e7317_analysis_processed_data/1">
    <dcterms:title>measurement.ginkgo.7317 processed data</dcterms:title>
    <sbol:attachment rdf:resource="http://bbn.com/exp73170x2d310x2dds60969320x2emzML0x2esic0x2e1310x2e13670x2epeaks0x2ecsv/1"/>
    <sbol:displayId>measurement0x2eginkgo0x2e7317_analysis_processed_data</sbol:displayId>
    <sbol:persistentIdentity rdf:resource="http://bbn.com/measurement0x2eginkgo0x2e7317_analysis_processed_data"/>
    <sbol:version>1</sbol:version>
    <prov:wasGeneratedBy rdf:resource="http://bbn.com/measurement0x2eginkgo0x2e7317_analysis/1"/>
  </sd2:ExperimentalData>
</rdf:RDF>
```

**Comment by bbartley** [comment]
I think this is a bug.  Since GenericTopLevel inherits from TopLevel, the `sbol:attachment` field should definitely be allowed and not dropped by SBH.

**Comment by cjmyers** [comment]
You are correct.  This is a bug.  Will look into it.

**Comment by cjmyers** [comment]
It is a libSBOLj bug actually.  The GenericTopLevel copy method did not copy attachment links.  All others TopLevels copy it just fine.  I've fixed it in libSBOLj, and it will come with the next update of SBH, which we hope to be soon.

**Comment by cjmyers** [comment]
Ok, the libSBOLj issue fixes things so SBH does not drop the link anymore.  However, an attachment link that does not link to an attachment object is not currently rendered on the page.  We should have a fall back this case, so leaving this open for now.

**Comment by bbartley** [comment]
Confirmed working with the following test.
```
from pySBOLx import XDocument
from pySBOLx import Experiment
from sbol import PartShop

doc = XDocument()

# Initialize generic top level
e = Experiment('e')

# Create attachment and add to GTL
a = doc.attachments.create('a')
a.source = "file://dummy.txt"
a.format = "TXT"
e.attachments += [a.identity]

# Prepare Document for submission
doc.addExtensionObject(e)
doc.displayId = 'attachments_test'
doc.name = 'attachments_test'
doc.description = 'attachments_test'
print(doc.validate())

# Submit
sbh = PartShop('https://tang.ece.utah.edu/manage')
sbh.login(user, pw)
sbh.submit(doc)
```
