### ISSUE TITLE
Need an endpoint to check if an object exists

### ISSUE THREAD

**Issue by bbartley** [SynBioHub/synbiohub#769]
AFAIK there is not currently a canonical way to check if an object already exists in SBH, other than to use a try / catch clause and try to download it.  This is a little hacky and can result in non-optimal behavior.

A common use case is when I want to check whether a collection already exists before I attempt to add more items to it.  This use case comes up often in development and testing, as I often need to delete a test collection and start over.

**Comment by cjmyers** [comment]
Agree this is a bit of a hack.  I would assume something like <URI>/exists which returns true/false is what you are looking for.  This should not be too difficult.

**Comment by cjmyers** [comment]
@bbartley How about this endpoint:

<URI>/metadata

This endpoint returns basic metadata:

[{"persistentIdentity":"https://synbiohub.org/user/myers/Simple/Simple_module","displayId":"Simple_module","version":"1","name":null,"description":null,"type":"http://sbols.org/v2#ModuleDefinition"}]

If it does not exist, you get:

[]

**Comment by bbartley** [comment]
That's sufficient for my purposes.  

A general suggestion for this, and some of the other endpoints, is that a request should return a 401:  Unauthorized response if the user isn't logged in.  This endpoint returns [] in cases where the queried object does exist but the user is not logged in.

**Comment by cjmyers** [comment]
I'm not sure about this. This would allow people to know which objects exist.  By saying does not exist in both cases, it does not expose the URIs of objects in the private repository.  I guess one option would be to give a 401 for any URI in a user space outside your own, whether it exists or not.  However, there may exist objects in other graphs that you are allowed to see due being a co-owner of the part.  

Is there some reason that you prefer 401 rather than does not exist?

**Comment by bbartley** [comment]
> I guess one option would be to give a 401 for any URI in a user space outside your own, whether it exists or not.

This is exactly what I'm suggesting.  I would prefer to get a 401 error if I'm not authorized to view the user's graph, or if I'm not logged in, and therefore not authorized, to view my own graph.  This behavior should generalize to other endpoints as well.  In this case, the endpoint returns a false negative "[]".

**Comment by cjmyers** [comment]
Seems reasonable

**Comment by cjmyers** [comment]
Opened a new issue for the 401 error (see issue #858).  Closing this one.
