### ISSUE TITLE
Report when VISBOL rendering is omitted for being too large

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#771]
When a VISBOL rendering is omitted for being too large, it should be reported on the page, since otherwise the person would expect it to be there.

Similar warning messages might also want to be done for other places where we don't want silent failure, but obviously not for things that have no inherent rendering.

**Comment by cjmyers** [comment]
Currently it is difficult to distinguish between nothing to render and not possible to render.  Much of SBOL still resides outside what VisBOL can render.  For example, Modules and MapsTos are not rendered even with a full fetch.  Furthermore, some of the table information will be inferred when there is not a full fetch.  

Maybe what we should do though when there is no full fetch is add a message like:

"Record is very large, so only a partial record has been fetched.  Click here to attempt to fetch the entire record.  Note that this operation may slow or not be successful."

This would allow us to still have access to the full record, but have users know when the operation may be slow or unsuccessful.

The not being able to rendering some SBOL information is a much trickier one.   An empty rendering may result when a record includes only content that cannot be rendered.  However, it may not be an empty rendering.  For example, a record with FCs and interactions will render, but Modules and MapsTos will not be in the diagram.  Furthermore, other SBOL information may never appear in a diagram.  Finally, in the future, the VisBOL renderings are going to abstract away details meaning that some information is intentionally left out of the diagram.  My feeling is that the VisBOL diagrams should never be considered as the ground truth of the record but simply a limited visual aid.

**Comment by jakebeal** [comment]
Your proposed "no full fetch" statement sounds reasonable.

I agree that VisBOL is just a visual aid, but it's an extremely valuable one, and for any CD or MD one should get some hint on why you aren't getting a visualization if you don't get one.

**Comment by zachzundel** [comment]
@cjmyers -- can this be closed?

**Comment by cjmyers** [comment]
No, I've only handled half of this issue so far.

**Comment by zachzundel** [comment]
Okay, then moving to 1.5.0.

**Comment by cjmyers** [comment]
Decided to just update the message to mention there is no VisBol rendering.
