### ISSUE TITLE
Tester does not fail on roundtrip test errors

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#799]
When the roundtrip test errors, it appears to exit testing with success.

**Comment by oflatt** [comment]
How were you able to get these results, @cjmyers ? I can't seem to replicate it.

**Comment by cjmyers** [comment]
I had broken the SBOLTestrunner, and it still showed pass even though the tester was failing.  To reproduce, you likely need to break the SBOLTestrunner temporarily.  Maybe edit a test case to make it invalid SBOL.

**Comment by oflatt** [comment]
Thanks, the way in which I was breaking it was making it exit correctly. Changing a sbol file allowed me to replicate it.

**Comment by oflatt** [comment]
This has been addressed.
