### ISSUE TITLE
Implementations should say they are implementations

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#811]
If you browse to an implementation, you have no idea what you are looking at, since nowhere on the page does it actually say the type of the item.

Example: https://hub.sd2e.org/user/sd2e/biofab_yeast_gates_q0_aq_10833/s2077/1

**Comment by cjmyers** [comment]
What would you like to see?  We could add the VisBOL rendering of the item found on the built link, for example.

BTW: there is no built link here.  I thought if something was built, you would always have the built and wasDerivedFrom links, but they could point to the same thing when you have no evidence that they are different.

One tricky thing is the built link could be a CD or MD, so it would have different information available.  Also, you can have multiple wasDerivedFrom links, like I do with Addgene data that points to both the original record at Addgene and the thing that was built.  Therefore, some wasDerivedFroms may not even be de-referenceable.  Therefore, I think you must have a “built” link, so I can be sure of type of object.

**Comment by jakebeal** [comment]
I'm thinking something much simpler.
At the top of a ModuleDefinition you get something like: "M9_glucose_CAA Version 1  (Module) "
At the top of an Implementation like this one you get: "s2077 Version 1  (unknown)"

Instead of "(unknown)" it should be "(Implementation)".  Likewise, anything you can link to should say its type (or alias, like we do for MD->Module), rather than "(unknown)"

**Comment by cjmyers** [comment]
Oh, that is simpler.  That is already done, see:

https://hub-staging.sd2e.org/user/sd2e/biofab_yeast_gates_q0_aq_10833/s2077/1

Is that all you are looking for?  Notice that it also tells you the Name of the built object.

**Comment by jakebeal** [comment]
Ah, so it's already been resolved by the next deployment when you update?  If so, then great, and this issue can be closed.

**Comment by cjmyers** [comment]
Yeah, please check look and feel issues on staging.  I think it is much better.  Matt confirmed he can migrate this to production next week.
