### ISSUE TITLE
Module roles are not being reported

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#813]
On a module, such as: https://hub.sd2e.org/user/sd2e/design/TE0x2C0x20pH0x2080x2E0/1, a role property is set but does not appear anywhere on the page.

**Comment by cjmyers** [comment]
This is also handled on staging:

https://hub-staging.sd2e.org/user/sd2e/design/TE0x2C0x20pH0x2080x2E0/1
