### ISSUE TITLE
After submission, redirect to something in the submitted file.

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#814]
Right now, after you submit you get redirected unceremoniously back to the root submissions page. I always want to go check on what I've submitted, though, so it'd be a lot better if I was redirected to something in what I'd submitted.

Possibilities:
1. The first TopLevel in the file
2. The first "root" TopLevel in the file, e.g., a collection that contains many things.

The first should be easy; the second would be harder, but given that most SBOL is machine-generated with the root at the top, might be approximated well by the first anyway.

**Comment by cjmyers** [comment]
Sounds reasonable, and it should not be too difficult.
