### ISSUE TITLE
Cycle log files and add useful information for debuggging

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#823]
On a restart due to a crash, should copy the log file to a new unique file name for later debugging.

Should also limit size of log file and copy log files to rolling log backups, like in linux.  Such as synbiolog.log.#.  The # field should when it reaches a limit delete the log.

Finally, it would be good to add to these log files some time stamps periodically, so we know when the messages are occurring.  And we should make sure that endpoints hit are added to the log.

**Comment by zachzundel** [comment]
This was closed by #860 .
