### ISSUE TITLE
Login problems with testing

### ISSUE THREAD

**Issue by oflatt** [SynBioHub/synbiohub#831]
When synbiohub is set up through the setup page manually, you are automatically logged in. This does not seem true for running a post request to the setup page to do the same thing.

Also, after logging in as admin through a post request, the response shows a logged-in page. However, getting the page again, admin seems to be logged out again. Am I missing something important?

**Comment by cjmyers** [comment]
Logging in through the webpage and through post requests is different.  In the later, you get returned an token that needs to be used on all subsequent requests.  In the former, you get a session which saves your user information.  I think this requires a browser for this to work, I assume.

**Comment by oflatt** [comment]
That makes sense- thanks, I'll have to implement a state machine for the tests to save login information.

**Comment by oflatt** [comment]
With the refactor to TestState, login info is saved.
