### ISSUE TITLE
Removing public submission throws error but performs removal

### ISSUE THREAD

**Issue by oflatt** [SynBioHub/synbiohub#846]
Sending a get request to the /public/:collectionId/:displayId/:version/removeCollection endpoint results in an error but still removes the public collection.
Example:
Get request to http://localhost:7777/public/test/test_collection/1/removeCollection
Response:
HTML: Removing public submissions is not allowed
Https error: 500 internal server error

**Comment by cjmyers** [comment]
Yikes!  Good catch.
