### ISSUE TITLE
Support bulk-updates of properties

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#852]
We need to be able to update property values through an API (e.g., to fix ontology terms, update a custom annotation, etc.)

(different from #787 because it's through an API, not the web interface)

**Comment by zachzundel** [comment]
@jakebeal does the admin SPARQL page meet your needs here?

**Comment by jakebeal** [comment]
Browsing the admin SPARQL page, I don't see anything about a programmatic API?

**Comment by cjmyers** [comment]
Sorry that it is not documented, but it is there.  The endpoint is <URL>/admin/sparql.  You must be login as an admin and send your login token in the header.  I will add a wrapped call to the endpoint in Java.  You might ask Bryan to add one to pySBOL.

**Comment by cjmyers** [comment]
I've added documentation to the wiki for the admin sparql interface.

http://wiki.synbiohub.org/wiki/HTTP_API#GET_endpoint_to_perform_a_SPARQL_admin_query

I've also added a wrapped admin sparql function in libSBOLj. 

Would still be nice to add this to pySBOL as well.
