### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by 3ach** [SynBioHub/synbiohub#855]
The SynBioHub runner is flaky, it occasionally requires multiple runs before succeeding.

**Comment by cjmyers** [comment]
Strange.  What kind of errors do you see?  Is it the runner or are you running into Too Many Open Files issues?

**Comment by zachzundel** [comment]
This does not appear to be related to #639. This happens on Travis -- runs sometimes have to be redone to succeed. I have not tried to recreate the issues locally. There is not enough debug output printed in Travis to tell me what the problem is.

**Comment by zachzundel** [comment]
This should (hopefully!) be easier to debug with #869
