### ISSUE TITLE
JBEI-ICE ACS and PUBLIC removed 

### ISSUE THREAD

**Issue by jurquiza** [SynBioHub/synbiohub#862]
Just wondering if Synbiohub public will have ICE-ACS and ICE-PUBLIC collections back?

**Comment by cjmyers** [comment]
It looks like their SSL certificates are expired.  I've let them know.

**Comment by cjmyers** [comment]
This is working again on the development instance (https://dev.synbiohub.org <https://dev.synbiohub.org/>).  Please check it out.

It will be working again on main instance after next update.

**Comment by cjmyers** [comment]
This is fixed
