### ISSUE TITLE
Request publication of data

### ISSUE THREAD

**Issue by jurquiza** [SynBioHub/synbiohub#863]
we are planning to recommend SBH however one concern is whether users will be able to make their design public at the final stage of their projects?

**Comment by cjmyers** [comment]
Yes, this is supported.  When you submit, it goes into a private repository visible only to the user and those s/he provides a share link to or adds as owners.

When the design is complete and well documented, you can click on the Make Public button to publish it into either an existing or new public collection. 

I would be happy to provide a demo, if you like.

**Comment by cjmyers** [comment]
Actually, I just had a thought.  Are you meaning that you want to have designs on your own instance of SBH then publish them into a different public instance.  If so, this is not something that we currently support, but it likely would not be too difficult to add support for in the future.

**Comment by jurquiza** [comment]
sorry I mean you public instance 

https://synbiohub.org

**Comment by jurquiza** [comment]
Sorry I mean on you public instance i cannot make collections public. This feature is blocked.

**Comment by cjmyers** [comment]
Ah, right, I see now.  Making public is restricted to only those users marked as Curators.  They need to approve the record before it can be made public.  The procedure is you need to send a share link to the curator, and they will then be responsible for making your record(s) public.  

However, I see the dilemma is that you may not know who are the curators for this instance.  We should add a feature that allows you to share with curators, which would automatically email the share links to those users that are marked as curators in the user database.

**Comment by zachzundel** [comment]
So, to be clear: if you are not a curator, you should be able to request that a curator makes a construct publicly accessible? And this curator would then receive a share link to check the construct is sufficient to publish?

**Comment by cjmyers** [comment]
Yes, that is the idea.  Maybe this is also a "security" issue, since it relates to share links.

**Comment by zachzundel** [comment]
I'm not convinced it is a security issue, but definitely makes sense to me
in data pipeline.

**Comment by aromanowski** [comment]
Hi everyone,
Have there been any developments towards easier sharing of collections?

Thank you!

**Comment by cjmyers** [comment]
Hi @aromanowski, sorry there has not been progress on this particular issue.  I'm going to bump up its priority, since it is related to see work that we are doing on improving the authentication module.  In the new authentication module, you can share your designs and other objects in SBH with other users.  You can give these other users view/edit/share privileges.  If you are not a curator and you want to make a part public, you must share this part with a curator and give the curator share privileges.  The one element that is missing in our current prototype is a way to know which users are curators.

@3ach In the list of users you can select from, can we add to their names, their status on SBH?  Something like: "John Doe (Curator)" or "Jane Doe (Curator/Admin)"?

**Comment by aromanowski** [comment]
Hi @3ach  and @cjmyers! Thank you for the update. Adding the (curator) status next to the names or maybe adding a public sharing button that would allow any user to share their collections would be great. Perhaps this could be complemented by a 3-step process:

1) User decides to make his collection public by pressing the proper button.
2) A curator is alerted and can see the collection and then recommend changes or allow public sharing.
3) Outcome 1: Collection is shared. Outcome 2: collection is returned to owner until they satisfy requirements por public sharing.

Thank you!
A

**Comment by cjmyers** [comment]
@aromanowski these are good recommendations.  Would you mind opening a new issue for this?  Thanks.
