### ISSUE TITLE
When converting GenBank/FASTA files may need to uniqueify identifiers

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#864]
Some software like SnapGene give the same LOCUS identifier (Exported) to all exported GenBank files.  This is problematic, since this is used as the SBOL identifier, and if multiple files are uploaded they will all have the same identifier.  In this case, should uniqueify the identifiers.

**Comment by cjmyers** [comment]
Perhaps based on the file names.

**Comment by zachzundel** [comment]
Can this be closed @cjmyers ?

**Comment by cjmyers** [comment]
Yes, this was fixed.
