### ISSUE TITLE
Print the logs when the test fails

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#869]
Output the logs from the synbiohub container when a test fails.

**Comment by oflatt** [comment]
How should it decide how much of the log to print each time a test fails?
I could set a set constant number of lines, or do something fancier involving the logging work Zach is doing.

**Comment by cjmyers** [comment]
Good question.  The tricky thing is that if an early test fails then you continue, the actual failure may be hiding deep in the log.  

Zach and I discussed different logging levels, and I think we came up with:
error - serious problem, such as uncaught exceptions, unhandled promises, etc.
warn - messaging that is not failing, such as maybe a file that was submitted had validation problems.
log - selected useful information about progress
debug (or verbose) - very detailed messaging of every step being taken

I would say that we would want log level for this probably.

**Comment by oflatt** [comment]
Should this wait for logging to be merged?

**Comment by cjmyers** [comment]
Yes that makes sense

Chris

**Comment by zachzundel** [comment]
Logging is merged, so @oflatt you can take this back up.
