### ISSUE TITLE
Part page error in docker containers

### ISSUE THREAD

**Issue by oflatt** [SynBioHub/synbiohub#872]
Right now, if I upload a file to a synbiohub instance running locally, the component pages work.

However, if I am running from the docker containers, I get an error in page that says

Error: http://localhost:7777/user/testuser/testnew/BBa_J23119/1 record not found: http://localhost:7777/user/testuser/testnew/BBa_J23119/1

**Comment by cjmyers** [comment]
This sounds like the old setup bug where the registry needs to include the local instance to work correctly 

Zach: what do u think?

Chris

**Comment by oflatt** [comment]
Pages render after restarting containers without clearing the volumes. It's just the first time you create a collection.

**Comment by cjmyers** [comment]
This problem sounds familiar.  I think this is an issue with the registry not being updated initially.  I thought we had fixed this, but maybe not.  Zach?

**Comment by cjmyers** [comment]
@zachzundel Is this the strange restart error we were seeing before?

**Comment by zachzundel** [comment]
This sounds like the same error. PR #767 fixed the issue. @oflatt : maybe look for similar code (pulling from config at startup) that could be causing. 

One way to test if this is the *exact* same type of error is to create new synbiohub containers, bounce them, *then* try uploading something. If you can see it straight away, it is probably this exact same type of error somewhere.

**Comment by zachzundel** [comment]
@oflatt have you found anything else out here?

**Comment by oflatt** [comment]
Forgot to close this issue- should have been fixed by #879
