### ISSUE TITLE
Errors not reported in status code

### ISSUE THREAD

**Issue by oflatt** [SynBioHub/synbiohub#878]
In some places, errors are caught without sending an appropriate error code. If it sent a code, the test suite would be able to catch more errors.

**Comment by zachzundel** [comment]
Can you provide places? Either here or opening individual issues.

**Comment by oflatt** [comment]
The one that I have observed is in the catch in topLevelView.js
Chris and I were talking about the various catches in the source code. Some of them are for functionality, and some report errors.

**Comment by cjmyers** [comment]
Largely addressed by API refactoring.
