### ISSUE TITLE
Activity type page: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by oflatt** [SynBioHub/synbiohub#880]
I'm getting the error TypeError: Cannot read property 'map' of undefined on all activity component pages.

**Comment by oflatt** [comment]
Is this just me? I'm also getting
TypeError: Cannot read property 'forEach' of undefined
on component pages like that for BBa_I0462

**Comment by cjmyers** [comment]
I’m not seeing this error.  Are you seeing this on a local instance or the reference instance?

**Comment by oflatt** [comment]
I'm seeing this on synbiohub running locally and synbiohub running from the docker containers,
on branch master. It seems to only affect non-public submissions made after some recent point in time, but I can't be completely sure.

**Comment by cjmyers** [comment]
Hmm, I think I will need to see this.

**Comment by cjmyers** [comment]
Fixed.  Needed to update sboljs and java
