### ISSUE TITLE
UWBF_16967 is broken

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#887]
When I browse to: https://hub.sd2e.org/user/sd2e/design/UWBF_16967/1

I get the following inscrutable error:
> TypeError: Cannot read property 'forEach' of undefined

The same thing seems to be happening for a number of other UWBF yeast strains as well.

**Comment by cjmyers** [comment]
This error message occurs because something in the SBOL is unexpected.  Agree that the error message is not good.  This particular record has the following problem:

In this functionalComponent within this ModuleDefinition:

https://hub.sd2e.org/user/sd2e/design/UWBF_16967/UWBIOFAB_22544/1 <https://hub.sd2e.org/user/sd2e/design/UWBF_16967/UWBIOFAB_22544/1>

It has a definition property that points to this object:

https://hub.sd2e.org/user/sd2e/design/UWBIOFAB_22544/1 <https://hub.sd2e.org/user/sd2e/design/UWBIOFAB_22544/1>

This object is actually a ModuleDefinition.  A functionalComponent thought must point to a ComponentDefinition.  So, this is invalid SBOL.  SBH assumes that the SBOL is valid and it is trying to get information about a ComponentDefinition, and when it stumbles on a ModuleDefinition it breaks assumptions that are made in the code.

My guess as how this occurred is that the original object was uploaded with a CD at this URI.  Then, a new object was uploaded to this collection with overwrite turned on, which had a different object, an MD at this URI.

So, this highlights several issues:

1) Need better error checking and reporting when unexpected objects or fields show up in an dereferenced SBOL object.

2) Need better error checking when upload with overwrite to ensure that when you replace an object that you are not causing problems with references to the existing object.

**Comment by jakebeal** [comment]
We also need to get that SBOL corrected, which I think is afflicting all of the yeast strains. Can you do a triple-surgery fix?

**Comment by cjmyers** [comment]
There is a couple ways this can be done.  We can wait for the deployment to give us SPARQL update and do triple surgery, but we could also fix it now using replacement of objects.  The key question though is what went wrong and what should be the correct data.  

Namely, should this have been a Module reference to a ModuleDefinition?  Is the definition in the FC wrong and it should be pointing to some other CD?  Who generated this and how?  

Once we know what it should be, we can see what the best way forward is to repair it.

**Comment by jakebeal** [comment]
This is probably generated by @nroehner's work on curation in some way.  Nic, can you please work with Chris to sort this out?

**Comment by cjmyers** [comment]
Running this query found there are several of these problems:

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX sbol: <http://sbols.org/v2#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX purl: <http://purl.obolibrary.org/obo/>

select ?s ?type where {
  ?s sbol:functionalComponent ?fc .
  ?fc sbol:definition ?def .
  ?def a ?type
         Filter (?type != <http://sbols.org/v2#ComponentDefinition>)
         }



s	type
https://hub.sd2e.org/user/sd2e/design/NEB_10_beta_pAN1201_Larabinose_aTc_IPTG_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/NEB_10_beta_pAN1717_Larabinose_aTc_IPTG_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/NEB_10_beta_pAN3928_pAN4036_Larabinose_aTc_IPTG_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_0_aTc_0_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_0_aTc_0_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_0_aTc_0p002_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_0_aTc_0p002_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_5_aTc_0_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_5_aTc_0_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_5_aTc_0p002_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1201_Larabinose_5_aTc_0p002_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_0_aTc_0_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_0_aTc_0_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_0_aTc_0p002_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_0_aTc_0p002_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_5_aTc_0_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_5_aTc_0_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_5_aTc_0p002_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN1717_Larabinose_5_aTc_0p002_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_0_aTc_0_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_0_aTc_0_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_0_aTc_0p002_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_0_aTc_0p002_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_5_aTc_0_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_5_aTc_0_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_5_aTc_0p002_IPTG_0_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/transcriptic_rule_30_q0_1_09242017/NEB_10_beta_pAN3928_pAN4036_Larabinose_5_aTc_0p002_IPTG_1_system/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_5992/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_5993/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_6388/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_6389/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_6390/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_8544/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_16967/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_5783/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_6391/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_7299/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_7300/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_7373/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_7374/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_7375/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_7376/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_7377/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_8225/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_8231/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_8542/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_8543/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_8545/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_16968/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_16969/1	http://sbols.org/v2#ModuleDefinition
https://hub.sd2e.org/user/sd2e/design/UWBF_16970/1	http://sbols.org/v2#ModuleDefinition

**Comment by cjmyers** [comment]
This is fixed in PR #912.
