### ISSUE TITLE
Missing designs in SD2 SynBioHub

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#888]
The designs collection is full of things that are missing when you click their link.

Some examples:
* https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_4/1 not found
* https://hub.sd2e.org/user/sd2e/design/YG_plasmid_0036_seq/1 not found

I'm also getting lots of apparently random "502 Gateway Not Found" errors

**Comment by cjmyers** [comment]
It looks like these objects were removed, but somehow not removed from the list of members of the collection.  Do you believe these were removed by mistake OR should have been removed from the list of members?

What are you doing when you receive the 502 Gateway Not Found errors?

**Comment by jakebeal** [comment]
With regards to the 502 errors: just opening collections.  They seem to randomly error instead of opening.

@nroehner @bbartley Do either of you know whether these protein designs were supposed to be removed? My assumption is they are supposed to be there and should be restored.

**Comment by cjmyers** [comment]
@jakebeal This query finds all Collection members that do not point to an actual object:

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX sbol: <http://sbols.org/v2#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX purl: <http://purl.obolibrary.org/obo/>

select ?s ?p ?o where {
  ?s sbol:member ?o
  FILTER NOT EXISTS { ?o a ?type }
  }

**Comment by cjmyers** [comment]
s	p	o
https://hub.sd2e.org/user/sd2e/design/yeast_gates/1	
https://hub.sd2e.org/user/sd2e/design/YG_plasmid_0025_seq/1
https://hub.sd2e.org/user/sd2e/design/yeast_gates/1	
https://hub.sd2e.org/user/sd2e/design/YG_plasmid_0036_seq/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_design_9/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_design_8/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_design_11/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_design_10/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017_design_7/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017_design_6/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017_design_5/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017_design_4/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/id00001/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/id00001_seq/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_10/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_10/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016_computational_scores_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested_computational_scores_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016_computational_scores_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested_computational_scores_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested_computational_scores_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016_computational_scores_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science_computational_scores_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science_computational_scores_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science_computational_scores_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested_computational_scores_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017_computational_scores_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested_computational_scores_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017_computational_scores_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017_computational_scores_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested_computational_scores_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017_computational_scores_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017_computational_scores_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017_computational_scores_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested_design_7/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested_design_6/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested_design_4/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_topology_mining_March_2018_untested_design_5/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science_design_8/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science_design_9/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science_design_11/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science_design_10/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017_design_7/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017_design_5/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017_design_4/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva2_Dec_2017_design_6/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested_design_10/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested_design_9/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested_design_8/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_untested_design_11/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_sequence_6/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_sequence_5/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_5/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_sequence_4/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_4/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_sequence_7/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_6/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/Collection_protein_designs/1.0.0
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/design_protein_design_data_v1_April_2018_Longxing_Dec_2017_design_7/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_designs/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_9/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_8/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_7/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_6/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_9/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_8/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_7/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_3/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_5/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_6/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_4/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_3/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_5/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_sequence_4/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Longxing_Dec_2017_computational_scores_design_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016_design_2/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016_design_0/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016_design_3/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Inna_April_2016_design_1/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Rocklin_2017_Science/1
https://hub.sd2e.org/user/sd2e/design/design_collection/1	
https://hub.sd2e.org/user/sd2e/design/protein_design_data_v1_April_2018_Eva1_Dec_2017/1

**Comment by cjmyers** [comment]
I ran this delete query on staging and all the dangling member references were removed:

<img width="1194" alt="Screen Shot 2019-05-01 at 8 34 46 PM" src="https://user-images.githubusercontent.com/3507191/57055491-a7ce2800-6c50-11e9-8961-fc58c44bb345.png">

**Comment by cjmyers** [comment]
Have a look in the design collection:

https://hub-staging.sd2e.org/user/sd2e/design/design_collection/1

**Comment by cjmyers** [comment]
These have been deleted from production:

https://hub.sd2e.org/user/sd2e/design/design_collection/1
