### ISSUE TITLE
Add a find by sequence feature

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#894]
Would be nice to be able to search by sequence and even better is to find similar sequences.

**Comment by zachzundel** [comment]
I know @derethanhausen wrote a SynBioBLAST utility that may be able to serve this function.

**Comment by zachzundel** [comment]
https://github.com/schnauzer/synbioblast

**Comment by cjmyers** [comment]
Right, I forgot about that.  Could be a useful starting point.

**Comment by cjmyers** [comment]
Now supported via SBOLExplorer
