### ISSUE TITLE
SBOL visual glyphs not showing for SBOL Module

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#895]
I am browsing over the Bacillus subtilis Collection and for parts that are classified as type Module, there are no SBOL visual glyphs shown. 

[Here](https://synbiohub.org/public/bsu/SyBiOntKB2sbol/1) is an example of a Module taken from this collection that has this issue.

**Comment by zachzundel** [comment]
Verified this issue with @tramyn and could not see any obvious errors in the browser console. Download Image was still an option, so it appears VisBOL might have failed.

**Comment by cjmyers** [comment]
Sorry module view was not turned on.  Should work now @tramyn please test

**Comment by zachzundel** [comment]
Still does not work on the link @tramyn included.

**Comment by cjmyers** [comment]
That link is an Activity not a Module

See this Module, for example:

https://synbiohub.org/public/bsu/module_BO_32477_encodes_BO_26583/1 <https://synbiohub.org/public/bsu/module_BO_32477_encodes_BO_26583/1>

**Comment by cjmyers** [comment]
Should be working now.
