### ISSUE TITLE
Need to sort all lists on pages to make for stable testing

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#899]
All lists on pages need to be sorted to make sure the HTML renders the same each time for testing.  Should make search case-insensitive with fallbacks for equals.  Should restore tests that were failing due to sort once done.

**Comment by cjmyers** [comment]
Fixed by PR #906

**Comment by zachzundel** [comment]
Not as fixed as we'd hope. https://travis-ci.com/SynBioHub/synbiohub/builds/110266522

**Comment by cjmyers** [comment]
Linked travis build above is now working.  However, not completely convinced this is sorted yet.

**Comment by cjmyers** [comment]
Seems to be working.  Closing for now.
