### ISSUE TITLE
Show all attachment images

### ISSUE THREAD

**Issue by zachzundel** [SynBioHub/synbiohub#918]
Not just PNG

**Comment by cjmyers** [comment]
I've added support for jpeg, tiff, and bmp.  Any others?

**Comment by cjmyers** [comment]
Done

**Comment by jakebeal** [comment]
Looking at: https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support, I would suggest also adding GIF and SVG

**Comment by cjmyers** [comment]
I tried adding SVG, but it does not look like we can easily detect an SVG file.  When we attach an SVG, it gets tagged as XML.

**Comment by jakebeal** [comment]
That makes sense because SVG _is_ an XML format. You can probably detect it just by parsing past the header and seeing if it is an SVG XML.

**Comment by cjmyers** [comment]
I’ve added support for GIF.  I tried to see if SVG would render by allowing files of type XML to render, and it did not render in the browser.  I’m not sure if SVG will render using the same scheme we are doing for the other file types.  In any case, this is a heavier lift than we want for 1.5.1.  If you think it is important to render SVG, please open a new 1.6.0 issue.

**Comment by cjmyers** [comment]
Also considering the table in the link, it looks like browsers do not support SVG well, so it is likely better to leave it off.

**Comment by jakebeal** [comment]
I'm fine to leave SVG off until somebody needs it.

**Comment by cjmyers** [comment]
Added GIF in PR #932
