### ISSUE TITLE
Edit annotations in web page, constrained by configurable list

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#919]
It should be possible to edit annotations in the web page, at least for numbers, strings, and URIs.

The namespaces of the annotations, however, should not be totally open: there should be a configurable list of recommended annotations that SynBioHub looks at to:
1. Suggest classes of annotation (e.g., in a drop-down)
2. Constrain the annotation's type
3. Allow but warn if somebody picks an "other" annotation and writes their own.

**Comment by jakebeal** [comment]
For example, one might configure a particular deployment to pull a list from the "attributes" page of the SD2 Dictionary.

**Comment by zachzundel** [comment]
Moving this to 1.6
