### ISSUE TITLE
sbh:topLevel Not Removed From Uploaded Objects

### ISSUE THREAD

**Issue by nroehner** [SynBioHub/synbiohub#924]
After copying an object that I downloaded from SynBioHub into a new namespace, I uploaded the copy to SynBioHub and re-downloaded it, only to discover that the object now had two sbh:topLevel properties, While this could be avoided by changing our library copy methods to remove sbh properties, this seems like an issue that should be fixed on the SynBioHub end by removing existing sbh properties from uploaded objects before creating new ones.

**Comment by cjmyers** [comment]
Overlaps issue #498
