### ISSUE TITLE
Can't delete attachments on page where they have been added.

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#931]
Once an attachment has been added, it cannot be deleted from the page where it has been added. It took me a while to realize that I had to click through to the attachment, delete it directly (which doesn't make it obvious that it will delete the relationship), then lose my navigation as I get bounced to the root collections page again.

It would be much simpler to have a little "X" to let you delete attachments on the page where you are looking at them.

(discovered while playing with things relating to #913)

**Comment by cjmyers** [comment]
Agree that this would be a good feature to have.
