### ISSUE TITLE
Pencils still showing up for public parts

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#942]
Public parts should not allow name/description/roles or other SBOL elements to be edited, so the pencil should not be visible on public parts.

**Comment by 3ach** [comment]
I can't reproduce this. Where are you seeing it?

**Comment by cjmyers** [comment]
Here, for example:

https://synbiohub.programmingbiology.org/public/Eco1C1G1T1/Eco1C1G1T1_collection/1

**Comment by cjmyers** [comment]
This bug is still here, but will delay to 1.5.2 as a priority.
