### ISSUE TITLE
copy shared collection

### ISSUE THREAD

**Issue by jurquiza** [SynBioHub/synbiohub#943]
got a an error 

https://synbiohub.org/user/jurquiza/Wild/Wild_collection/1/9ec2ad54b4d0383008cce1863023ac688ba2649b/share/cloneSubmission not found

when clicking copy in shared submissions

**Comment by cjmyers** [comment]
Good catch.  This endpoint is indeed not exposed for shared objects.  It might be tricky, since I assume it would copy it from another's graph to your own graph.  However, it is likely good to support this.

**Comment by cjmyers** [comment]
Clone has been removed.
