### ISSUE TITLE
GenBank exports lose names

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#944]
GenBank exports come out with anonymous features.  Here is an example:
https://synbiohub.org/public/igem/BBa_K808000/1
https://synbiohub.org/public/igem/BBa_K808000/1/BBa_K808000.gb

The SBOL knows the features are AraC, AraO, AraO1, and AraPromoter, but the GenBank loses that information.

**Comment by cjmyers** [comment]
You mean the label is missing, the SO type has no corresponding one in GenBank as far as I know,

This is a libSBOLj issue, since SynBioHub just uses libSBOLj for GenBank conversion, so you should log your issue there.

Please indicate what you think the GenBank file should look like in your issue.

**Comment by jakebeal** [comment]
Issue opened; I'd like to leave this issue open as well until the libSBOLj issue is resolved and a new version of SynBioHub incorporating it is deployed: until then, this issue is not resolved for me.

**Comment by cjmyers** [comment]
Fixed in libSBOLj, should be part of next release.
